### ISSUE TITLE
[Question] Cluster not splitting apps across multiple nodes

### ISSUE THREAD

**Issue by dhamaniasad** [caprover/caprover#1009]
I set up a Caprover cluster with 2 nodes. I had an app running and I increased the number of instances for it, but it didn't start any instance on the added worker node. I noticed the app had the node ID of the master server in the configuration, I replaced that with the node ID of the worker. That moved all the containers for that app to the worker. I tried removing the node ID, as it says `Leave empty for automatic placement` but it automatically sets it up on the worker node ID over and over again.

Is it not possible to run 1 app across multiple nodes in the cluster?

**Comment by githubsaturn** [comment]
There are two types of app, with persistent data and without persistent data.

Looks like you're app has persistent data (a mapped directory or volume).

You cannot move this type of app around because the data is stored on the disk of one of the nodes. 


When you create an app, if you don't check the box for Persistent Data, your app can be move around freely.

**Comment by dhamaniasad** [comment]
@githubsaturn My app doesn't have any persistent data.

![image](https://user-images.githubusercontent.com/4560482/107617021-1f7a1500-6c75-11eb-8756-e596178ed9e8.png)

**Comment by dhamaniasad** [comment]
Actually nevermind, I mistakenly checked this button when I created the app. I destroyed it and recreated it again without that button checked, and the app scales across nodes in the cluster just fine. Thanks @githubsaturn !

<img width="531" alt="Screenshot 2021-02-11 at 2 48 59 PM" src="https://user-images.githubusercontent.com/4560482/107618878-484fd980-6c78-11eb-9dd4-774186f30c18.png">
