### ISSUE TITLE
Caprover behind a proxy fails to fetch one-click apps

### ISSUE THREAD

**Issue by patternoia** [caprover/caprover#1037]
In our corporate network we have a squid proxy installed and all the network traffic should be routed through it.
This makes the axios to pick up the `https_proxy` from the environment and attempt to use it and fail with HTTP 501. It is a [known issue](https://github.com/axios/axios/issues/2072) in axios and they are not fixing it since ages and suggest everyone to use workarounds. One possible workaround which works for me is to use `axios-https-proxy-fix` package.

Can you please look into this? Alternatively I can prepare a PR with my workaround.

**Comment by githubsaturn** [comment]
Rather we don't introduce a random package in the backend for this uncommon usecase. Also, I don't understand how axios picks up `https_proxy` from the environment. The axios instance that fetches oneclickapps sits in a Docker container in the backend.

A better option option for you is to have your own one click repository that is mirroring the official repository:
https://github.com/caprover/one-click-apps#build-your-own-one-click-app-repository

It can be hosted within your network such that it doesn't need to go through the proxy.

Otherwise, if you have a solution that doesn't require an external package, feel free to introduce.

**Comment by patternoia** [comment]
As I mentioned, there seems to be no way to make axios work with proxies correctly without using some additional 3rd party tools.
I will try to host the app repository on the same captain instance.

**Comment by githubsaturn** [comment]
Did you manage to get it working?

Just realized that, if the issue with proxy is specific to axios library, you can simply deploy a one click app (NGINX PROXY) and set upstream to be `https://oneclickapps.caprover.com`

Then, add `http://srv-captain-nginx-proxy-app-name` as your custom 3rd party repo:

![image](https://user-images.githubusercontent.com/10582082/110060092-5bb00b00-7d33-11eb-9bed-ab64013e2f29.png)

**Comment by patternoia** [comment]
> Did you manage to get it working?

Yes, setting up a repository with a simple node.js server worked in the end. The app images would not load, however, since their url resolve to something like `http://srv-captain--app-rep:8080/v4/logos/ackee.png` which is obviously not reacheable from outside of server. This ruins the user experience.


> Just realized that, if the issue with proxy is specific to axios library, you can simply deploy a one click app (NGINX PROXY) and set upstream to be `https://oneclickapps.caprover.com`
> 
> Then, add `http://srv-captain-nginx-proxy-app-name` as your custom 3rd party repo:

This is a nice suggestion. However, the nginx tries to connect to the repository by ip which fails. Any hints?
```
[error] 12#12: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.1.5, server: _, request: "GET /v4/list HTTP/1.1", upstream: "https://185.199.109.153:443/v4/list", host: "srv-captain--oneclick-proxy"

[warn] 12#12: *1 upstream server temporarily disabled while connecting to upstream, client: 10.0.1.5, server: _, request: "GET /v4/list HTTP/1.1", upstream: "https://185.199.109.153:443/v4/list", host: "srv-captain--oneclick-proxy"

10.0.1.5 - "GET /v4/list HTTP/1.1" 502 158 "-" "axios/0.21.1" "-"
```

**Comment by githubsaturn** [comment]
Regarding your first solution:
Instead of using `http://srv-captain--app-rep:8080`, you can try using `http://app-rep.your.domain` - just make sure you set container http port to 8080 in app's settings. 

Regarding the second solution:
I don't have much context on how your proxy works. But I tried it on an instance without proxy and it works just fine. Note that if you use `srv-captain--appname` for this solution, you'd have the same image issue.
