### ISSUE TITLE
[Deployment Issue] How-to avoid docker cache when pulling base image

### ISSUE THREAD

**Issue by PatBriPerso** [caprover/caprover#1075]
**What is the problem?**
When building the Docker image, the latest base image version is not pulled. 
Base image is the one on top of my Dockerfile like `FROM mysql:latest`.

I use a CI (Jenkins) to build my Docker image and push it to my private Docker hub account.
So, after each commit, my CI push the image and tag it `dev-latest`
Then I try to update the CapRover app which use a very simple Dockerfile like this:
```
FROM myaccount/myapp:dev-latest
```
But the docker build command does not pull the last image with this tag (dev-latest), it uses the one already in the Docker cache.

I read [in the Docker docs](https://docs.docker.com/engine/reference/commandline/build/#options) that we can add the option `--pull` to "Always attempt to pull a newer version of the image".

Is there a mean to add this option when CapRover build the image?

Thanks in advance for your help.
And a big thanks to have created and shared CapRover, great app!

**If applicable, content of `captain-definition` file:**
My captain-definition file:
```JSON
{
  "schemaVersion": 2,
  "dockerfilePath": "./myapp.Dockerfile"
}
```
My Dockerfile (myapp.Dockerfile):
```
FROM myaccount/myapp:dev-latest
```

**Comment by githubsaturn** [comment]
It's generally not a good idea to override a Docker tag, like `dev-latest`. It creates problems like the one you're experiencing. The better practice is to tag the image with a unique tag, like your commit sha for example.

If you really insist on having this approach, you can define the sha of your docker image and instead of using 
```
FROM myaccount/myapp:dev-latest
```
use
```
FROM myaccount/myapp@sha256:sha_digest_here
```

Another meta point here is that you shouldn't use this hacky way of a single Dockerfile line, CapRover deploy supports deploying an image name directly. So you should do something like this:

```
caprover deploy -i myaccount/myapp@sha256:sha_digest_here
```

See here for an example:
https://caprover.com/docs/ci-cd-integration.html#9--gitlab-ci-file

**Comment by PatBriPerso** [comment]
Thanks for your quick answer and your advices.

I'll probably use the `caprover deploy` command based on the CI/CD integration in the documentation.
Thanks again for this great product.
