### ISSUE TITLE
Listen for Webhooks other than Github

### ISSUE THREAD

**Issue by designermonkey** [caprover/caprover#1082]
It would be really useful to be able to listen to webhooks from systems like Strapi CMS which would allow static site rebuilds based on content changes in the CMS. It wouldn't even really matter about the content of the webhook payload (like new entry data) so long as it simply triggered a rebuild.

**Comment by githubsaturn** [comment]
You should be able to do this. All you need to do is to set up your git repository source and anytime the webhook is invoked with a POST request (regardless of the content of payload), a new build will be triggered.

![image](https://user-images.githubusercontent.com/10582082/113867974-2dcc4500-977d-11eb-97a2-ef8d49f45eec.png)

**Comment by designermonkey** [comment]
But Strapi CMS is not a git repository.

**Comment by githubsaturn** [comment]
I am a bit confused. Is "Strapi CMS" also your website? Or is it just the data provider?

I am assuming your website code is different, no? If not, can you please provide an example?

**Comment by designermonkey** [comment]
It's a data provider: https://strapi.io/

The website would be a normal dockerised frontend.

**Comment by githubsaturn** [comment]
So, it should work just fine. 

- Enter the git information for your frontend app and generate the webhook
- Enter the webhook in your Strapi workflow, such that every time the data changes, Strapi calls that webhook (assuming Strapi has this functionality)
- As soon as CapRover receives the webhook, it triggers the build process. It pulls the latest git repo, even if it's not changed since the last time, rebuilds the content using the latest data and deploys it.

**Comment by designermonkey** [comment]
Thanks for the details. Are there any specific headers or body payload that needs to be sent, or does Caprover just respond to anything sent to that webhook?

**Comment by githubsaturn** [comment]
Any POST request to that webhook should be enough to trigger a build.

**Comment by designermonkey** [comment]
Thank you very much for your help :)
