### ISSUE TITLE
Caprover Nginx and SSL via Docker Compose

### ISSUE THREAD

**Issue by miguelurtado** [caprover/caprover#1132]
Is it possible to deploy via docker compose using CapRover Nginx load balance and CapRover SSL? If so, would anyone have an example?

**Comment by maietta** [comment]
I believe it's possible simply because it's my understanding that Caprover is an app deployment system, whatever it does you can do with native Docker tools. Sadly, I don't have an example of this. Sorry.

**Comment by githubsaturn** [comment]
Two ways:

**First method**
Use one click app as a proxy to deploy docker compose file. Read about it [here](https://caprover.com/docs/docker-compose.html#what-is-docker-compose)

It has its own downsides. Most importantly, only few properties in Docker Compose are consumed by CapRover. There are many properties that are ignored by CapRover such as networks, host, and etc. If you app relies on that, this deployment method does't work.


**Second method**
Use Docker compose to deploy your app, but instead of exposing the port, attach your service to `captain-overlay-network` and deploy an NGINX Proxy one click app and have it connect to that service.
