### ISSUE TITLE
GitHub cached in the build time

### ISSUE THREAD

**Issue by alexander-potemkin** [caprover/caprover#1135]
What is the problem?

'Force Build' get cached Git source code, leading to the deployment of the previous version.

Steps to reproduce the problem:
1. Make code changes, click 'Force Build' button
2. Make another code change, click 'Force Build'
3. Note that the git hash for the last two builds is exactly the same.

To fix: `docker builder prune --all` or invalidate the Docker's cache every time inside the Dockerfile, but that means a long time of build every time it's happening.

I also believe that automatic deployment (via Webhook) doesn't cause that trouble.

Latest CapRover 1.9.0, installed on a various 18.04 Ubuntu machines.

**Comment by githubsaturn** [comment]
> Make code changes, click 'Force Build' button
Make another code change, click 'Force Build'

Are you sure you're pushing your code between the first, and second step? your git repo shouldn't be cached at all.

**Comment by alexander-potemkin** [comment]
Triple checked that. Thanks for the git hash I was able to realize, that with 'Force Build' it was building the same git hash, which is 5 days old (and there are others).

I also could not see this coming, an accident server reboot lead me to understand that it's something about the cache and then I found it's about CapRover / Docker cache of the git managed source code.

God know how and why, but that was quite a pain for me and the developer and we currently invalidating Docker cache by the advice from you earlier (wget google.com...), but it leads to a very long build time and doesn't feel right anyway.

Do you have any clue how or what could go wrong here?

**Comment by githubsaturn** [comment]
Force Build literally makes the same call as the webhook. So it's weird that webhook is not exhibiting any issues. Can you reproduce this issue easily? I've tried it multiple times and it seems to work fine for me.

- Start a new public repo on github
- Initialize it with a simple Dockerfile containing nothing but `FROM nginx:alpine`
- Add `test` and `test` as username and password (it's a public repo, so it works) and also add the github URL to the deployment tab and save
- Click on Force build and make sure it works
- Update the Dockerfile on Github and just add a dummy line `## testing` 
- Click on Force build, does it use the latest commit?

**Comment by alexander-potemkin** [comment]
I can not, unfortunately. And after two cache reset it didn’t re-occure. I guess I shall close the issue with a hope that it will be of help for future someone, giving a work-around to apply.

Thank you for your quick reaction and support - I’m sorry I can’t reproduce it =(

**Comment by githubsaturn** [comment]
Thank you for the update! But what do you mean by cache reset? What cache did you have to reset and how?

**Comment by alexander-potemkin** [comment]
Apologies for the delay: I did `docker builder prune --all` - that cleans up Docker cache, including a build cache; applied couple of times with your fix you offered on the issues earlier (like `wget http://google.com/` or something like that) - that seems to help - it's a production server, with not that much of the updates, so I can't tell for sure - we are now verifying git hash at the github and on caprover after every build, to make sure we are on the safe side (thanks for showing git hash on the GUI!)

**Comment by MeXaaR** [comment]
I think I have the same problem for a mont or so. I have a Strapi instance wich is pulled from github. I updated strapi to 3.6.5, pushed the code and every deploy is still in 3.6.1. Event if I use caprover CLI, it does not update my instance. 
The build is made but I think it is made on the cache and it doesn't use the new code....

@alexander-potemkin  you use `docker builder prune --all` on you server terminal and it solved the problem ? I didn't check the github hash but I think it is the same problem

**Comment by alexander-potemkin** [comment]
@MeXaaR , yep - just execute it (with `sudo` if required) on the host server and force the build.
Git hash can be seen in the builds section on CapRover and on commits section of GitHub.

By the way, that could be a docker / swarm issue actually…

**Comment by MeXaaR** [comment]
yes, so, i tried that and it didn't change anything. 
with the prune command, I have `Total reclaimed space: 0B` so it didn't remove anything
The github hash is the good one, it pull correctly the code. it's just build with the cache so with the old code. weird. I will try with docker issues

**Comment by githubsaturn** [comment]
@MeXaaR a few questions:
- can you check the image hash to see if it's changing? Run `docker images` 
- Also, what method of deployment you use? Are you using `caprover deploy` or using a git webhood?

**Comment by MeXaaR** [comment]
the IMAGE ID is not the same

I tried to deploy with git webhook and `caprover deploy` ad it does the same

the first step of the build are using cache, and, I think, same code base, then when I have the yarn build, it builds correctly, but not with the new code base, the cached one

**Comment by githubsaturn** [comment]
Have you confirmed this? You can view the image layers with `docker image inspect` 

The reason I am asking is that it's weird that it uses cached layer for a COPY operation and then for a RUN operation it invalidates the cache. It should be the other way around.

**Comment by MeXaaR** [comment]
So, I ran `docker image inspect` on the latest build and change the readme file of the project and pushed it to github. the webhook worked and triggered a new build. this was the output

---------------------------
Step 1/10 : FROM strapi/base

---> 88f34f8a4fbd
Step 2/10 : WORKDIR /srv/app/

---> Using cache **<-- is this normal ? it should not use cache to copy package.json and take it from the new code base, right ?**
---> 99deb1957e61
Step 3/10 : COPY ./package.json ./

---> Using cache
---> 907abc48a145
Step 4/10 : COPY ./yarn.lock ./

---> Using cache
---> 17825be533c1
Step 5/10 : RUN yarn install

---> Using cache
---> 06f07eb97896
Step 6/10 : COPY . .

---> ab3519c433ad
Step 7/10 : ENV NODE_ENV production

---> Running in 2d337ac9f182
Removing intermediate container 2d337ac9f182
---> 69067aa0355e
Step 8/10 : RUN yarn build --clean

---> Running in 6126628bccb8
yarn run v1.22.5
$ strapi build --clean
Building your admin UI with production configuration ...
ℹ Compiling Webpack
✔ Webpack: Compiled successfully in 1.63m
Done in 100.67s.
Removing intermediate container 6126628bccb8
---> f1c370c1620e
Step 9/10 : EXPOSE 80

---> Running in 2feda4a1327f
Removing intermediate container 2feda4a1327f
---> 27a65108d55b
Step 10/10 : CMD ["yarn", "start"]

---> Running in b69b1f3077cd
Removing intermediate container b69b1f3077cd
---> 7e2f8d7954d4
[Warning] One or more build-args [NODE_ENV] were not consumed
Successfully built 7e2f8d7954d4
Successfully tagged img-captain-********:latest
Build has finished successfully!

---------------------------

So, as expected, it didn't update the strapi version (wich is in the package.json), or any others changes I made in the code, and started the project with the same old code base. So i inspected the layers again and this is the output of the 2 images layers

Image 34:
            "Layers": [
                "sha256:1fb0a31fe7c2950eaf79588bd3db9417a4c5ce16870d48a6b8a3611551919d11",
                "sha256:74825a980b6d98e42ce29b2fd82efe4254f59e12058ccf6d864b6b6eef226e1d",
                "sha256:aa817488a0ddbb3192c5dafbc940df5fe307db415984827c1363e04d5eb6a634",
                "sha256:edfb8ee7c346a368e8416ba57ec367b73aa2f883113e991535bebe786dbbda6a",
                "sha256:07700abd910e24084faf4f755fe7d2f569ed58dfbbce497862f77f868e28e674",
                "sha256:fdba6a5d9dd726e79b208f70abb0bf7906e9a71e0d92bc8f2f132950f29e036a",
                "sha256:4f92f3f276651448aecffc6ead70f09855dac54d2417fac1d427a546590abad5",
                "sha256:cbff660b7bdc35e75aca673ea4e4878d08ffdd80478613fb52ee606750151db0",
                "sha256:76269cc2f2b553311ae3c0e9bae73d1b444c71bed210917ce3e8968b417dade4",
                "sha256:c04ee85cefbcffbf42ae77474c98d3eb30d187ab4c712e94ed729be0ffe01a76",
                "sha256:843f90afcccde261b216a707c0d2a219372e89db227372f46421f40456f50efa",
                "sha256:e2447e31fce61c365982033de8cca0f6c882a0569a9d90c51e9d2b5dacee79b6",
                "sha256:fae04e3675d97414c72134d339536c2583b5c4072845c6ef502725f59aefb13d",
                "sha256:0df64d562bce9e9760f5800a23d90e09f21808aedb488cbd467da2463cc3cc11",
                "sha256:e89827871fc56d5f3724c25962ee4d8520aa869750f3293b5bc988178a247f6d"
            ]

image 35: 
            "Layers": [
                "sha256:1fb0a31fe7c2950eaf79588bd3db9417a4c5ce16870d48a6b8a3611551919d11",
                "sha256:74825a980b6d98e42ce29b2fd82efe4254f59e12058ccf6d864b6b6eef226e1d",
                "sha256:aa817488a0ddbb3192c5dafbc940df5fe307db415984827c1363e04d5eb6a634",
                "sha256:edfb8ee7c346a368e8416ba57ec367b73aa2f883113e991535bebe786dbbda6a",
                "sha256:07700abd910e24084faf4f755fe7d2f569ed58dfbbce497862f77f868e28e674",
                "sha256:fdba6a5d9dd726e79b208f70abb0bf7906e9a71e0d92bc8f2f132950f29e036a",
                "sha256:4f92f3f276651448aecffc6ead70f09855dac54d2417fac1d427a546590abad5",
                "sha256:cbff660b7bdc35e75aca673ea4e4878d08ffdd80478613fb52ee606750151db0",
                "sha256:76269cc2f2b553311ae3c0e9bae73d1b444c71bed210917ce3e8968b417dade4",
                "sha256:c04ee85cefbcffbf42ae77474c98d3eb30d187ab4c712e94ed729be0ffe01a76",
                "sha256:843f90afcccde261b216a707c0d2a219372e89db227372f46421f40456f50efa",
                "sha256:e2447e31fce61c365982033de8cca0f6c882a0569a9d90c51e9d2b5dacee79b6",
                "sha256:fae04e3675d97414c72134d339536c2583b5c4072845c6ef502725f59aefb13d",
                "sha256:2f369f8bee067771c1ce41275553eee8ecb8856aa72d1e62ee728a81afc64c25",
                "sha256:5468964ce010ee30ac9ffa7e8848008b767316b8631617f4b2f3caf49016e004"
            ]

As you can see, only the last 2 layers are different. So the build and the start. But they are based on the same cached layers. 
I did that with an update to the readme but, I am pretty sure, it does the same with an update to the package.json file because I changed it many times without any differences. I event tried differents version of strapi and strapi packages.

**Comment by githubsaturn** [comment]
Yes, it's clearly says it's using the cached layer here:
```
---> Using cache
---> 06f07eb97896
Step 6/10 : COPY . .
```

I am totally lost as to what's going on here. The fact that is so easily reproducible on your end is very weird.

1) What if instead of a change in readme, change your Docker file, maybe add a simple line right after FROM: `RUN echo "test"`

2) Does it only happen with Strapi? What if you create a new app, perhaps something as simple as [sample PHP application](https://github.com/caprover/caprover/blob/master/captain-sample-apps/php.tar).

**Comment by MeXaaR** [comment]
> I am totally lost as to what's going on here. 

You and me both, and wait for it, it does get better

> What if instead of a change in readme, change your Docker file, maybe add a simple line right after FROM: RUN echo "test"

I didn't think about that solution and, even if it doesn't make sense I have to do that, it does make sense that it works. and it does. The cache is not used anymore and the pakages are correctly pulled. 
Everything works fine but.... **The app starting is not the the one with the new code base but the old one...** It makes even less sense

> Does it only happen with Strapi?

so far, it only happened with this app. I have other strapi apps on other instances and nothing like this ever happened. I tried to make a new strapi app with the same code (on the same caprover instance) with another name and it does the same. with a fresh empty database, and same.

I just tried ith a simple JS app I have on github, made a change and everything went normally. I can see the changes

**Comment by MeXaaR** [comment]
I removed the .git folder and created a new git repo in my project. I used the CLI to deploy the app and the build still used the cache -_-

**Comment by githubsaturn** [comment]
>  I have other strapi apps on other instances and nothing like this ever happened. I tried to make a new strapi app with the same code (on the same caprover instance) with another name and it does the same. with a fresh empty database, and same

To me, it looks like something specific to "this" Strapi... whatever magic it has... I am not too familiar with how Strapi works. But it could be related to how it works. Judging from their [sample Docker compose file](https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/installation/docker.html#creating-a-strapi-project), it looks like they have a persistent volume. This could explain things... If your app is stored on the server in a persistent directory, then you can't change it by deploying a new image.

**Comment by MeXaaR** [comment]
That's why I started a new app, with the same code but with a new persistent volume and it did the same. SOrry I wasn't clear when I said empty DB, I meant empty volume ;)
Alright, I am lost, I will try crazy things with no sense at all (to my brain right now) and see if one of them works. I'll let you know :)

**Comment by githubsaturn** [comment]
Try completely removing the persistent volume form your app config and redeploy to see if it makes any difference.

**Comment by MeXaaR** [comment]
It did yes. the new code base has been deployed. And then I used the persistent volume from before and it came back to the previous version. You are right. I ha ve a leeeeaaaad, thanks :)

Now I jsute have to figure out how to keep the data i want and remove the app stored in the volume. It was strapi related sorry

**Comment by wolfskaempf** [comment]
I had a very similar, if not the same problem, which was caused by my persistent folder inside the container being the same folder as the main app folder, where the copy command puts all the project files. I moved all the files that require persistence into a separate subfolder and then reconfigured the in-container path of the volume to that new location. This fixed the issue of the app not updating after a deploy of a new version.

**Comment by alexander-potemkin** [comment]
@wolfskaempf , thanks, not sure I follow - any chance you can share some examples / specifics?
And in my case, we didn’t change the folders structure and seems never had this issue re-appeared.

**Comment by wolfskaempf** [comment]
My app lives inside the container at `/usr/src/app`. I used to have the following configuration for a persistent volume.

![image](https://user-images.githubusercontent.com/233473/154281385-d2658142-2c19-47b2-9e2c-dfefa37777bd.png)

What would happen is, that during the docker build process, the new versions of my files were copied to `/usr/src/app`, however after launching the container with the new image and the above persistent volume settings, the content of `/usr/src/app` would be overridden by the volume contents (which were the old files still). Therefore I thought there was a problem with the image build process and caching, but it turns out it was the volume all along.

To solve the problem, I changed my app so that persistent files would live in a subfolder at `/usr/src/app/persistent` and then changed my apps caprover configuration to the following.

![image](https://user-images.githubusercontent.com/233473/154282595-5ccbe7b5-3f96-454a-a343-69dc42340890.png)

After I did that everything worked already, but to clean up I went into the container with `docker exec -i -t [container-id] sh` and deleted the app-logic files that don't need persistence from `/usr/src/app/persistent`.

If you want to take a look at the project files, you can find them in [this repo](https://github.com/wolfskaempf/tops).

I hope this could clear things up and maybe it will even help you diagnose or fix the issue you are having. If not feel free to ask more specific questions.

**Comment by alexander-potemkin** [comment]
Thanks a lot! It was not my case for sure - my app is stateless, but I hope this would save someone else’s time here!
