### ISSUE TITLE
[Question] setting MTU

### ISSUE THREAD

**Issue by glor** [caprover/caprover#1149]
I am in a network which throws away packages that are to large (mtu = 1450). I think there was an update which increased this inside docker containers. I followed the various instruction that configure docker to use a lower mtu (I have set the value in /etc/docker/daemon.json to 1450). I also tried restarting docker, the vm, caprover itself. But it seems not to affect all networks and I didn't succeed in changing the mtu for eth2:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
137: eth2@if138: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:12:00:06 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet 172.18.0.6/16 brd 172.18.255.255 scope global eth2
       valid_lft forever preferred_lft forever
139: eth0@if140: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default
    link/ether 02:42:0a:00:01:2b brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.0.1.43/24 brd 10.0.1.255 scope global eth0
       valid_lft forever preferred_lft forever
149: eth4@if150: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default
    link/ether 02:42:0a:00:00:03 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet 10.0.0.3/24 brd 10.0.0.255 scope global eth4
       valid_lft forever preferred_lft forever
```

How can I do that? Is this affected by caprover or is it docker?

**Comment by githubsaturn** [comment]
It's done by Docker. CapRover doesn't override any MTU values, and all default values are used.

The problem is that upon installation, CapRover creates an ingress network. and once that network is created, I think, you can't change the MTU value of it. You can only set the overlay network's MTU at the creation time: https://docs.docker.com/engine/reference/commandline/network_create/#network-ingress-mode

Potential solutions:
1) Override Docker default:
-  [uninstall CapRover](https://caprover.com/docs/troubleshooting.html#how-to-stop-and-remove-captain) if it's installed
- Make sure the overlay network is deleted too: `docker network rm captain-overlay-network`
- Make sure you update the default MTU in `/etc/docker/daemon.json`,
- Reinstall CapRover

2)
If solution 1 didn't work, try this one [it may/may not work]:
- Install CapRover as you usually do
- Wait until the installation process is fully done (run `docker service logs captain-captain --follow` to make sure it's done)
- After the system settles, try deleting the overlay network: `docker network rm captain-overlay-network`
- Now manually create a overlay network with the name of `captain-overlay-network` and [custom MTU](https://docs.docker.com/engine/reference/commandline/network_create/#network-ingress-mode)

**Comment by glor** [comment]
Thanks for the quick reply. Unfortunately 1. does not work. The network still gets an MTU of 1500, completely ignoring my docker settings.

Solution 2 fails ` rpc error: code = FailedPrecondition desc = network 6885hv85baecoewu4gyvod3xe is in use by service 3355hfp8wteccnzv0uwl4r1p1`. As far as I have understood, removing the services uninstalls caprover, am I right?

Got any further ideas?

**Comment by githubsaturn** [comment]
> As far as I have understood, removing the services uninstalls caprover, am I right?

That's correct. 

I can't think of any other solutions. But solution 1 not working is a bit weird because CapRover definitely doesn't override any MTU values, it just uses Docker's default configs.
