### ISSUE TITLE
[Question] Unselect persistent data

### ISSUE THREAD

**Issue by jersomoreira** [caprover/caprover#1150]
Please clearly state your question:

I created an app and marked it as persistent data, but it is not persistent data.
How to unmark app as persistent data in apps listing in Caprover?

![Captura de Tela 2021-07-20 às 18 13 55](https://user-images.githubusercontent.com/10035279/126402468-9034b7d5-a6cd-4ba4-abe7-f7af6f218329.png)

![Captura de Tela 2021-07-20 às 18 14 41](https://user-images.githubusercontent.com/10035279/126402472-f58ae828-962b-4b2a-b50d-803cf8bcd257.png)

**Comment by githubsaturn** [comment]
Once an app is created, it cannot change its persistency state. It's because once the app is marked as "persistent", it is locked down to a specific node. You'll have to remove the app and recreate it if you want it to not support persistency.

Having said that, the only downside of being marked as persistent is that the app always stays on the same node. If you only have one single node, this checkbox doesn't do anything. Even if you have more than one node, all it does is that it ensures your app always runs on the same node and it doesn't jump around nodes as it dies and gets recreated.
