### ISSUE TITLE
Error while deploying Go application

### ISSUE THREAD

**Issue by Fabian9799** [caprover/caprover#1160]
What is the problem?
I am trying to install [https://github.com/gempir/justlog](https://github.com/gempir/justlog) on caprover but every time i try to install it i get the following error:
```
Deploy failed!
Error: {"code":1,"message":"The command '/bin/sh -c go build && ./justlog' returned a non-zero code: 1"}
The command '/bin/sh -c go build && ./justlog' returned a non-zero code: 1
```
The same thing also happens when i download the example Go application from [https://github.com/caprover/caprover/tree/master/captain-sample-apps](https://github.com/caprover/caprover/tree/master/captain-sample-apps)

 `captain-definition` file:

```json
{
  "schemaVersion": 2,
  "dockerfileLines": [
    "FROM golang:latest ",
    "RUN go build && ./justlog"
    ]
}
```

Steps to reproduce the problem:
Download any go app (i tested it with the one mentioned above and the example go app) and try to upload it to caprover
While building the error appears

Specs:
Caprover: 1.9.0
Ram: 64GB
OS: Ubuntu 20.04.2

**Comment by githubsaturn** [comment]
Regarding justlog: it's not CapRover related.Your docker file for justlog is surely wrong. You'll have to first make sire it builds with docker then bring CapRover to the mix. 


But sample applications are tested. It's weird that it doesn't run for you. Are you modifying the sample application? Or deploying it as is?

**Comment by githubsaturn** [comment]
I looked into the sample go, and it turned out it was broken because it was using the "latest" version of Go:
```
FROM golang:latest
```

Golang has a breaking change in 1.16 that makes some codes incompatible. I fixed the sample app and you can download it from here: https://github.com/caprover/caprover/raw/master/captain-sample-apps/go-sample.tar

With regards to "justlog" you'll have to use their own Dockerfile and make sure it's compatible. First use it with Docker (without CapRover) to make sure it works, then Deploy it to CapRover.

PS: looks like they have their own Dockerfile: https://github.com/gempir/justlog/blob/master/Dockerfile
