### ISSUE TITLE
`Certificate has expired` when running `caprover deploy`

### ISSUE THREAD

**Issue by ghost** [caprover/caprover#1231]
- What is the problem?
When trying to execute `caprover deploy` I get an error that certificates have expired. I already updated to Caprover 1.10.1 which solved some certificated related issues. I have restarted both my server and Caprover. I have tried to `caprover logout` and `caprover login` without success.

```
Something bad happened: cannot save XXX at YYY.
Error: certificate has expired
```

- If applicable, content of `captain-definition` file:
N/A

- Steps to reproduce the problem:
Run `caprover deploy`

- Output of the following command on your server:
```
uname -a && lsb_release -a && free -h
```
```
Linux ip-172-26-11-254 5.4.0-1058-aws #61~18.04.3-Ubuntu SMP Fri Oct 1 14:04:01 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
              total        used        free      shared  buff/cache   available
Mem:           1.9G        696M        431M        7.7M        857M        1.1G
Swap:            0B          0B          0B
```

**Comment by ylluminate** [comment]
@githubsaturn this one bit me as well pretty hard in terms of time sink. I initially thought it was a CapRover server problem due to the error, but finally found this and was able to work through it by upgrading node on Ubuntu 18.04 to a non-distribution release (via nodesource.com v17 (v18 is broken on Ubuntu 18.04). 

It would be helpful to update the error message. 

@githubsaturn I don't think this is related, but perhaps it is something close enough to consider related since it has some approximate relationship with certificate issues. While on the server I decided to make it more convenient to run some `caprover` operations on the server by installing `npm` + `caprover`. This is on Ubuntu 18.04 still.

After doing this and attempting to login to the server (in theory localhost, but I gave it the fqdn), I got the following message:
* From: 
  ```
  Error: certificate has expired`
  ```
* To: 
  ```
  Error: certificate has expired. HINT: Try upgrading your NodeJS and NPM version for your workstation. This is NOT a server-side error!
  ```

**Comment by githubsaturn** [comment]
Unfortunately these errors are thrown by the underlying HTTP client, not CapRover itself. What's the minimum version of NodeJS and NPM to fix this issue? We can bump the min required version to that.

**Comment by ylluminate** [comment]
That's a good question. I'm not sure of the min version actually. I couldn't use node 18 and had to back down to v17 due to the above situation... So I guess v17 might be sane since it's still workable on Ubuntu 18.04. Is there another way of which you're aware to test this situation more thoroughly?

**Comment by githubsaturn** [comment]
That's weird that a downgrade was needed in this case.

**Comment by ylluminate** [comment]
See: https://github.com/nodesource/distributions/issues/1390

**Comment by githubsaturn** [comment]
Wait, I am confused. Ubuntu 18 is your local machine (laptop) or your server (CapRover machine)?

**Comment by ylluminate** [comment]
Well, both actually. I have an 18.04 workstation that I do have sitting beside me to emulate a couple of the servers I still maintain, but I also use 18.04 on the server still as well. I tried this on both locations to see what was going on since I *INITIALLY* had believed it was a server problem... It was a very confusing error message.

**Comment by githubsaturn** [comment]
You can safely upgrade your local machine to Ubuntu 20+. Even for CapRover server, there are just a few issues that might happen with multi-node setup. Even those seem be not happening as much lately.

**Comment by ylluminate** [comment]
Interesting, I'm glad to hear that. I thought we were still needing to use 18.04. Thanks!
