### ISSUE TITLE
Avoiding "Request Entity Too Large" error

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#1276]
I started to reply to [this post](https://github.com/caprover/caprover/issues/1233#issuecomment-983851031) but realised that I was straying off the original topic and rather hijacking the thread, because what I'm encountering is really a different issue.

Hi @maietta... thanks for the guidance.  I've not used GitHub Actions before, so I've learned a bit playing around with this feature.  It looks like using the App Token rather than Webhook would be an improvement (mainly that it would survive a backup/restore), but for me a big problem remains... and that problem is the reason why I was using the Webhook deploy method in the first place.

I'm deploying from a repo that has some large data files in it.  So if I try to clone the repo locally and then just deploy to CapRover in the normal way, I get a "Request Entity Too Large" error.  I know that I could [change my nginx config](https://github.com/caprover/caprover/issues/168), but whilst I like customising stuff, I'd really rather leave core stuff like nginx alone (and leave it to those who know better than me).

So with the App Token method you describe, it seems to work to the extent that it is packaging up the tarball and deploying to the CapRover server I specify in the secret, but when it comes to deploying to CapRover, the same "Request Entity Too Large" occurs... looks like it is working in a similar way and packaging up a tarball that is too large to handle.

For some reason, using the Webhook approach doesn't lead to this "Request Entity Too Large" error... when I trigger the webhook on GitHub, I can see the deploy steps happening in the logs on the CapRover console, and the deployment continues to completion without the "Request Entity Too Large" error.  

@githubsaturn why is that... with Webhook it doesn't need to tar everything up into a single (too large) tarball?

I thought that the Webhook is just a mechanism to notify CapRover of a change to the repo (and to signal that a new deploy is required).  Surely there could be a way to trigger this locally (e.g. via `caprover deploy`) without any Webhook?  In both cases, CapRover still needs to fetch the relevant files from GitHub and if it can work (without "Request Entity Too Large" error) with a Webhook trigger it could also work with a local trigger?

**Comment by maietta** [comment]
Hi @drmrbrewer. Thanks for checking out the method I use for deployments. That's an interesting error.

From your description and as I understand it, it dos appear that this in fact is coming from the Caprover side of things, more specifically, the Nginx webserver.

The deployment strategy I discussed uses the caprover CLI tool under the hood. Without browsing the source code, I would guess that it's uploading to an API endpoint of Caprover and not to the dashboard interface.

Looking at the /etc/nginx/conf.d/captain-root.conf config, (Also available via the Caprover UI's Settings secton), I can see where one might need to adjust or set the client\_max\_body\_size for the API part of the configuration.

I'm hesitant on testing this out on my production server though!

As I understand it, the App Token method is still relatively new and thus not many people using it with CI/CD yet so to you I say congratulations on finding a possible bug/issue!

I'll craft a bug report for this and tag you along with it. I am curious, do you have Large file storage enabled on your Github?

**Comment by maietta** [comment]
I want to provide some basic information about the differences between Method 1 and Method 3 in Caprover for deployments:

In Method 3, Github will perform a POST to the webhook provided by Caprover for your app. Caprover will then make a request for your Github Repo, then perform the actions provided via the caprover-definition file.

However, in Method 1, Github will instead run the workflow files, performing two tasks as provided from my boilerplate example. The first is as you saw, the use of tar to bundle up select files and directories into a deploy.tar file.

The difference is in fact that in Method 1 we're uploading the newly created deploy.tar file to Caprover's API, which is served using Nginx web server.

Because Method 3 using Webhooks is requesting the file, i.e, downloading, it's not hitting any kind of data limit. Method 1 though, well, the webserver is going to complain when files are too large. This is a adjustable safety feature of Nginx to prevent network abuse.

Increasing the client\_max\_body\_size _may_ lead to network abuse so to prevent that, one trick may be to limit what IP's or IP netblocks can access your Caprover API which is well beyond the scope of this issue. This leads me to believe you were better off with the Method 3 option for the moment. :(

Sorry for the troubles, @drmrbrewer. We'll still want to try and resolve your original issue though. Perhaps document this issue as something to be aware of.

**Comment by drmrbrewer** [comment]
So with Method 3 (webhook) the files are fetched from GitHub individually rather than in a bulk tarball?  In the repo concerned, there isn't one massive data file causing this issue... there is just a bunch of medium-sized files (e.g. 10MB) that together add up to a lot.  Isn't there any way to replicate this approach (where CapRover fetches individual files from GitHub, not a tarball) using something other than webhooks... e.g. via the App Token mechanism?  I understand that GitHub could itself perform the build, but ideally it's better IMHO for CapRover to do the building, based on files from GitHub.

**Comment by maietta** [comment]
I believe with Method 3 (webhook), Caprover performs an actual "git clone" command to fetch your files. (Someone correct me if I am wrong, plz).

The App Token method only offers an alternative to distributing your Caprover password for deploying apps. It's implied that you must use your own tooling when using Method 1.

I propose the following solution:

In your workflow file in Github, specify the minimal number of files required to start deploying your project (not including your main files for the application itself).

Craft a Dockerfile that will get sent to Caprover, along with your captain-definition. Have this deployment recipe perform a "git clone" for the full repository and then build accordingly.

In this way, you are asking Caprover to perform the download rather than Github pushing those big files. This lets you keep your App Token (Method 1) and avoid this error you ran into.

It's a workaround, but I don't see any reason why it couldn't work. If you need clarification, I'll do my best to help.

**Comment by drmrbrewer** [comment]
OK I understand the basis for this approach (though have yet to try it, or even know where to start).  

But I'm just wondering if there's any reason why this can't be built into CapRover?  Would be great just to supply a GitHub repo URL (it's a public repo so no authentication is required)... and then it would also be the case that "you are asking Caprover to perform the download rather than Github pushing those big files".  

It could just be a one-line `captain-definition` (or two including the version number):

    {
      "schemaVersion": 2,
      "repoUrl": "https://github.com/mygithub/my-great-repo.git"
    }

Of course, `my-great-repo` would itself have all the necessary files required by CapRover, i.e. a `captain-definition` and a `Dockerfile` (if required).  So the `repoUrl` is just a pointer to the actual build repo, it doesn't have the build files itself.

And even if the build repo is private, we can still use this approach by providing authentication info too.

**Comment by maietta** [comment]
Ha, I just edited my last post to include a link where someone wrote about how to solve fetching a private repository from a docker container. Two different solutions are offered: [https://medium.com/paperchain/fetching-private-github-repos-from-a-docker-container-273f25ec5a74.](https://medium.com/paperchain/fetching-private-github-repos-from-a-docker-container-273f25ec5a74.)

I didn't realize Caprover offered a repoUrl option. I've always used a Dockerfile or using dockerlines.

Interesting.

**Comment by githubsaturn** [comment]
> For some reason, using the Webhook approach doesn't lead to this "Request Entity Too Large" error... when I trigger the webhook on GitHub, I can see the deploy steps happening in the logs on the CapRover console, and the deployment continues to completion without the "Request Entity Too Large" error.
@githubsaturn why is that... with Webhook it doesn't need to tar everything up into a single (too large) tarball?

Webhooks work in a different way. When you push your code, Github sends a very small request to CapRover and says "hey, there is an update". At this point, CapRover internally runs a `git clone` and pulls the data. There is no HTTP call involved here. You can manually just call the webhook and it'll do that same thing. Webhook is just a trigger.

**Comment by drmrbrewer** [comment]
> At this point, CapRover internally runs a `git clone` and pulls the data. There is no HTTP call involved here. You can manually just call the webhook and it'll do that same thing. Webhook is just a trigger.

That's exactly as I thought.  So my suggestion/hope is that CapRover can have a deploy option that does exactly the same thing (i.e. `git clone` internally), but is triggered not by a webhook signal from GitHub but instead by a trigger from caprover CLI.

Like just specifying a `repoUrl` in the `captain-definition` (as per my suggestion above) to tell CapRover what to `git clone` internally.  Similar to the `imageName` option that [already exists](https://caprover.com/docs/captain-definition-file.html#use-image-name).

> The way to circumvent this is to build your image on a CI/CD server, and just use `caprover deploy --imageName` to tell CapRover to "pull" the image

Or (if you don't want to mess with pre-built images) a new command-line option for the repo url to use to build the image internally:

`caprover deploy --repoUrl "https://github.com/mygithub/my-great-repo.git"`

**Comment by githubsaturn** [comment]
Yes, that's should be possible. Feel free to open a feature request.

**Comment by drmrbrewer** [comment]
> Yes, that's should be possible. Feel free to open a feature request.

Great... [see here](https://github.com/caprover/caprover/issues/1279).

**Comment by maietta** [comment]
I would recommend if you MUST have large files in your repo, to switch to "Method 3" deployment strategy.
