### ISSUE TITLE
Question on Instance Count

### ISSUE THREAD

**Issue by thomascenni** [caprover/caprover#1278]
Hi,
I have an application consisting of Django and huey for task queuing. Basically I send emails with huey.
I needed to increment Instance Count from 1 to 2, and what happened is that emails are sent in duplicity.
I read on the [doc](https://caprover.com/docs/app-scaling-and-cluster.html#run-multiple-instances-of-app) that Captain automatically spreads the requests between different instances of your app, so in reality I should receive only 1 email from one of the 2 instances.
Am I correct ? I am missing something ?
Thanks @githubsaturn for your support.

**Comment by maietta** [comment]
It's up to your app to ensure that it only sends out email once despite running from multiple instances. I am not familiar with this application or how it operates but typically there will be a central database (or distributed) that will keep track of what emails were sent and which bounced, etc.

I know this isn't very helpful, but hey, my two cents is now yours to do as you wish with.

**Comment by thomascenni** [comment]
@maietta 
Hi, it's not clear to me. Imagine I have a web app which renders a page (index). If I request that page, I should get only one answer from one of the two instances, and see just one page...

**Comment by maietta** [comment]
Correct. You should always only get one answer no matter which server is serving the content if using multiple instances.

I re-read your original problem and now conclude that I answered incorrectly as I misunderstood your problem.

From what I now understand, there is no centralized or synchronized awareness of tasks tracked by this "huey" tool, leading to duplicity in emails sent. But still, I would think that you would only have once instance answering at any time.

Can you point me to this "huey" tasks program? I can't seem to find it via Google searches.

**Comment by maietta** [comment]
Okay, I think I have a better grasp here. 

After quickly scanning over the examples and readme, I see that it uses a database for task queuing.

I see that this system can use Redis, file-system, SQLite or in-memory. For your application you should only be using Redis it seems and have that Redis server referenced by all your instances.

Are you currently using Redis or one of the other 3 storage types?

**Comment by thomascenni** [comment]
Yes, I use Redis in a separate container, so both instances are pointing to the same Redis database.

**Comment by maietta** [comment]
Interesting! Now I am genuinely intrigued by your problem.

**Comment by thomascenni** [comment]
huey is managed by supervisor.

**Comment by maietta** [comment]
As in supervisord for Linux daemon management?

**Comment by thomascenni** [comment]
Yes, I run a prestart script with this command:
```
supervisord
echo '>> Supervisor daemon started. <<'
```

**Comment by githubsaturn** [comment]
Not all programs are designed to be distributed across multiple instance. Your email sender seems to be one of them. 

A simple example:
Assume that you have a redis queue that has all the email jobs:
```
[
  {to: me@gmail.com body: "hi"},
  {to: you@gmail.com body: "bye"}
]
```
If you have two instances of your email sender running, they both run at the same time, grab one instance from the queue, send the email and they both try to remove it from the queue after a successful send. Most likely one of them succeeds, and the other one fails on deletion since the record has already been removed from the queue. 


So to put it in a nutshell, applications must be designed for scalability if you want to run multiple instances of them. CapRover distributes the load, but that doesn't mean that it can change the inner workings of your application.

A good and simple example that just works out of the box is an image processor app. Assume that you have an app that doesn't use any database etc, it just receives a PNG file and it tells you whether it's a black and white, or color PNG. You can simply increase the instances of such app without worrying about breaking something. Each request will go to a random instance of this app and gets processed and returned.
