### ISSUE TITLE
Error 525 SSL handshake failed cloudflare caprover

### ISSUE THREAD

**Issue by Panhara28** [caprover/caprover#1345]
Is that problem with let's encrypt renewal ?

**Comment by githubsaturn** [comment]
Are you using their DNS service or using them as a proxy?

**Comment by Panhara28** [comment]
I am using that as a proxy

**Comment by Panhara28** [comment]
### Description
I setup caprover on private IP
`10.99.9.1 `
And then I point the private IP to cloudflare with 
A record as an example:
`A *.production => 10.99.9.1 (DNS Only) `
When I did that everything is working fine except enable https so I change the private IP to Public IP one 
`A *.production => 133.10.54.132` 
Now I can enable the https with let's encrypt 
After that I change it back to private IP because if I don't change it I can't access to **captain.production.example.com**
### Problem

The issue is when I visit my instance I mean my nextjs app with this url **admin.example.com** it return me back 525 error SSL handshake from cloudflare after I refresh the page the website is back to normal 

### The question

1. Is it any my configuration from my side is wrong ? **I also have firewall for my network**
2. Is that problem about cloudflare proxy ?
3. Any solution about this ?

Thank you for advance :)

**Comment by githubsaturn** [comment]
According to documentation, you should use A record. CapRover is designed with A records in mind, proxy services might work, but it's definitely not a fully supported method similar to A record. So you're using it at your own risk.

![image](https://user-images.githubusercontent.com/10582082/154996428-321fee61-b54d-45f8-81bb-40a3c64ff56f.png)



In general, "Error 525 SSL handshake failed" is not a CapRover error, it's a cloudflare specific error. 


Also, private IP is from your own network. Of course, when you use cloudflare as a proxy you need to allow Cloudflare to access your machine. You cannot expect cloudflare to access your private IP. That's why it's a private IP.

**Comment by Panhara28** [comment]
@githubsaturn thank you for your answer but any solution or I need to change proxy provider

**Comment by githubsaturn** [comment]
Two changes needed to resolve the issue:
1- Change the proxy mode to DNS mode
2- Use your public IP address

**Comment by Panhara28** [comment]
So I need to change like this

### Before Configuration 
A    admin   133.22.33.44 (Public IP)     proxy
A    *.production  10.99.9.1(Private IP) DNS only 

### Your solution
A    admin 133.22.33.44(Public IP) dns only
A    *.production  133.22.33.44(PublicIP) DNS only 

Is that right  @githubsaturn  ?

Thank you for your support ^^

**Comment by githubsaturn** [comment]
Yes!

**Comment by mxdpeep** [comment]
you cannot use caprover with cloudflare reverse proxy mode ON FYI, but it's
a bad mistake for security reasons 😕

Filip Oščádal
CEO mxd.cz

**Comment by Panhara28** [comment]
@mxdpeep so your solution is ?

**Comment by mxdpeep** [comment]
I don't use Caprover, but the only probable possible solution is set
another proxy and use that through Cloudflare, while limiting Caprover
origin to this proxy only.

*Filip Oščádal*
*https://mxd.cz <https://mxd.cz>*
