### ISSUE TITLE
[Question] Docker parameter

### ISSUE THREAD

**Issue by murratore** [caprover/caprover#1346]
Perhaps a really dumb question, but how do I add parameters to an app?

Example: I want to install Webtop https://docs.linuxserver.io/images/docker-webtop#linuxserver-webtop
This is the docker command:
```
docker run -d \
  --name=webtop \
  --security-opt seccomp=unconfined `#optional` \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -e SUBFOLDER=/ `#optional` \
  -e KEYBOARD=en-us-qwerty `#optional` \
  -p 3000:3000 \
  -v /path/to/data:/config \
  -v /var/run/docker.sock:/var/run/docker.sock `#optional` \
  --shm-size="1gb" `#optional` \
  --restart unless-stopped \
  lscr.io/linuxserver/webtop
```
The environment variables like TZ are clear. Also the image-name, volumes and port mapping.
But how things like "--shm-size", oder "--security-opt".

Thank you

**Comment by githubsaturn** [comment]
Passing parameters aren't supported because CapRover uses Docker service., not Docker containers. The exposed functionalities are different.

Some flags are available through service override: https://caprover.com/docs/service-update-override.html#schema

This is a complex process, if you are not familiar with Docker, I don't recommend using it.
