### ISSUE TITLE
[Question] Connect fail MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017

### ISSUE THREAD

**Issue by Trung229** [caprover/caprover#1358]
Hi everyone,

I am connecting my pc with mongoDB on ubuntu server,

Everything works fine on my machine, which means when I type `yarn start` my node app returns as DB-Connect,

But on the server, it keeps saying connect ECONNREFUSED 127.0.0.1:27017, I have researched for more than 4 hours but still no results

I have tried [all the ways](https://stackoverflow.com/questions/46523321/mongoerror-connect-econnrefused-127-0-0-127017) but none of them work

Hope anyone can help me,

this is my file env

```
MONGO_USERNAME = 'trungpham'
MONGO_PASSWORD = 'something'
MONGO_HOSTNAME = '127.0.0.1'
MONGO_PORT = '27017'
MONGO_DB = 'furniture'
``` 

this is my code

```
const url = `mongodb://${process.env.MONGO_USERNAME}:${process.env.MONGO_PASSWORD}@${process.env.MONGO_HOSTNAME}:${process.env.MONGO_PORT}/${process.env.MONGO_DB}?authSource=admin`;

mongoose.connect(url,{useNewUrlParser: true})
.then((res)=> console.log(">>>>>DB connected"))
.catch((err)=> console.error("Connect fail", err));
```
this is log on caprover
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/52306399/155840288-e6c4de03-00de-4cba-b428-ebc0185b9619.png">

Thanks

**Comment by Trung229** [comment]
Hi @maietta,

Thank you for your reply,

Im a newbie and I'm still not used to using the terminal to interact with the software,

So you can tell me detail about how can I do with `srv-captain`

**Comment by maietta** [comment]
No problem, @Trung229.

I don't know how your app was deployed and therefore know whether your MongoDB lives in the same container as your main application. Most one-click-apps I've seen follow best practices for containerizing applications, which is to say each part of the whole application lives in it's own container and the service is deployed as a stack. This allows for scaling up and down each part of your app as needed for traffic to your deployed services, if that application is designed with this in mind.

Assuming your app was deployed as a service stack, you should have a app in your Apps List referencing your MongoDB instance. Whatever that name is, you need to prefix with with srv-captain--. So if your app is "myappname", then it should look like "myappname-db" or "myappname-mongodb". Your final compiled name should look something like "srv-captain--myappname-db". 

It appears that you're app is referencing enviornment variables provided in the App Config area of Caprover UI. If that's the case, nice. Set your MONGO_HOSTNAME to srv-captain--myappname--mongo-db or whatever it is supposed to be.

HOWEVER:

If your MongoDB instance lives in the same container as your application, then 127.0.0.1 should have worked. Keep us posted if this worked, or you're still have trouble.

**Comment by Trung229** [comment]
Hi @maietta,

I tried the ones you mentioned, It means I changed MONGO_HOSTNAME from `127.0.0.1` to `srv-captain--admin--mongo-db` but it doesn't seem to work,

I don't know if I missed any of the steps you mentioned

This is my Env File:

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/52306399/155867443-f76fa4d3-2929-46be-a470-1c5a0ebf3886.png">


This is my log on server:

<img width="982" alt="image" src="https://user-images.githubusercontent.com/52306399/155867329-2bfe8622-337e-4a1c-9766-3c03d50eb8c7.png">

This is my log mongoDB status on server:

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/52306399/155867381-c59bdceb-e73e-4c25-9b7b-a7f01cff50c7.png">

This is Log when I type mongo on server:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/52306399/155867405-a005992a-e2cd-4b82-8958-d4545236df48.png">

**Comment by maietta** [comment]
Okay, a few things:

Firstly, srv-captain--admin--mongo-db is definitely not right. There should only be one, not two double dashes separating the srv-captain and the name of your app. There should only be one "--" in the service name.

Secondly, your config appear to have incorrect syntax, potentially causing your app not to parse the values?

- PORT should not have a semicolon after the value.
- You are not enclosing the MONGODB and ACCESS_TOKEN value with single quote mark, as they are strings and I believe this is required.
- There is a couple of environment variables specified in your config that seem to have similar names: MONGODB and MONGO_DB. Are you sure it's not supposed to be MONGO_DBH, as in, Database Handle?

From what I am seeing, your environment looks like a Digital Ocean droplet VPS with a default root prompt. This tells me your MongoDB is running outside a container, so typical Docker Swarm networking will not apply. The use of srv-captain--yourmongoappname does not apply in your case. You'll definately need a locally resolvable DNS entry in /etc/hosts, upstream DNS or the of an IP reachable from your container running your app.

If you are running your app inside a container on a different server than your MongoDB instance, perhaps it's a firewall issue that you ran into.

I believe Ubuntu (based on Debian), uses UFW firewall. For initial testing, you can disable the firewall for port 27017 by running ufw allow 27017.

Some other things I would be checking:

- Make sure MongoDB is binding to a network interface you can reach from your other app, whether its a public IP assigned to your instance or a private network interface between instance.
- Make sure you don't have a firewall blocking the port at the cloud level, not just on the machine of Mongo, if you need to reach the database from elsewhere than the same machine (for testing only, after which I would run a VPN like wire guard to tunnel your traffic between the app and the database, or limit what IP's or netblocks can reach your db)

NOTE: I think in most cases and by default, your app container will NOT be able to reach the real internet and thus may not see your Mongo instance. If mongo was deployed via Caprover, then this wouldn't have been a problem because a overlay network is provide to your apps in the swarm so that the apps can reach eachother by the service names.

The problem I think you are having is that your MongoDB is deployed outside Caprover and thus Docker Swarm networking is not used here.

**Comment by Trung229** [comment]
Hi @maietta,

Now that I know what the problem is, I think I'll move on to using mongoDB caprover's one-click-app

But I want to ask how can I use mongo syntax on server

Like typing db.collections.insert or show.dbs

**Comment by maietta** [comment]
I'm not familiar with mongoDB itself so I won't be of help. My goal was to try and help identify to the problem or a quick solution.

I charge 75/hr (existing clients only) for my time but I chip in here for free where I have a few minutes here and there. Sorry.

Keep us posted when you get your resolution or if you run in any further issues. As long as it's caprover related, this thread probably a good place. I'm just a dude who enjoys using caprover.

-Nick
