### ISSUE TITLE
instance index

### ISSUE THREAD

**Issue by id3vz** [caprover/caprover#1366]
I have a cron job inside my nodejs app which is run every x minutes.
when I run multiple instances of my app, the cron job is running multiple times. which is not what I want.
Is there any way to have an index for every running instance, so I can control to run it only on the first instance?

I used pm2 before and they have an env variable called `NODE_APP_INSTANCE` where you can find the index of the current instance.

**Comment by maietta** [comment]
Caprover is a tool to let you deploy and manage docker services. This is something it does really well, with no bloat caused by adding features not specific to what it's designed for.

This seems like a problem with the way the schedular is designed. The cron job probably isn't designed to be aware that it's running inside a container and thus needs a way to consult with the docker api to determine how many instances are running and which one to find, etc. to run a task on.

If this is an app you wrote yourself and your cron scheduler is inside your app, you need to separate this out or design a mechanism to signal to the rest of the apps that a cron task is already running. Perhaps a flag in the database to say "Hey, a cron job was already started by one of of apps (that's me!), so other apps, please don't perform the task, I got this". This flag, along with a timestamp can help determine if perhaps the task never got completed and thus, part of the cron job can include a provision to continue anyway while removing the old flag, replacing it with it's own if too much time has elapsed.

There are many ways to handle this problem, but this is just one idea.

I personally would run the app in a separate container and give it access to the Docker API under strict permissions. It would be tasked with finding an available app to run a task against and then executing said task.

**Comment by githubsaturn** [comment]
+1 to @maietta 

Also, keep in mind that update strategy for stateless services is "start_first", it's really hard (if not impossible) to maintain an index counter for these containers. I suggest you dedicate a specific container for your one off job.
