### ISSUE TITLE
Save & Load Identities (auth/ssh-key)

### ISSUE THREAD

**Issue by Alfagun74** [caprover/caprover#1501]
**Is your feature request related to a problem? Please describe.**
I get frustrated when i have to reenter my auth/ssh-key every time i create a new app and want to deploy it from git

**Describe the solution you'd like**
The Ability to enter the ssh key / user name once in the settings and save it, then provide a dropdown with saved identities on the app deployment page. So i can simply re use them.

**Comment by maietta** [comment]
Okay, this is scary.

You should only ever have one authentication token per repository with read-only permission on each key limited to the repository in question. If your server was ever compromised, an attacker could gain access upstream to your entire Github organization.

I would highly recommend you nullify every key you use and re-add them with limited scope to read-only and only to the repo and update your Caprover installation.

Just because everything is in containers, doesn't mean you're safe from privilege escalation or docker breakouts. In fact, most containers I see are running root and in past testing, it was not too difficult to break out of the container to reach the docker host.

To make matters worst, most people have a nasty habit of installing docker as root and don't bother using installing docker-engine under a non-privileged user.

I'm almost certain that if I brushed off my hacking skills, I could pawn your server in a matter of a couple of hours (likely much less) and in turn, gain full access to your source code.

**Comment by Alfagun74** [comment]
@maietta Okay, Calm down Snowden.
First of all, not everyone uses Github. There are (selfhosted) Alternatives that provide the feature to create ssh-keys/users with readonly access for your repositories.
Secondly, what do you think the Username/Password Feature is there for? You think people create a new account on their Git for each Project?

**Comment by Alfagun74** [comment]
Oh and lastly @maietta: 
What in gods name are you using caprover for?
This is [non-enterprise hobby-grade software](https://github.com/caprover/caprover/issues/42#issuecomment-352076740).

**Comment by githubsaturn** [comment]
Dupe of https://github.com/caprover/caprover/issues/1353
