### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by kmkallas** [caprover/caprover#1559]
What is the recommended procedure for moving Wordpress /mysql files from an old non-Caprover server to a new Wordpress/mysql site created with Caprover?  My old Wordpress site was a DigitalOcean droplet created with their 1-click app (WP, Apache, MySQL, PHP, Failban, Postfix, Certbot) and it was probably hacked and now crashes constantly.  I can still access it though.  But how are we to migrate an old server such as this to the new Caprover platform?  I would expect that you might have to restore WP and MySQL separately, but where do the WP files go in the WP container, and what is the process to restore the MySQL database?  Install phpmyadmin?  I tried some backup/restore plugins, thinking maybe they were smart enough (Duplicator Pro) but it killed the new site as I though it would.  But at least it was super easy to delete the apps and reinstall them again.  Anyone have a good algorithm to do this?  Thanks in advance.

**Comment by maietta** [comment]
I've done many of these migrations and offer it as a service. These are the following things to know ahead of time:

- A fresh WordPress instance is perfectly okay to perform a WordPress migration from any old system to a new system.
- You have a choice to either install WordPress with, or without a database. (There are two versions available). I always like to try and use the "with database" option and manually import my data using HeidiSQL for Windows or MySQL Workbench for macOS.
- Install another One-Click-App to offer SSH access to your WordPress container. This one is a bit tricky to get setup, but this is a nice option instead of mounting a host directory to the container. You can then SSH into your WordPress container from the outside world using the public/private keypair method (I think the password version of the ssh container was removed)
- While you COULD use phpMyAdmin one-click-app to access your database, I don't recommend this method as phpMyAdmin doesn't do a great job importing databases. If your site is not an ecommerce website, then you should be likely fine but if you are using any plugins that use any advanced features of a MySQL database, you'll want to stick with better tools for the job.

There are some cases were your exported data may not be compatible with the database you are using. If that happens, often times a simple adjustment can be made to your database to get things to work. If that happens, research "strict mode". It is preferred however in the cases, to provide your own database type and version to match that of the old site.

I'm probably missing a few things but these are the basics.

**Comment by maietta** [comment]
Honestly, I think it'd be awesome to write up an in-depth article for the site to show how to perform a migration for WordPress.
