### ISSUE TITLE
Caprover firewall doc may be misleading 

### ISSUE THREAD

**Issue by mjmare** [caprover/caprover#1564]
This page, https://caprover.com/docs/firewall.html, lists the ports that should be opened or closed on the firewall for different Caprover/Swarm purposes. 
And it gives an example on how to set the port access with UFW. 

I used this info to close some ports that were unnecessary for me by removing the corresponding rules. I noticed however, that the ports were still open (with `netstat -tln`).
I think this is because Docker manages its own firewall rules with iptables. See also this article: https://www.howtogeek.com/devops/how-to-use-docker-with-a-ufw-firewall/

I am correct (which is far from certain), then one might unwittingly leave open ports, which might be a security risk.

**Comment by slava-vishnyakov** [comment]
Yes, I tend to agree. Even if you use ufw - it doesn't protect docker. Unless you use howtogeek's way, unfortunately, I couldn't make it work.

**Comment by amazing4u** [comment]
In December 2023 i can still confirm this issue! 

I also think this is very dangerous and the docs should be updated. All the blocking and allowing specific ips do not work using ufw changes.

@githubsaturn Can please someone check if [this guide](https://www.howtogeek.com/devops/how-to-use-docker-with-a-ufw-firewall/) works also with caprover or does someone know a better/working solution?

**Comment by githubsaturn** [comment]
To add context on this thread: CapRover in no shape or form uses ports differently that how Docker does. So if something works on Docker, it works on CapRover. CapRover simply uses a combination of Docker swarm's ingress network plus Docker's host port mapping. **This is a Docker issue, not a CapRover issue**.

- https://github.com/moby/moby/issues/4737
- https://forums.docker.com/t/running-multiple-docker-containers-with-ufw-and-iptables-false/8953
- https://www.techrepublic.com/article/how-to-fix-the-docker-and-ufw-security-flaw/
- https://blog.viktorpetersson.com/2014/11/03/the-dangers-of-ufw-docker.html
- https://askubuntu.com/questions/652556/uncomplicated-firewall-ufw-is-not-blocking-anything-when-using-docker
- https://chjdev.com/2016/06/08/docker-ufw/
- https://askubuntu.com/questions/652556/uncomplicated-firewall-ufw-is-not-blocking-anything-when-using-docker
- https://my.oschina.net/abcfy2/blog/539485
- https://www.v2ex.com/amp/t/466666
- https://blog.36web.rocks/2016/07/08/docker-behind-ufw.html

The most popular tool that try to address this issue is [ufw-docker](https://github.com/chaifeng/ufw-docker).

**Comment by amazing4u** [comment]
Yeah, i understand that it is a issue with Docker.

But i think the documentation should contain this information, because it is not clear that by mapping a port the service is public in the internet even without allowing it in ufw or even when it is denied in ufw. I was shocked to find out! When you know it, you can handle it by for example not mapping it and using the ssh tunnelling instead.

**Comment by githubsaturn** [comment]
Keep in mind that majority of VPS providers offer firewalls that are configured outside of the OS. The problem is only with UFW and docker.

**Comment by githubsaturn** [comment]
Vast majority of users use standard ubuntu installations with UFW. Without running the above command, CapRover installation won't work as Docker only bypasses the mapped port, not registry, discovery etc. 

I've added a note about the mapped port in the docs:
https://github.com/caprover/caprover-website/commit/2cbf816f994a8019e7629e8ab2d52b9d3f3bb5a3
