### ISSUE TITLE
[Question] How to check docker images uploaded to default registry?

### ISSUE THREAD

**Issue by Tarmik0s** [caprover/caprover#1574]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Hi, I was able to push a docker image to the default registry and I just would like to ask if there is a way to check all uploaded docker images? (via UI or CLI is viable). In the UI, probably the most relevant information I found is in the disk cleanup section:

![image](https://user-images.githubusercontent.com/41224463/204963328-fc68d37a-9c1f-4b18-ada5-8ee4f9f6f07c.png)

Thanks in advance!

**Comment by githubsaturn** [comment]
Disk cleanup is only showing the images that Docker engine reports - this does not include the docker registry images. 

To see the images stored in Docker registry, you can either view the volume at `/captain/data/registry` or use a Docker registry GUI like [Joxit/docker-registry-ui](https://github.com/Joxit/docker-registry-ui). 

Just a heads up the built in docker registry is mostly for testing and learning purposes. It's not recommended for production usage due to the fact that it's hard to clean up, also there is no built in data resiliency, meaning that a data corruption might result in all images to be corrupted.
