### ISSUE TITLE
Redis password is updated but not reflected

### ISSUE THREAD

**Issue by mfaheemakhtar** [caprover/caprover#1606]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?

I have updated the redis (installed using 1-click apps) password, it is changed and I see the latest password even after refreshing multiple times. But I can't connect to it using the new password. I am able to connect using the old password.

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:

Update redis password using env variable

Output of the following command on your server:

```
uname -a && lsb_release -a && free -h
```

```Linux ip-172-31-41-37 5.4.0-1080-aws #87~18.04.1-Ubuntu SMP Fri Jun 10 18:32:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
              total        used        free      shared  buff/cache   available
Mem:           3.8G        1.5G        350M        3.3M        1.9G        2.0G
Swap:            0B          0B          0B
```

**Comment by githubsaturn** [comment]
Thanks for the report! Redis one click app was built assuming that the env var is just for the initial password. 

The definition is [now changed](https://github.com/caprover/one-click-apps/commit/742bc4f4a1b642598959107ae444105f31d3caa4).  

Please redeploy your Redis one click app again and let me know if the issue still persists. 

PS:
Please know that other databases (such as MySQL) are designed to allow the password to be initialized using the env var. Password changes after the initial install has to be done through SQL commands. However, in the case of Redis, since the password is managed by CapRover, we were able to make the change and make the password dynamic based on the env var.
