### ISSUE TITLE
[Question] Coldn't find your IP Error

### ISSUE THREAD

**Issue by DaniHRE** [caprover/caprover#1668]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:
Can't run CapRover "Error: Couldn't find your IP".
![Coldn't find ip CapRover error](https://user-images.githubusercontent.com/62768034/219436449-8faa3221-38fd-42c8-b64c-4fccfc7951db.png)

When i run this start command, this error appears. and i don't know why.

**Comment by githubsaturn** [comment]
This seems a lot like the other issue that you posted:
https://github.com/caprover/caprover/issues/1669

Looks like the containers are having trouble connecting to the internet. The root cause behind that is beyond CapRover. Because of a weird networking configuration issue, or it could be firewall, or other internet connection issues.

**Comment by DaniHRE** [comment]
This problem run out if i set the MAIN_NODE_IP_ADDRESS=127.0.0.1 this problem fades away.

This is a temporary solution to this problem.
