### ISSUE TITLE
[Question] Could not resolve host: github.com

### ISSUE THREAD

**Issue by DaniHRE** [caprover/caprover#1669]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:
When i try to run my app.

## Error in App Page
![image](https://user-images.githubusercontent.com/62768034/219455980-9d17ab40-9887-494f-bc74-377a8eda73d2.png)

## Container Log
![image](https://user-images.githubusercontent.com/62768034/219468911-1e656715-e25f-43d6-ba66-34c967344cca.png)

Another question is, how can i set mt proxy to CapRover Apps?

**Comment by githubsaturn** [comment]
The error is self explanatory. The container is unable to resolve the host GitHub.com. 

That means you probably have some network issues. Do you have any specific networking set-up? What VPS provider are you using?

**Comment by DaniHRE** [comment]
i'm not using a vps, i'm using a Ubuntu WSL with CapRover, i have a businnes proxy, in my job.

**Comment by githubsaturn** [comment]
The issue that you're facing with with WSL, not CapRover. WSL has so many weird bugs and it doesn't play well with CapRover and Docker. 

Some people have used CapRover on WSL, but certainly requires a lot of manual adjustments that defeats the ease of use of CapRover.

As [mentioned here](https://caprover.com/docs/get-started.html#b2-server-specs), one of the requirements to run CapRover is a plain Ubuntu machine. WSL is intentionally not listed there because of its bugs and problems. 


Feel free to open an issue on [Docker's github page](https://github.com/moby/moby/issues/), but the scope of this issue is beyond CapRover. You can just manually shell into the container and without using CapRover code try to `curl` github.com and you'll see the same issue.

**Comment by DaniHRE** [comment]
This is what happens what happens in the docker caprover logs exactly when I click to build the project.

![image](https://user-images.githubusercontent.com/62768034/220620217-cab6ed94-3889-4deb-9904-1ca0c87ea0be.png)

**Comment by DaniHRE** [comment]
I think this error is related to the docker container that is created for the application, it may not be recognizing the proxy configuration and not going through the proxy that's why the message: "fatal: unable to access..." @githubsaturn
