### ISSUE TITLE
[Deployment Issue] Zero downtime deployment not possible?

### ISSUE THREAD

**Issue by JonathanDoelan** [caprover/caprover#1690]
I am redeploying a container with a NuxtJS app everytime the data of my headless cms changes via CapRovers Git Deployment method.

It works perfectly and there is one aspect that could be improved:
When the newly generated container starts (or nginx proxy changes the route?) … there are a few seconds when the following screen is present at my apps URL (e.g. app.captain.example.com) with a `<title>` of `Powered by CapRover`.

<img width="1210" alt="502" src="https://user-images.githubusercontent.com/2291224/223049734-0e7ccb09-5d67-49c0-86ca-a88d37d34abc.png">

Is it possible to prevent this screen from being shown? Or to implement an automatic page refresh?

I don’t want to show this screen to my customers in a production app.

(Maybe this is a feature request for „Zero Downtime Deployment“)

**Comment by Kkeller83** [comment]
While it would probaly be possible to develop this in caprover, its
certainly easier for you to just deploy your own load balancer (nginx,
haproxy, traefik etc) and point your customers app url to that. Then on thr
load balancer level you point to 2 instances of your production app.

If you do an update, you will take one instance down and update it while
the other instance is still running and reachable via your load balancer.
Once the updates completes your reroute all traffic to the new instance
while you take down the other instance for update.

Once both instances are updated you can let the load balancer use both
instances again for traffic.

**Comment by githubsaturn** [comment]
@JonathanDoelan  - CapRover by default supports zero downtime deployment. Does your app have any persistent data? If so, that's the only situation that causes non zero downtime deploy, and that's by design:
https://github.com/caprover/caprover/blob/e23b3c7d8af103c6c6dc4cea2973737daabf6e22/src/docker/DockerApi.ts#L1414-L1417

As you can see, if there is no volumes attached to your container, CapRover asks Docker to first start the new container, and only if it's healthy, kill the previous container.

#### if your app doesn't have any volumes:
This (zero downtime deploy) should just work out of the box. If you're not seeing it, it's likely that your container somehow takes a long time to start up. You can look into adding a healthcheck to your Dockerfile that only passes when the container is actually ready.


#### if your app has volumes:
CapRover, by design, first kills the current container, then deploys the second one. The reason behind this is this:
If you have two containers at the same time accessing the same files, it may cause corruption. A quite visible example of this is databases.
