### ISSUE TITLE
[Question] How to enable sticky sessions?

### ISSUE THREAD

**Issue by gustavotoyota** [caprover/caprover#1695]
I already saw https://github.com/caprover/caprover/issues/1415 and https://github.com/caprover/caprover/issues/379, but they don't answer what to put inside the upstream brackets:
```
upstream backend {
  ip_hash;

  ?????
  ?????
}
```
Can it be filled automatically instead of manually for each instance?

Redis doesn't solve the issue for me.
Thank you.

**Comment by githubsaturn** [comment]
```
        set $upstream 
```
can be changed to 
```
upstream backend {
  ip_hash;
  <%-s.localDomain%>:<%-s.containerHttpPort%>;
}
```


Also change `proxy_pass $upstream;` to `proxy_pass http://backend`

**Comment by githubsaturn** [comment]
This may or may not work, since the underlying infrastructure is Docker swarm and it's different from using two explicit domains.


Also. editing nginx configurations is an advanced operations. If you're not an nginx expert, you should NOT edit the nginx config as it might completely break all your apps.

**Comment by smkamranqadri** [comment]
It's not working, I tried, in my case I have files saved locally and when I increase the instance number the file is not accessible.
