### ISSUE TITLE
Your auth token is not valid anymore, try to login again...

### ISSUE THREAD

**Issue by frederikhors** [caprover/caprover#1698]
I installed caprover on my PC from where I can deploy in some `development` environments.

After just one day I get from Caprover this message (during `caprover deploy` command):

```
Ensuring authentication...
Your auth token for [SERVER_NAME] at https://captain.domain.com is not valid anymore, try to login again...
? CapRover machine password: [hidden]
```

and if I enter my password it works again.

Why? Can we have tokens that last longer and maybe never expire (since there are other protections)?

**Comment by githubsaturn** [comment]
This by design to the current single factor authentication. When 2FA becomes available, we can probably look back at this and extend this. 

However, that doesn't mean that you need to enter your password every time. I suggest using an env var and pass the password as an argument to your `caprover deploy --caproverPassword $YOUR_ENV_VAR --caproverUrl $YOUR_CAPROVER_URL_ENV_VAR .....`. 

You can see all possible arguments through `caprover deploy --help`

**Comment by frederikhors** [comment]
Where is it stored the temporary token? I'm on Windows 10.

**Comment by githubsaturn** [comment]
CapRover CLI uses [configstore](https://www.npmjs.com/package/configstore) to save the data on disk. That package decides where is best to store the data.
