### ISSUE TITLE
Scale my nodejs app

### ISSUE THREAD

**Issue by hatemragab** [caprover/caprover#1716]
In recent days I discovered Caprover. 
i save a lot of time deploying my server and managing it thanks a lot,
I have a question about the way to run multiple instances and make a load balance for all of them 
first i think to deploy my app multiple times let's say my app name is api 
so i will create new 3 apps (ap1.exapmle.com) (ap2.exapmle.com) (ap3.exapmle.com)
and set Do not expose as web-app 
them create nginx app to accept the traffics and distribute all to the 3 upstreams 
and make global load balancer 
i want to know is this can be or if there are easy ways done by caprover for this.

**Comment by maietta** [comment]
As long as your apps don't use the persistent storage option, you can use the instances field to increase the instances of the same app.

You can use the Service Override field in Caprover to apply a specific deployment strategy, but you'll need to manually apply labels to your nodes in the Swarm and apply the override config accordingly.

I'm not at my computer so I can't instruct further. I'll follow up this morning.

**Comment by maietta** [comment]
Here's the follow-up I promised:

CapRover deploys apps as standard Docker Services. Consequently, all Docker functions are available and can be leveraged to address specific needs. However, if you wish to use CapRover to replicate instances across nodes with specific labels, it is important to note that CapRover does not currently provide a feature for assigning labels to nodes. Nevertheless, this can still be achieved using regular Docker node commands through the terminal.

By executing the docker service inspect command, you can obtain a JSON response that shares the same structure as the Docker Service Override section, which applies changes to your application service stack. You can utilize the identical syntax to implement any necessary changes to your stack via the App Config > Service Override textarea.

To illustrate, I requested an example of a Docker service inspect JSON response that configures a service to replicate an app across all worker nodes in a Docker swarm. The response was provided since the official Docker documentation lacks such examples.

```json
[
  {
    "ID": "q3fejgmg7nvw",
    "Version": {
      "Index": 27682
    },
    "CreatedAt": "2022-09-18T15:45:42.066875143Z",
    "UpdatedAt": "2022-09-18T15:45:42.101020036Z",
    "Spec": {
      "Name": "my-service",
      "Labels": {
        "com.docker.stack.namespace": "my-stack"
      },
      "TaskTemplate": {
        "ContainerSpec": {
          "Image": "nginx",
          "Labels": {
            "com.docker.stack.namespace": "my-stack"
          }
        },
        "Resources": {
          "Limits": {},
          "Reservations": {}
        },
        "Placement": {
          "Constraints": [
            "node.role == worker"
          ],
          "Preferences": [
            {
              "Spread": {
                "SpreadDescriptor": "node.labels.zone"
              }
            }
          ]
        },
        "RestartPolicy": {
          "Condition": "any",
          "Delay": 5000000000,
          "MaxAttempts": 0
        },
        "ForceUpdate": 0
      },
      "Mode": {
        "Replicated": {
          "Replicas": 2
        }
      },
      "UpdateConfig": {
        "Parallelism": 1,
        "Delay": 1000000000,
        "FailureAction": "pause",
        "Monitor": 5000000000,
        "MaxFailureRatio": 0,
        "Order": "stop-first"
      },
      "EndpointSpec": {
        "Ports": [
          {
            "Protocol": "tcp",
            "TargetPort": 80,
            "PublishedPort": 8080,
            "PublishMode": "ingress"
          }
        ]
      }
    },
    "Endpoint": {
      "Spec": {}
    },
    "UpdateStatus": {
      "StartedAt": "2022-09-18T15:45:42.124918854Z",
      "CompletedAt": "2022-09-18T15:45:42.132985944Z"
    }
  }
]
```

It's evident that the structure closely resembles what is available in CapRover's Docker Service Override section:

![image](https://user-images.githubusercontent.com/11745020/228901327-8b3edd4f-3f8e-494c-a864-e9be536dfbc8.png)

Given this, it is possible to eliminate any unnecessary information and isolate the relevant portion by extracting only what is required.

```json
{
    "TaskTemplate": {
        "Resources": {
            "Limits": {},
            "Reservations": {}
        },
        "Placement": {
            "Constraints": [
                "node.role == worker"
            ],
            "Preferences": [
                {
                    "Spread": {
                        "SpreadDescriptor": "node.labels.zone"
                    }
                }
            ]
        },
        "RestartPolicy": {
            "Condition": "any",
            "Delay": 5000000000,
            "MaxAttempts": 0
        },
        "ForceUpdate": 0
    }
}
```

Hope this helps.

**Comment by hatemragab** [comment]
thanks hope you have great day
