### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by DaniHRE** [caprover/caprover#1718]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:

My api can only be seen by the browser.
I'm using Windows and WSL to run CapRover on Ubuntu.
When I try to connect to my api I use the CapRover address: "auth.captain.localhost".
In the browser this works, but when I try to do the same thing inside WSL, I can't connect. In addition, it is worth mentioning that I am using a business proxy, but in this case, I think it is not trying to do with this problem.

**Comment by githubsaturn** [comment]
As I mentioned [previously in a separate thread](https://github.com/caprover/caprover/issues/1669#issuecomment-1435471192), this is not a CapRover issue, but a WSL issue with Docker. CapRover is not tested on WSL and you may experience issues with WSL, that's why it is not listed under the supported environments.

Please use the [supported stack](https://caprover.com/docs/get-started.html#b2-server-specs) (Ubuntu).
