### ISSUE TITLE
Clean URLs / URL rewriting

### ISSUE THREAD

**Issue by i-kamenov** [caprover/caprover#1735]
Hi guys, I’m having issues getting clean URLs. I’ve scoured GitHub and beyond (Google, ChatGPT, etc) to find a solution, but nothing seems to work for me.

I’m new to programming, so apologies for obvious mistakes.

I’m trying to host a static html-based site with a few html files as pages (index.html, contact.html, bookshelf.html, etc.) and I'm trying to have the urls display without the file extensions (clean URLs). The reason I chose to go with CapRover is:

1. For scalability + to be able to build dynamic sites later on.
2. To learn by doing.

I’ve used the php template in the captain-definition file, and have tried to created a .htaccess file in the root directory of the site, but nothing seems to work. I don't believe the issue can be fixed in nginx, since the code is running on Apache when launching a php-container, if I'm not mistaken (as per the [schema](https://caprover.com/img/captain-architecture.png)). (I've had to restore my environment a few times when messing with the wrong stuff there, whoops.)

Here is my captain file:
```
{
    "schemaVersion" :2 ,
    "templateId" :"php/7.1.10"
}
```
and the .htaccess file:

```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ $1.html [L,QSA]
```

- I've also tried the steps described in #189 , but I can't seem to deploy my code when I copy-paste the code mentioned. (With two separate files in the root directory). I don't understand enough of what's going on to alter it in case some part of it is depreciated.

I hope this wasn’t too vague, and many thanks for all the help!

**Comment by githubsaturn** [comment]
@i-kamenov 

This issue is not related to CapRover. This is an Apache question. Probably the best is to use stackoverflow and ask the question there.

There are many solutions discussed on stackoverflow, like this one:
https://stackoverflow.com/questions/1992183/how-to-hide-the-html-extension-with-apache-mod-rewrite

But regardless, this is really an apache question and I can't comment on how to fix this. 


As a reminder, CapRover is just a deployment platform. Once you're app is deployed and running, CapRover is completely out of the loop and if you're experiencing issues post deployment, CapRover forums are not the best place to ask these questions.

**Comment by i-kamenov** [comment]
Thanks, @githubsaturn! 

Yeah, it is more a docker question actually. 

For posterity, I'll just add that it seems I had to write a Dockerfile that looks something like this:

```
FROM php:8.0-apache
RUN apt-get update && apt-get install -y git curl
RUN mkdir -p /var/www/
COPY ./apache2.conf /etc/apache2/apache2.conf #Replaces the default apache config file with modified one
COPY . /var/www/
WORKDIR /var/www/ 
RUN echo httpd -V
CMD [ "php", "-S", "[::]:80", "-t", "/var/www/" ]
EXPOSE 80
RUN a2enmod rewrite 
RUN service apache2 restart
```
So that I can rewrite the apache config files to allow the .htaccess file to be read by the server.

For some reason it's still not working as intended though, but this isn't the right place to ask.

Thanks for the help!
