### ISSUE TITLE
Multi user support and TFA authentication support

### ISSUE THREAD

**Issue by rinshadka** [caprover/caprover#1748]
Hello, 

I have gone through the caprover tool and experienced  the potential and would like to use this in production environment.

However I couldn't find the multi users / role based restrictions and 2FA implementation. Is this in place or am I missing something.

Thanks.

**Comment by maietta** [comment]
There is another discussion already active here on this topic.

2FA is coming, but multi user is not.

It is not practical yo implement multi user features in a system like this mainly because it makes no sense from a technical perspective.

If you give someone direct access to deploy a container, then you effectively can't easily or safely restrict the permissions of another user who can also deploy containers. Isolation between users and their containers would require careful coding, and even with that it would provide a false sense of security.

CapRover deploys directly to Docker, so all the same rules of docker and docker security apply.

**Comment by rinshadka** [comment]
Thanks for the update. Can I use any other OAuth services like [oauth2_proxy ](https://github.com/oauth2-proxy/oauth2-proxy) in front of caprover to provide 2FA support since I wish to go production with caprover.

**Comment by githubsaturn** [comment]
You can build your own, but there is no built in solution.
