### ISSUE TITLE
[Question] How to enable ssl with cloudflare tunnel?

### ISSUE THREAD

**Issue by leozaur1808** [caprover/caprover#1788]
Hello guys, I have been trying to setup root domain with Cloudflare tunnel.

The first thing that must be noted is that I cannot turn off the proxy because I use tunnels. I tried copying certs from cloudflare origin server, importing them to `/captain/data/nginx-shared` and executing `chmod 600` on each of them, yet I get the "Nothing here yet" error when accessing via my domain name (though it works perfectly when accessing from the local network). Logs suggest that I keep getting 304 errors. How to fix this?

UPD: I managed to fix "Nothing here yet" error, yet I still cannot force https as otherwise the whole captain installation becomes unavailable.

**Comment by githubsaturn** [comment]
First thing first: Cloudflare tunnels are not an officially supported way of setting up a CapRover instance. You do need a globally accessible public IP for CapRover to work out of the box.

With regards to your question, more information is needed to debug what's going on. "yet I still cannot force https" - what does this mean? Can you not connect to https://captain.domain.com or just the force https function doesn't work? What do you see when you cURL to the HTTPS url? What do you see in nginx logs?

**Comment by Tivin-i** [comment]
I did manage to replace nginx certs for a specific service by editing the nginx configuration for it, haven't tried for the captain.x.x domain though.

**Comment by leozaur1808** [comment]
> First thing first: Cloudflare tunnels are not an officially supported way of setting up a CapRover instance. You do need a globally accessible public IP for CapRover to work out of the box.
> 
> With regards to your question, more information is needed to debug what's going on. "yet I still cannot force https" - what does this mean? Can you not connect to https://captain.domain.com or just the force https function doesn't work? What do you see when you cURL to the HTTPS url? What do you see in nginx logs?

Hi, thank you for your answer. The captain.xx.com works and I can connect with https. The only problem left is that I cannot enable "Force https" because if I enable it, the whole service ceases to work. Here is my caprover nginx config:

```
# Default catch-all page. e.g. if you enter SOME-RANDOM-CHARS.captainroot.domain.com
    server {

        # Catch all HTTP
        listen       80;

        # Catch all HTTPS
        listen              443 ssl;
        ssl_certificate     /nginx-shared/xx.com.pem;
        ssl_certificate_key /nginx-shared/xx.com.key;

        server_name  _;

        location /nginx_status {
            stub_status on;

            access_log off;

            # This can be improved by adding authentication as well.
            # CIDR Range IPs:
            allow 172.16.0.0/12;
            allow 10.0.0.0/8;
            allow 192.168.0.0/16;
            
            deny all;
        }

        location / {
            root   <%-captain.defaultHtmlDir%>;
            index  index.html index.htm;
        }

        error_page 404 /index.html;
        error_page 500 502 503 504 /error_generic_catch_all.html;
    }


# Captain dashboard at captain.captainroot.domain.com
    server {

        listen       80;
        client_max_body_size 300m;

    <%
        if (true) {
    %>
        listen              443 ssl;
        ssl_certificate     /nginx-shared/xx.com.pem;
        ssl_certificate_key /nginx-shared/xx.com.key;

    <%
        }
    %>

        server_name  <%-captain.domain%>;

        # 127.0.0.11 is DNS set up by Docker, see:
        # https://docs.docker.com/engine/userguide/networking/configure-dns/
        # https://github.com/moby/moby/issues/20026
        resolver 127.0.0.11 valid=10s;
        set $upstream http://<%-captain.serviceName%>:<%-captain.serviceExposedPort%>;

        # IMPORTANT!! Except proxy_read_timeout, this block should be same as location /api/v2/user/apps/appData
        location / {
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # temporary until build process becomes an asynchronous process
        location /api/v2/user/apps/appData {
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_read_timeout 120s;
        }

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-captain.staticWebRoot%>;
        }
        
        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-captain.staticWebRoot%>;
        }
    }



# Built-in Docker Registry at registry.captainroot.domain.com
# Port 80/443 is used by Let's Encrypt to support HTTPS
# But the Registry engine runs on port 996
    server {

        listen       80;
        client_max_body_size 500m;

    <%
        if (true) {
    %>
        listen              443 ssl;
        ssl_certificate     /nginx-shared/xx.com.pem;
        ssl_certificate_key /nginx-shared/xx.com.key;
    <%
        }
    %>

        server_name  <%-registry.domain%>;

        location / {
            root <%-registry.staticWebRoot%>;
        }
    }
```

**Comment by Tivin-i** [comment]
I just remembered that I didn't use a CF tunnel, but just replaced the certificates.
One question comes to mind, why are you trying to force HTTPS on the nginx if you are already using a tunnel on the Caprover host?

Host---->CF HTTPS---->Tunnel---->Service

If you configure the tunnel to * resolver, and HTTP in the back then it doesn't really matter if those are self-signed or CF certificates because those would be terminated on the tunnel anyway, which is located on the localhost.

**Comment by leozaur1808** [comment]
Frankly speaking, I am just curious whether avoiding Let’s Encrypt completely is possible or not.  I have Cloudflare Origin CA setup with NGINX (as in the file above if someone is curious) and Cloudflare Strict SSL enabled.

From: Tivin ***@***.***>
Date: Thursday, 29 June 2023, 18:04
To: caprover/caprover ***@***.***>
Cc: Lev Zharikov ***@***.***>, Author ***@***.***>
Subject: Re: [caprover/caprover] [Question] How to enable ssl with cloudflare tunnel? (Issue #1788)

I just remembered that I didn't use a CF tunnel, but just replaced the certificates.
One question comes to mind, why are you trying to force HTTPS on the nginx if you are already using a tunnel on the Caprover host?

Host---->CF HTTPS---->Tunnel---->Service

If you configure the tunnel to * resolver, and HTTP in the back then it doesn't really matter if those are self-signed or CF certificates because those would be terminated on the tunnel anyway, which is located on the localhost.

**Comment by Tivin-i** [comment]
Well, it should be. Just avoid HTTPS on Caprover and enforce it with CF tunnel.
You can also do the redirect, but unless you change the code to force it in every time you will end up with a manual hassle.

**Comment by githubsaturn** [comment]
Not sure how Cloudflare tunnel SSL works under the hood. But likely some headers aren't set properly. See here:
https://github.com/caprover/caprover/blob/master/src/app.ts#L78-L91
This is the code that takes care of the redirect.


Another way to force ssl without having to enable it from the dashboard is to modify the nginx config. Remove `listen 80` from here:
```
# Captain dashboard at captain.captainroot.domain.com
    server {

        listen       80;
```


Then just add a block for redirect above that:
```
    server {

        listen       80;
        server_name  <%-captain.domain%>;

  
        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-captain.staticWebRoot%>;
        }
        
        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-captain.staticWebRoot%>;
        }

        location / {
            return 302 https://$http_host$request_uri;
        }
    }
```

**Comment by wildyaboku** [comment]
I've been successfully using CapRover behind a Cloudflare tunnel for several months. I installed `cloudflared` as an app within CapRover, using its `config.yml` file within a volume to map the various hosts:

```yml
ingress:

  - hostname: example.com
    service: http://captain-nginx:80

  - hostname: '*.example.com'
    service: http://captain-nginx:80

  - service: http_status:404
```

On the CapRover side of things, you don't enable SSL. This is not a concern because the tunnels themselves are always encrypted. You must enforce SSL from your Cloudflare dashboard (SSL/TLS > Edge Certificates > Always Use HTTPS) for each domain.

Finally, from the Cloudflare DNS manager, I set each hostname to `CNAME UUID.cfargotunnel.com` which points it to the tunnel (and thus, my CapRover nginx instance).

With this, you can completely close your server off from the internet without opening any ports (not even `443` or `80`), without issuing SSL certificates at all, and without touching the CapRover configuration (aside from disabling domain verification).

**Comment by adamshand** [comment]
@wildyaboku any chance you could provide a bit more detail on how you got this up and running?  I'm having trouble passing the token to `cloudflared` or figuring out where to put the `config.yml` ...

**Comment by wildyaboku** [comment]
> @wildyaboku any chance you could provide a bit more detail on how you got this up and running? I'm having trouble passing the token to `cloudflared` or figuring out where to put the `config.yml` ...

Sure!

The approach I described above is for a locally-managed Cloudflare tunnel, which needs to be created via their CLI and can only be configured from the configuration file. If you created a tunnel from their Zero Trust dashboard, then it's a remotely-managed tunnel, and can only be configured through Zero Trust.

I chose the locally-managed version, because the online dashboard used to lack some configuration options and had clunky pagination for large numbers of hosts. I think it's a lot better today and can recommend using the dashboard, especially because its lack of a config file means it can be replicated to multiple nodes, which Cloudflare Tunnel handles by directing traffic to the geographically nearest node ([supposedly](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/deploy-tunnels/deploy-cloudflared-replicas/)).

The basic setup for `cloudflared` on CapRover is as follows:

1. Create a new app in the CapRover interface named `cloudflared` or similar.
   - For locally-managed tunnels (created through the CLI), enable persistent data for the configuration file.
   - For remotely-managed tunnels (created through the online dashboard), **do not** enable persistent data.
2. Check the "do not expose as web app" box.
3. Configure the environment variables shown below.

```env
TUNNEL_TOKEN=
NO_AUTOUPDATE=true
```

4. In the "Service Update Override" configuration textbox on the CapRover app, enter the following configuration, which invokes the `run` command. I'm not sure if they have a better way of doing this, but it works for me.

```yml
TaskTemplate:
  ContainerSpec:
    Args:
      - tunnel
      - run
```

5. For locally-managed tunnels only, create a volume for the app path: `/etc/cloudflared`
    - The `config.yml` file will go in the root folder of the created volume.
7. Save changes.
8. Deploy the `cloudflare/cloudflared:latest` image.

As for configuring hostnames, either through the Zero Trust dashboard or the local configuration file, the process is identical. You will simply need to map the real hostname (`example.com`) to the captain hostname (`http://captain--example:80`).

**Comment by adamshand** [comment]
@wildyaboku thank you that was super helpful.  I was trying to add the arguments to `cloudflared` by using `command` in the service override.  

I'm not sure if what I could be doing wrong, but for a remotely managed tunnel I had to change the override to the below in order to get it to work:

```
TaskTemplate:
  ContainerSpec:
    Args:
      - tunnel
      - run
      - --token
      - <TOKEN>
```

**Comment by VictorioBerra** [comment]
This has been tough, and it does involve $10 CF ACM. But I too wanted Cloudflare tunnel, I wanted to block all connections to 80/443 on my firewall and ONLY allow access through tailscale or cloudflare tunnel. Does not get more secure than that.

- moved my route53 NS to cloudflares NS
- Installed tailscale on the bare metal of the server
- Close ALL ports via firewall. **tailscale and cloudflare tunnel allowed only!**
- installed cloudflare tunnel on bare metal, used version 2025.2.0
- edit /caprover/data/config-captain.json (via tailscale)
  - customDomain: "caprover.custom1.apps.example.com"
  - hasRootSsl: false
  - forceRootSsl: false
- enforce SSL from your Cloudflare dashboard (SSL/TLS > Edge Certificates > Always Use HTTPS) for each domain
- Buy cloudflare Advanced Cert Management ($10/mo), go to SSL settings, allow Total TLS
- Go to CF DNS -> create DNS record for `*.custom1.apps.example.com` set to the CF tunnel CNAME. Mine is `GUID.cfargotunnel.com` where GUID is in the CF Tunnel Web UI address bar.
- go into CF tunnel dashboard -> create Public Hostname -> set `*.custom1.apps.example.com` and have it go to http://localhost.
- Make sure all Caprover sites do NOT use force HTTPs.
