### ISSUE TITLE
[Question] Disable prune

### ISSUE THREAD

**Issue by RealityWinner** [caprover/caprover#1836]
Please clearly state your question:

Why is caprover pruning all docker containers with no option to disable or warning? I deployed caprover on my existing docker setup and now have lost multiple docker containers as a result.

**Comment by githubsaturn** [comment]
I'm very sorry that it caused headache for you. But this is actually a very **sane** default. CapRover has defaults for many many things so that the end use does not need to configure a million knobs. That's the main design principle of CapRover.

Normally we provide override options for some default configs, but in this case, after 100M+ docker pulls and tens of thousands of installation, this is the first report of this behavior being an unwanted behavior. Unfortunately, this is one of those cases that apparently does not make sense to provide an override for. Any good design has to make compromises here and there, and unfortunately you were hit by one of these. 

Last but definitely not least, CapRover DOES NOT kill any existing running containers. It only prunes the dead containers. As a good practice, you should never rely on dead containers for important tasks. Use volumes, docker compose, docker stack etc.

**Comment by githubsaturn** [comment]
Will you be submitting a PR for the improvement?
