### ISSUE TITLE
[Question] Licence change to "open core", why this silent change?

### ISSUE THREAD

**Issue by matbgn** [caprover/caprover#1852]
As a contributor, I'm shocked to see such a sneaky change to the licence model, and not publicly communicated, but obfuscated in a merge request process.

https://github.com/caprover/caprover/commit/ea1b06a1a6c1d6d153348572bb274bb22cd31b77

Any info on that?

**Comment by githubsaturn** [comment]
Hi @matbgn - this version includes some paid features. It is publicly communicated as Terms and Conditions are in the release note. I understand that it's a change from previous model, but this is to protect the cost of the paid features. What's your specific concern?

**Comment by matbgn** [comment]
Actually, there is no specific mention of changing the licence model on its own, so the less we could say is that this is not really a transparent process or community process at all for such a change.

What's your ultimate goal? What is the code base that will remain core free? What will never be merged into the core? 2FA what else? How would a licence lock be applied and how would it affect core users (as we must now call ourselves)? What are the opt-outs, e.g. for marketing or forced upgrade policy? And so on... In fact, we have so many concerns for such a critical service as our PaaS that the word "specific" has absolutely no meaning here.

**Comment by githubsaturn** [comment]
> In fact, we have so many concerns for such a critical service as our PaaS that the word "specific" has absolutely no meaning here.

I'm a solo developer working on the project. I'm not a mega company. The pros and cons for you as the end user is the same. I won't be making a 1000 page T&C that you cannot read. The T&C is clear and short. So you'd have to be specific about your concern to enable me to answer.

> What's your ultimate goal? 

The goal behind making these changes is simple. The premium features are easy to replicate. Once replicated, I won't have any reasons to support the project and I'd simply archive it. I'm sure that's not what anyone who uses CapRover wants.


What is the code base that will remain core free?
* The code that you see, you won't pay for what you're not paying today.

What will never be merged into the core? 2FA what else? 
* This depends on what features the paid users ask for. If anyone, discusses, builds a net new feature and opens a pull request, I'm not gonna close that and replicate it as a paid feature. Take [this issue for example](https://github.com/caprover/caprover/issues/905), I don't see a world where this is a paid feature. 

How would a licence lock be applied and how would it affect core users (as we must now call ourselves)? What are the opt-outs, e.g. for marketing or forced upgrade policy? 
* Like I said, this license a simple "please don't eat my lunch license", the purpose is to make sure I don't end up pausing all the development work one day because a script boy replicated the 2FA as a free feature. Believe me, this is for all users' benefit.


I am genuinely committed to answer any questions you might have.
