### ISSUE TITLE
Deploy failed! Error: Command failed: ssh-keyscan -p 22 -H github.com >> /root/.ssh/known_hosts

### ISSUE THREAD

**Issue by m4rcster** [caprover/caprover#1932]
I have been using the  Method 3: Deploy from Github/Bitbucket/Gitlab via webhook for a couple of years now. Since the upgrade to 1.11 it behaves inconsistently. Deployments fail:

The logs say:

```
------------------------- Thu Nov 02 2023 10:20:37 GMT+0000 (Coordinated Universal Time)
Build started for dreistuben
Build has failed!
----------------------
Deploy failed!
Error: Command failed: ssh-keyscan -p 22 -H github.com >> /root/.ssh/known_hosts
```

I have recreated a key according to the docs : https://caprover.com/docs/deployment-methods.html

It worked once, then it stopped again. Any Ideas?

**Comment by m4rcster** [comment]
BTW I pushed Force Build Again and It worked...

![image](https://github.com/caprover/caprover/assets/14793583/0504cace-05fa-4bc0-a486-32e871a2ec5d)
72 -> Force Build
71 -> Force Build
70 -> Force Build
69 -> Webhook

**Comment by githubsaturn** [comment]
What host you're using? Is it possible that github.com is rate limiting your requests before the same IP is sending way too many requests to github.com?

You can manually shell into the container and try to run the exact same command to see why it fails. Make sure you first shell into the container and the results might be different from running it on the host.

**Comment by m4rcster** [comment]
Caprover is running on an ubuntu 20.04 Raspberry Pi 4, 8GB. Do you mean to ssh on the host and deploy from there? or into the captain-captain container?

**Comment by githubsaturn** [comment]
Into the captain-captain container

**Comment by Baxket** [comment]
I am facing the same error
Deploy failed!
Error: Command failed: ssh-keyscan -p 22 -H github.com >> /root/.ssh/known_hosts
getaddrinfo github.com: Try again
getaddrinfo github.com: Try again
getaddrinfo github.com: Try again
getaddrinfo github.com: Try again
getaddrinfo github.com: Try again

**Comment by githubsaturn** [comment]
Looks like github is blocked from your VPS IP address.

**Comment by burak-sayici** [comment]
Hi, I'm getting the same error and I haven't been able to resolve it in any way. It happens when I use the private repository on GitHub. If I use a public repository, there is no problem. Can you help me with this issue?

I created an ssh key in PEM format.
ssh-keygen -m PEM -t ed25519 -C "yourname@example.com" -f ./deploykey -q -N ""

I added deploy key to GitHub and added webhook.

![image](https://github.com/caprover/caprover/assets/155234322/435e6569-d4dc-4387-b5e5-99a400d81b90)

![image](https://github.com/caprover/caprover/assets/155234322/96ad60e8-9fbd-41e6-9dbc-cc8e72482c89)

![image](https://github.com/caprover/caprover/assets/155234322/5ec2b94a-2954-4e6a-b4d0-fa593da88b06)

![image](https://github.com/caprover/caprover/assets/155234322/3cb601ca-67d6-46bf-9282-e4cd01da02cf)

**Comment by githubsaturn** [comment]
Login to https://captain.server.demo.caprover.com 
Password is `captain42`

There is an app called "test-private-repo`, go to the deployment tab and copy paste all values from those boxes to your instance, and click on Force Build. Does it work?

**Comment by burak-sayici** [comment]
Hello, first of all thank you for your response. When I click on the force build button, it does not take any action, it gives a warning.

![resim](https://github.com/caprover/caprover/assets/155234322/1bcb1a98-54a6-4957-9aa1-eaaf54cf91e0)

**Comment by burak-sayici** [comment]
First of all, thank you for your reply and happy new year. I copied all the data in the application you mentioned, but I did not get any results. I am attaching screenshots.

When I make a public repo and there is no ssh key, it deploys without any problem. But I want to use it on private repo.
The operating system I use: Ubuntu 22.04.3 LTS
Caprover version: 1.11.1

Thank you.

![image](https://github.com/caprover/caprover/assets/155234322/32003c9f-9283-4fcc-b0e2-502e5e236a3f)

![image](https://github.com/caprover/caprover/assets/155234322/18bb604e-a138-45f8-a71d-c0f56f3e6a3b)

**Comment by githubsaturn** [comment]
So this shows that your server fails to resolve the SSH path on github - this is why the public repo works but private repo fails. 

To debug further, run this:
```
docker exec -it $(docker ps --filter name=captain-captain -q) ssh-keyscan -p 22 -H github.com
```

What's the output?

**Comment by burak-sayici** [comment]
with out sudo:

![resim](https://github.com/caprover/caprover/assets/155234322/8358f556-59e7-4425-9891-79440f2cc203)

with sudo:

![resim](https://github.com/caprover/caprover/assets/155234322/70856ffb-3fa0-4e9b-88a4-f601f06f4c37)

**Comment by githubsaturn** [comment]
With sudo it doesn't return anything?!
Try this:
```bash
sudo docker exec -it $(docker ps --filter name=captain-captain -q) /bin/bash
# wait until in the container
pwd
ssh-keyscan -p 22 -H github.com
curl -Iv github.com
```

**Comment by burak-sayici** [comment]
no, running it with sudo returns nothing.

I get this output when I run your last command without sudo:
![image](https://github.com/caprover/caprover/assets/155234322/c4b842a7-4a14-4963-b534-b02db437b092)

sudo root with:
![image](https://github.com/caprover/caprover/assets/155234322/9027b9d9-ce31-4efd-88eb-f86288bf4489)


I might be doing something wrong, I'm a bit inexperienced.

Thank you.

**Comment by githubsaturn** [comment]
I just edited the command in the previous comment, please try again (note it's now "bin/sh")

**Comment by burak-sayici** [comment]
`ssh-keyscan -p 22 -H github.com`

Unfortunately, the code I wrote above does not produce any output.

![image](https://github.com/caprover/caprover/assets/155234322/0c4b1d40-c03a-4e60-9d43-ec068fa4040a)

**Comment by githubsaturn** [comment]
Where's your server located? Is it a virtual server on the cloud?

Looks like your server provider has blocked the outgoing access to SSH ports. 

https://superuser.com/questions/1762386/ssh-keyscan-does-not-return-a-key#:~:text=It%20usually%20means%20that%20the,%2Dkeyscan'%20lacks%20that%20option.

**Comment by burak-sayici** [comment]
Hello again. I live in Turkey and my server is in Turkey. My server is not a virtual server. It is a system that I prepared by installing ubuntu on a computer I do not use at home and with a static ip purchased from my internet service provider. I didn't see anything blocking the rule to the SSH port.
I ran sudo ufw allow ssh and there are no restrictions on the modem connected to the internet at home, firewall is disabled.
I would also like to point out that I was able to clone a private repo by adding the ubuntu server git ssh public key via terminal. If SSH was blocked, wouldn't ssh -T git@github.com give an error? It worked successfully for me. I don't know what to do about the issue, I'm waiting for your help.
Thank you very much,
Good work.

**Comment by githubsaturn** [comment]
1- Does `ssh -T git@github.com` also work fine if you're running it from within the container?
2- Can you try using username/password. Username `burak-sayici` and for password, use a Personal Access Token: https://github.com/settings/tokens (Use **Classic Token**) Select all checkmarks under repo

Does this work?

![image](https://github.com/caprover/caprover/assets/10582082/3b264513-9cf8-4aaf-bda7-2c32e01b2270)

**Comment by burak-sayici** [comment]
Hello again,

1) The code is not working properly inside the docker container, it gives a timeout error. Here is a screenshot of the code I run both outside and inside:

![image](https://github.com/caprover/caprover/assets/155234322/0d1d5359-0f77-4657-b737-2e4eeff52657)


2) This method finally worked for me! Thank you very much.

![image](https://github.com/caprover/caprover/assets/155234322/069adcb5-4002-4413-a857-3f24ae91eaf5)

I don't really understand why SSH doesn't work inside the container.
I want to ask one more question, I don't know if it's right to ask it in this thread, but I'll ask it anyway.
I have an asp dot net project and while I can run it on my local computer without any problem, I couldn't get it to run when I deployed it to Caprover. In order to understand and test the problem, I used the method you presented on the document 
When I went to "https://github.com/caprover/caprover/tree/master/captain-sample-apps" and downloaded the "asp_dot_net.tar" project and built it on docker, I got an error. Unfortunately, the example does not work.
The project I have is a web api ready template. I haven't made any changes to it yet, it's a simple template created by visual stuido.
I have made my repo public and I am sharing my settings. Can you give information about where I am wrong?

I am an inexperienced user, so I apologise.
Thank you.

Repo: [](https://github.com/burak-sayici/e-bilet)
Domain: [](https://test-e-bilet.buraksayici.com/)
Caprover Settings:

![image](https://github.com/caprover/caprover/assets/155234322/8c6d40e8-161a-42e4-911a-78122e28eff7)

![image](https://github.com/caprover/caprover/assets/155234322/e00cc161-fdc2-4936-9e3a-dea2c22de58b)

![image](https://github.com/caprover/caprover/assets/155234322/545f3414-6742-4691-9631-f092d8bb1171)

Local:

![image](https://github.com/caprover/caprover/assets/155234322/ae30a2c5-d55a-4b61-90c3-c139f81f692b)

**Comment by githubsaturn** [comment]
> I don't really understand why SSH doesn't work inside the container.

It's a problem with your server. My guess is that you took a non-conventional approach to Docker installation. I can see from your previous commands that using `sudo` makes the docker commands to fail. So something is messed up with your docker installation. I recommend using a standard docker installation on a standard ubuntu.

> I want to ask one more question, I don't know if it's right to ask it in this thread, but I'll ask it anyway.
I have an asp dot net project and while I can run it on my local computer without any problem, I couldn't get it to run when I deployed it to Caprover

Try running docker locally and see if it works. CapRover just deploys your docker image. Once your docker image works, CapRover instance will also work.

**Comment by anhitvn** [comment]
I had the same problem when trying to deploy a repo from github using ssh.

I researched and found the problem was due to the caprover vps being blocked by the firewall on port 22 and unable to listen to github's ssh port 22
System Admin when blocking default ssh port of vps caprover, accidentally blocked both directions. You can reconfigure from firewall or notify your System Admin
