### ISSUE TITLE
Custom CA certificate inside caprover

### ISSUE THREAD

**Issue by tobmatth** [caprover/caprover#1935]
I am running caprover within a corporate network behind a firewall that inspects SSL traffic. Therefore i need to add the firewall's root CA to my caprover image (as the connection to https://oneclickapps.caprover.com fails the certificate check at the moment). Any hints on how to do so?

**Comment by githubsaturn** [comment]
Please see: https://github.com/caprover/caprover/issues/265

TLDR: it's possible, but it requires modifying some nginx configs.

**Comment by githubsaturn** [comment]
Hi @tobmatth - CapRover doesn't have support for uploading custom CA certs. Also, worth noting that this issue is not CapRover specific. The only way that I know you can add a custom CA cert to a docker container is to modify them and copy the CA certificate inside.

https://stackoverflow.com/a/42292623
