### ISSUE TITLE
[Deployment Issue] On Click App Strapi

### ISSUE THREAD

**Issue by zknowz** [caprover/caprover#2044]
What is the problem?

I'm trying to install strapi on caprover but for some reason I can't connect it.

![Screenshot 2024-04-17 at 9 41 48 AM](https://github.com/caprover/caprover/assets/14256684/c4a9b2bf-4da9-4458-940f-e5ae589372ca)

**Comment by nativeit** [comment]
You may want to move this issue to the [One Click Apps](https://github.com/caprover/one-click-apps) repository, it's my understanding that this repo is primarily for the core Caprover platform.

But since we're here, Strapi has a complicated history with MongoDB support (see this [link](https://forum.strapi.io/t/mongodb-compatibility-delayed-on-v4/4549/136) for more details), and in hindsight it was probably a bad choice for the main Strapi template. I will look into updating this template myself, but in the meantime, it's probably better to use the PostgreSQL version. 

That said, there is another caveat--both templates are using the old Strapi v3, because for v4 Strapi dropped support for pre-compiled Docker containers (details at this [link](https://docs.strapi.io/dev-docs/installation/docker)), and so there are no official images for the templates to use for Caprover's One Click Apps, rather one must build a custom Docker image. It is still possible to deploy v4 on Caprover using a custom Docker image, but that does require specific knowledge of Dockerfiles and writing custom templates, which may/may not be something you're familiar with and/or willing to venture into under the circumstances.

I'm not sure if there are any ongoing discussions about removing the old templates, or potential workarounds, but if so they are likely to be found in the One Click Apps repo.

Hope this helps!

**Comment by nativeit** [comment]
I forgot all about this, to be honest, but I actually have an open issue over in the OCA repo, you can join the discussion [here](https://github.com/caprover/one-click-apps/issues/787).

**Comment by zknowz** [comment]
All fix but Thank You!
