### ISSUE TITLE
[Question] Severely degraded performance - what gives?

### ISSUE THREAD

**Issue by PhatDave** [caprover/caprover#2159]
Hello, I'm trying to figure out why I'm getting such "poor" performance out of caprover
I have a simple [nsq](https://github.com/nsqio/nsq) installation running on caprover with 41515 mapped to 4151 and its http port is set to 4151
And I'm querying it from the same network - different machine
The network speed between those two is 1Gbit
I also have both *shitbox* and *nsq.site.\<domain>* resolve to the same IP - 192.168.1.123
Running nslookup on both shitbox and the domain gives the same result - 192.168.1.123

Now when I do:
`bombardier -b '<redacted for brevity>' -m 'POST' -c 100 http://shitbox:41515/pub?topic=queue`
I get
```
Bombarding http://shitbox:41515/pub?topic=queue for 10s using 100 connection(s)
[============================================================================================================================================================================================] 10s 
Done!
Statistics        Avg      Stdev        Max
  Reqs/sec     70591.42   21439.02   92215.72
  Latency        1.42ms     1.58ms   176.59ms
  HTTP codes:
    1xx - 0, 2xx - 704648, 3xx - 0, 4xx - 0, 5xx - 0
    others - 0
  Throughput:   101.33MB/s
```
Throughput is almost network speed, I assume the loss is in processing, we can live with that
But when I try to go through the domain I get:
```
Bombarding http://nsq.site.<domain>:80/pub?topic=queue for 10s using 100 connection(s)
[============================================================================================================================================================================================] 10s 
Done!
Statistics        Avg      Stdev        Max
  Reqs/sec      7554.53    1549.93   11211.52
  Latency       13.32ms     3.87ms   243.01ms
  HTTP codes:
    1xx - 0, 2xx - 75058, 3xx - 0, 4xx - 0, 5xx - 0
    others - 0
  Throughput:    11.15MB/s
```
It is pretty much at 1/10th the speed in both throughput and latency

I have also tried https vs http thinking that was the difference but the speed is almost identical
What gives?
What can I do about it?

Note: I am using caprover version 1.12.0 and nginx 1.24

**Comment by githubsaturn** [comment]
The problem is not `shitbox` vs. `nsq.site.<domain>`, rather it's because your second try goes through nginx and then the nsq container. 


So somehow nginx is adding a lot of latency here. I am not sure about the inner workings of nsq, but I bet they have some recommendations for best tuned nginx configuration. CapRover's default nginx configuration is not tuned for specific use cases, rather it's a simple one:
* [nginx base config](https://github.com/caprover/caprover/blob/master/template/base-nginx-conf.ejs)
* [nginx per app config](https://github.com/caprover/caprover/blob/master/template/server-block-conf.ejs)


Maybe try `worker_processes auto` or `worker_connections 4096` 
Also you may be able to optimize performance by adding:
```
use epoll;  # for Linux
multi_accept on;
```

So generally speaking, there are hundreds of ways that you can "tune" your nginx configuration for your specific usecase. CapRover allows these configurations to be updated:
* You can edit the configuration for base on settings page
* You can also edit per-app configs on app's HTTP settings page

**Comment by PhatDave** [comment]
huh, OK
I had just assumed that since nginx was so well known it would pose no issue or obstacle (and magically work perfectly) but I guess it's a lot more complicated than I thought
Thank you for your advice, I will try playing with the nginx config, maybe get something close to the original, raw, result

**Comment by githubsaturn** [comment]
Yea nginx's default configuration is good enough for most cases, but when it comes to performance tuning, there are definitely a lot of configs you can adjust to get the most out of your hardware.
