### ISSUE TITLE
Captain ignores webhooks while building

### ISSUE THREAD

**Issue by olehermanse** [caprover/caprover#266]
Captain ignores webhooks while building. This means that if you push to multiple projects with GitHub webhooks, or have set up one github repo to send multiple webhooks to different captain apps, it won't work, **some apps will never be built**.

When 2 webhooks are received (roughly) at the same time, the second one is ignored with a 200 response, and this body:
```
{"status":1000,"description":"An active build (app name) is in progress... please wait..."}
```

If applicable, content of `captain-definition` file:
https://github.com/olehermanse/dagensquiz/blob/master/captain-definition
(It doesn't matter, though)

Steps to reproduce the problem:
* Set up a GitHub repo for a captain app
* Create 2 captain apps with different domains
* Set up webhooks on pushes to master for both
* 1 App will update, the other won't.

Captain should queue builds for different captain apps, and also not return 200 when the webhook was not successful.

**Comment by chromonav** [comment]
This problem is particularly a headache for mono-repos. Because of this captain does not initiate build for second app.

**Comment by githubsaturn** [comment]
Done. This feature will be available in the next release. For now, it's available on edge image:
https://caprover.com/docs/troubleshooting.html#how-to-use-the-edge-version

**Comment by koolamusic** [comment]
I am late to this party 😢 Is it possible to switch versions in a running VM or am I stuck with my version of caprover?

**Comment by stefan52a** [comment]
In the current version (as of this date), we are experiencing the same issue with deployments using GitHub Actions to deploy from one repository to two applications in CapRover.

**Steps to Reproduce:**
	1.	Set up GitHub Actions to deploy from a single repository to two applications in CapRover.
	2.	Trigger a deployment workflow.
	3.	Observe the outcome of the deployments.

**Actual Behavior:**
Approximately 1 out of 3 times, only the first application’s deployment succeeds. The deployment for the second application either fails with statuscode 429:

![CleanShot 2025-01-14 at 22 43 21@2x](https://github.com/user-attachments/assets/9c40ed2a-17b9-4706-aacd-701bc2e35f9b)

**Expected Behavior:**
Both applications should deploy successfully. When a request to deploy one app is made while another is deploying, the second deployment request should not be ignored. Instead, it should always be queued for execution by CapRover.

**Comment by githubsaturn** [comment]
@stefan52a 

429 is expected and working by design. All it means is that there are two POSTS requests accessing the write API at the same time - in this case, you're uploading two "tar" files at the same time and because this process takes a long time, it is not surprising that you see 429 error. There are two solutions that you can choose:

1- Deploy application sequentially

2- A MUCH better approach is to build the image on Github and just push the image name to CapRover. 

https://github.com/caprover/deploy-from-github?tab=readme-ov-file#example-1---deploy-using-image
