### ISSUE TITLE
[Feature Request] Deploy from Github/Bitbucket/Gitlab using SSH

### ISSUE THREAD

**Issue by gabrielgradinaru** [caprover/caprover#342]
First of all let me say this is a great and useful project.
I have a small suggestion to make regarding deployment from Github/Bitbucket/Gitlab.

I don't feel comfortable having my private repo password in cleartext.
So I would like to have the option to deploy from a git repo using SSH instead of HTTPS.

**Comment by githubsaturn** [comment]
What makes you think that entering your "private" SSH key is a safer option? It's not.

It's a common misconception that just because it's an SSH key, it's safer. But keep in mind that in order for git clone to work with SSH, your "private" SSH key will have to be stored on the server. This is a really bad idea!

If you store the password, even if the server is compromised, you can change the password. Changing SSH keys, on the other hand, is a more elaborate tasks, compared to changing password.

Even when you store password for git clone, the password is sent via HTTPS, which uses SSL tunnel. The same technology that encrypts SSH. Therefore, your password transmission is safe.


Last but not least, if you are concerned about security, and you should be, a good common practice is to create service account for your git repo. Service accounts are accounts that have limited access. In your case, you can create a account on Github/Bitbucket/Gitlab and give them read only permission to your repo. Then use that account in your automated deployment via git on CaptainDuckDuck.

**Comment by gabrielgradinaru** [comment]
I should add some clarifications:
- There is no need to change a compromised SSH key as long as you have different keys for each machine. You can just delete the compromised one from Github/Bitbucket/Gitlab
- I'm not saying that a SSH key is a safer option than a password. It just feels wrong to have it in clear text in the UI, anyone passing by the monitor could see it. I think a  "Show password" button would fix this.
- Thanks for the service account idea. I did not think of this

**Comment by fracet** [comment]
Sorry for re-opening this discussion. There is another reason to allow GIT access via SSH.

At least on Bitbucket, you have the possibility of adding read-only access using SSH (see https://confluence.atlassian.com/bitbucket/access-keys-294486051.html). This allows programmatic access to the repo without the need to add an additional user to the account (which might incur an extra charge if you already have a few people working on the repo).

**Comment by ngoyal16** [comment]
not only Bitbucket/ gitlab also have that option

**Comment by ngoyal16** [comment]
by using SSH it is safer than the password.. because using password your whole profile gets compromised. but if Read only ssh key is compromised then only the repos which have access of it get compromised...

there is one more thought... generally, peoples are using the same password for most the websites... so that is another risk of the password leak.

**Comment by gnuns** [comment]
With GitLab's [Deploy Tokens](https://docs.gitlab.com/ee/user/project/deploy_tokens/) feature you can generate repository-specific credentials with read-only access and avoid these account security issues. 
Both [Github](https://github.blog/2015-06-16-read-only-deploy-keys/) and [Bitbucket](https://confluence.atlassian.com/bitbucket/access-keys-294486051.html) offer a similar feature, but only with SSH Keys. So, since one can generate new SSH credentials for each repository as needed, I think this _Feature Request_ is a must-have.

**Comment by githubsaturn** [comment]
Implemented in v1.4.0
