### ISSUE TITLE
How to do backup database in order to move to a new server?

### ISSUE THREAD

**Issue by NishidaRyu416** [caprover/caprover#372]
Even though I have looked for issues about the backup of database, I couldn’t find them.
So how can we exactly do backup a database?
Thanks

**Comment by githubsaturn** [comment]
There is no universal method of backup that works for all databases. Each database has its own backup method. We cannot have a generic tool for creating backup that works with all databases.

You need to find the proper tools for the database that you're interested in. You can do this using an appropriate software. This is the process:

- Expose the appropriate port of the DB such that you can access it from your local machine. See (https://caprover.com/docs/one-click-apps.html#connecting-remotely)
- Find a desktop client for your database.
- Connect to your database using username and password of the database, and use the IP address of the server, then use the exposed port (host port) that you mapped.
- Download/backup data

Then after you set up the new server, do the exact same thing, but in the last step, instead of backup, use "restore" or "import" or similar option




For example, MySQL:

Desktop clients:
https://www.eversql.com/top-5-mysql-gui-tools-for-windows/

Port mapping:
Map port 4000 of host (or any other port) to port 3306 (the default port of MySQL: https://stackoverflow.com/a/3736420


Use these values when connecting to your MySQL:
server: IP-ADDRESS-OF-CAPROVER
port: 4000
user: root
password: your-root-password-in-app-config-on-web-dashboard



Other databases have other desktop clients and different ports.



Hope this answers your question.

**Comment by NishidaRyu416** [comment]
Thanks for giving me a pretty detailed answer.
That really answered my question!
