### ISSUE TITLE
High Disk Write usage after enabling HTTPS

### ISSUE THREAD

**Issue by suphero** [caprover/caprover#389]
What is the problem?
I'm getting continuously high Disk Write usage after enabling HTTPS. Average usage is above 1 MB/s.

Steps to reproduce the problem:
- Create CapRover Droplet on digitalocean.com
- Update Domain to *.my-root.example.com
- Enable HTTPS
- Go To https://captain.my-root.example.com
- Check Droplet -> Graphs -> Disk I/O on digitalocean.com

Answers to the following questions where applicable:
- OS and version: Ubuntu CapRover 1.3.0 on 18.04
- RAM: 1 GB

Found method for the fix:
Running "service apparmor teardown" shell script on remote machine

<img width="817" alt="Screen Shot 2019-03-20 at 01 08 54" src="https://user-images.githubusercontent.com/846531/54645726-e39c9c00-4aad-11e9-9502-7ff9a727a02f.png">
<img width="60" alt="Screen Shot 2019-03-20 at 01 18 47" src="https://user-images.githubusercontent.com/846531/54645793-278fa100-4aae-11e9-90fd-cdac80922415.png">

**Comment by githubsaturn** [comment]
Thanks for reporting this.

- Are you sure this is only caused when you enable https? My guess is it might be due to NetData. Have you enabled NetData around the same time?
- I believe it's a Docker issue, see this: https://github.com/moby/moby/issues/7276
- Run `journalctl --since "1 hour ago"` and see if your logs are filled with:
```
apparmor="DENIED" operation="ptrace" profile="docker-default"
```
- Finally, 1 MB/sec is not too worrying, but if you're running low on disk, you can turn off NetData.
