### ISSUE TITLE
[Deployment Issue]

### ISSUE THREAD

**Issue by AlvaroMtz** [caprover/caprover#401]
**IMPORTANT:** DO NOT POST issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
I am trying to deploy a wordpress on a one-click installation, it does not give any error, but nothing happens, I do not understand very well what steps I should follow

If applicable, content of `captain-definition` file:

{
    "schemaVersion": 2,
    "dockerfilePath" : "./Dockerfile"
}

Dockerfile:

FROM wordpress:latest
COPY . /var/www/html

My local wp is on the same path than the captain-definition file

Answers to the following questions where applicable:
- Your OS and version? Ubuntu 16.04
- RAM? 8Gb

**Comment by githubsaturn** [comment]
One click apps do not require you to enter `captain-definition`. Steps for WordPress one click app deploymenT:
- Login to web dashboard
- Go to APPS
- Click on One-Click App button
- Select WordPress
- Enter MySQL password and etc
- Click on deploy
- Wait until the process is done.

Can you please let me know how you are using captain-definition in this flow?

Also, what do you mean by this?
> it does not give any error, but nothing happens,

**Comment by AlvaroMtz** [comment]
Sorry, I'm using google translate. First, thanks for answering.

What I'm trying to do is a Continuous Deployment pipeline with wp. I deploy the one-click application, and, on this container (wp, not mysql), make the cd pipeline.

So, when I do the captain deploy with the captain-definition above, nothing happens, all Ok, but the container files are not updated.

**Comment by githubsaturn** [comment]
I understand now. You can't do continuous deployment with WordPress, because WordPress is an application where upon the initial deploy all data is copied over to a directory on the host (it's called volume). Any subsequent deploy has no effects.

This is not specific to CapRover. It's basically how wordpress works. Imagine this case:
- You create a wordpress one-click app
- You log in and you setup your wordpress blog
- You upload a few photos to your blog
- You deploy your local deployment to server and all your uploaded images are gone.

This is why WordPress uses volumes and that's the reason that you cannot use Continuous Deployment with WordPress. However, if that's really what you want. You can remove the volume and use WordPress without volume. To do so:
- Deploy WordPress one-click app
- Go to Apps > WordPress > App Config
- Delete the volume `/var/www/html` and click on SAVE & UPDATE

If you do this, you can deploy your local deployment. However, the changes that you make to your deployed version of WordPress are not persistent. They will get reverted to the last deployed version everytime you deploy a new version or everytime the server restarts. It can also cause inconsistency for your DB.

In general, continuous deployment for WordPress is extremely complicated and it's not recommended.

**Comment by AlvaroMtz** [comment]
I had an idea, I'm going to save the media data in an S3 bucket, so it just changes the code, not the files. I think it can work.
