### ISSUE TITLE
[Deployment Issue] How to pull from private registry

### ISSUE THREAD

**Issue by iamrommel** [caprover/caprover#462]
What is the problem?
There is always access denied issue when deploying from my private registry on gitlab is there a way to fix that

Steps to reproduce the problem:
- Go to the deployment method and set the deployment method as dockerfile and pull from private registry that needs login credentials

NOTE:
Where is the place to setup the login credentials, take look at this images fro more info

![image](https://user-images.githubusercontent.com/177265/61396293-f9a25800-a8f9-11e9-9b41-ca85626592e9.png)

![image](https://user-images.githubusercontent.com/177265/61396305-feffa280-a8f9-11e9-8a49-55aafee6b376.png)

**Comment by ComputerCarl** [comment]
I am having a similar issue except I am using Gitea.

![image](https://user-images.githubusercontent.com/29293242/61544003-83dddf80-aa12-11e9-8f6b-88943ef8b4c5.png)

![image](https://user-images.githubusercontent.com/29293242/61544570-bf2cde00-aa13-11e9-97cf-ecf67f347914.png)

```
------------------------- Fri Jul 19 2019 14:56:02 GMT+0000 (Coordinated Universal Time)
Build started for live-helper-chat
Build has failed!
---------------------- Deploy failed!
Error: Cloning into '/captain/temp/image_raw/live-helper-chat/1/source_files'...
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,password).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.
```

If I use my Git username and password, I am able to successfully deploy from the repo.

**Comment by githubsaturn** [comment]
These are two separate issues.

@iamrommel 

Your case is private Docker Registry. In order to pull Docker images from a private registry, you have to add your private registry credentials. Go to CLUSTER > ADD REMOTE REGISTRY and enter your docker registry credentials.


@ComputerCarl 

You're trying to pull from a git repo which you should be able to. The problem is that you're using your public key. You should be using your private key which starts with `-----BEGIN RSA PRIVATE KEY-----`. If you use this private key, you should be able to pull from your git.

**Comment by ComputerCarl** [comment]
Thanks once again @githubsaturn for your help and the awesome platform.
