### ISSUE TITLE
Deploying apps with wildcard domain

### ISSUE THREAD

**Issue by reimo** [caprover/caprover#470]
Hi 
Deployed  a multi tenant app but the system does not accept *.domain.com as custom domain

What can I do ?

**Comment by githubsaturn** [comment]
> the system does not accept *.domain.com as custom domain

This is intentional because otherwise, you could add a custom domain that might be in conflict with another app on the same CapRover instance. For example by default if you have `app1`, it's available as `app1.domain.com` and if you add `app2.domain.com` as a custom domain, it's in conflict with another potential app named `app2`.

Make sure to use a deeper root domain as explained in "best practices", link below
Read this: https://caprover.com/docs/best-practices.html#hidden-root-domain

**Comment by iammerus** [comment]
I have a similar issue.

I have a multitenant app, residing at `x.rootdomain.tld`.  I want connect a domain `myapp.tld`, which is only for this app. However, this app requires, `myapp.tld` and `*.myapp.tld` to be mapped to it. 

Trying to find a workaround for getting this to work.

**Comment by githubsaturn** [comment]
If you don't care about SSL, you can manually edit nginx config and do whatever you want. Go to your app > EDIT NGINX . Then find this line:
```
server_name  <%-s.publicDomain%>;
```
and replace it with:
```
server_name *.myapp.tld;
```

But if you want SSL you cannot do wild card
