### ISSUE TITLE
[Feature request] Two factor authentication

### ISSUE THREAD

**Issue by BamButz** [caprover/caprover#493]
**Is your feature request related to a problem? Please describe.**
Currently there is only one authentication factor (password) this could be easily compromised and should be secured through an additional factor.

**Describe the solution you'd like**
I would like to have an additional authentication factor like an TOTP Mobile Authenticator

**Additional context**
From #177:
> Can't do that. It requires a dependency on a third party usually paid & non-opensource system.

I think that's not true.
A 2FA can be implemented via TOTP the algorithm is open (https://tools.ietf.org/html/rfc6238) and there are also many free apps. (and of course closed source like Microsoft Authenticator)

I would be very pleased if we received an additional factor for authentication.

**Comment by githubsaturn** [comment]
Thanks @BamButz 
I had previously only considered SMS, call, and email, which are all paid services. But this TOTP solution seems viable.

Do you know of any open source framework that has adopted such approach without relying on paid services?

**Comment by solomon23** [comment]
Looks like https://github.com/bkimminich/juice-shop uses https://github.com/yeojz/otplib which seems pretty popular

**Comment by piscis** [comment]
@githubsaturn did a bit of research. I think one OSS lib that implements TOTP for NodeJS + Browser and is still maintain is: https://github.com/yeojz/otplib 

Browser Demo: https://otplib.yeojz.com/
License is: MIT

Other stuff that came up in the research:

- https://www.thepolyglotdeveloper.com/2017/05/implement-2fa-time-based-one-time-passwords-node-js-api/
- https://github.com/speakeasyjs/speakeasy (not maintained)
- https://www.thepolyglotdeveloper.com/2019/03/two-factor-authentication-totp-using-nodejs-speakeasy/
- https://github.com/guyht/notp (not maintained)
- http://www.passportjs.org/packages/passport-totp/ (probably not maintained)
- http://www.passportjs.org/packages/passport-2fa-totp/ (probably not maintained)
- https://www.nexmo.com/blog/2017/04/11/implement-two-factor-authentication-2fa-web-apps-node-js-dr (2FA with SMS provider nexmo)

**Comment by mxdpeep** [comment]
> Thanks @BamButz
> I had previously only considered SMS, call, and email, which are all paid services. But this TOTP solution seems viable.
> 
> Do you know of any open source framework that has adopted such approach without relying on paid services?

please implement optional **Google Authenticator**
https://github.com/google/google-authenticator

Google Authenticator is a software-based authenticator that implements two-step verification services using the Time-based One-time Password Algorithm and HMAC-based One-time Password algorithm, for authenticating users of mobile applications by Google.

**Comment by BamButz** [comment]
Google Authenticator is based on RFC6238 with the restriction that the secret is a base32 hash.
They do this to avoid the danger of confusion with the characters O and I.
I think it is a good idea to follow google in this decision and use base32 hashes as secret.

All this should work with the otplib referenced by @piscis.
More details about this topic can be found on there site (https://github.com/yeojz/otplib#seed--secret-length)

**Comment by rene-s** [comment]
Great software. :) However the missing 2FA is preventing me from using it productively yet. I would consider TOTP the bare minimum for 2FA. U2F/FIDO/FIDO2 or better yet Webauthn (like Github provides!) would be an even better choice.

Technically SMS/email count as second factors, yes, but the gain in security is rather low.

Implementing Webauthn would provide a better a far better cost-benefit-ratio in my opinion.

A small donation is on the way.

**Comment by githubsaturn** [comment]
I think I have to write a more proper answer to this. Here it goes...

Implementing 2FA for CapRover isn't as trivial as it may sound. CapRover uses password for web login, and it uses password for deployments from CI/CD platforms, and etc. Implementing a 2FA will essentially break the functionality of CI/CD systems which are an integral part of CapRover ecosystem. An alternative would be to introduce auth-tokens which are similar to passwords, except they don't require 2FA. At this point, we are back to square one as we have a fully functional auth-tokens that can do any actions and they don't require 2FA.

Another advanced approach is to create scoped auth tokens. This approach may work, but again, due to the very nature of CapRover is so complex that it makes it practically impossible to implement. Even if you scope a token to a particular app, the app can bind itself to docker socket and perform any "malicious" action. Trying to be smart and "prevent" this clever attacks is much more complex that you can imagine. it actually serves to the loss of the user as it creates a fake sense of security where in fact everything is hanging off a thin string. That's why even mid sized companies avoid using fine scoped auth tokens. DigitalOcean, as a mid/large scale company for example, uses 2 levels of scope of each token, read or write. Having ability to write, is basically having ability to create one tiny server and destroying all of your other servers.

Now, lets talk about the actual deal here, security! 2FA adds security in two cases:
- Brute force.
- You use the same password everywhere.

CapRover has tough guards when it comes to brute force. You can test it by entering your password wrong for a few times, you'll be blocked for 30 seconds. Practically, brute forcing a CapRover instance password is impossible. 

With regards to the second case, it's simply your responsibility to choose a relatively long, unique password.

Other than these two cases AFAIK, 2FA is just "sense of security", not actual security.

Last but not least, if you really really want an extra layer of security, you can even limit the IP addresses that can talk to your CapRover API. You can do so by modifying nginx settings from CapRover dashboard > Settings > Nginx, then look for `CapRover Config Location in nginx container: /etc/nginx/conf.d/captain-root.conf`


Hope this answers the actual security concerns.

**Comment by BamButz** [comment]
Hello, first of all thank you for your detailed answer.

With regard to security, it is also about man-in-the-middle / keylogger vectors, in which way access would only be valid for the period of time stored in the TOTP, which is usually 30 seconds.

As far as the CI / CD is concerned, I think you are talking about deployments via CLI, is that correct?

**Comment by rene-s** [comment]
I would be fine with a security level that Heroku already provides, except for the SMS option. For Heroku, implementing SMS as 2FA makes sense I guess, I consider the cost-benefit ratio to be good for them. Not for CapRover or a company running a CapRover instance though.

**Comment by githubsaturn** [comment]
> As far as the CI / CD is concerned, I think you are talking about deployments via CLI, is that correct?

Yes.

**Comment by sneak** [comment]
I use CapRover only via the web interface, and I think supporting U2F via WebAuthn is valuable.

https://webauthn.io/

**Comment by BamButz** [comment]
I agree with @githubsaturn, theoretically the existing mechanisms should be sufficient and I would also have no solution regarding the CLI.

Personally, I would only use the 2FA to use a password that I can memorize, but since this is too complex to implement, I still live with my password manager.

Perhaps if someone finds a solution to the CLI problem, we could evaluate this topic again.

@githubsaturn I leave it up to you whether you want to leave this issue open or close until then.

**Comment by githubsaturn** [comment]
If you are only using CLI and webgui locally from your own device and you don't need a random 3rd party machine (CI/CD) to access your CapRover instance, the most secure method is:
- Install a VPN sever either on the same host as CapRover or another host with static IP (OpenVPN or PiVPN are pretty easy)
- Impose restriction on nginx config such that it only allows the connection to the api to be made from a certain IP and deny everything else.

This makes your server as secure as a strong SSH connection can get.

**Comment by umaar** [comment]
Brute force protection is a step in the right direction, but passwords can leak in various ways, brute force isn't the only attack vector. In can even be done when using the CLI, e.g. see how Heroku do it: https://devcenter.heroku.com/articles/two-factor-authentication#using-two-factor-authentication-on-the-command-line

Regarding two factor auth from a CI tool, this is definitely possible: https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth 

The [NCSC](https://www.ncsc.gov.uk/guidance/multi-factor-authentication-online-services) has excellent reminders on the value of 2fa, please do consider it.

It's technically possible to implement 2fa on the web dashboard, the CLI tool, and during integration of CI services. Is the concern now the engineering effort?

**Comment by githubsaturn** [comment]
Thank you @umaar for the context. I am not sure I follow exactly what's the CI tool approach that fastlane is following. The only method that could potentially work with CapRover is to have your HMAC key sitting on the CI server so that the CI server can send the OTP generate by HMAC key alongside the password to the CapRover machine. Since on every restart CapRover changes its token salt, you can't authenticate once and get a never dying token. 

Regarding attack vectors, when you store your HMAC key alongside with your password on your CI machine. There is no real two factor auth. It's once factor split into two pieces.

**Comment by sneak** [comment]
I strongly recommend against the approach of complicating auth clients (like CI) in this way.

The main reasons for using 2FA are to mitigate password reuse/phishing/credential stealing.  In the case of API clients like CI, using strong random tokens is entirely sufficient. There is no second factor needed or recommended for machine-to-machine authentication. 2FA is for human logins.

I think adding U2F to the admin panel would be nice, but isn’t really important from a security standpoint and should be assigned a low-ish priority. For logging into CapRover you should be using a password-manager-stored long random password (which CR prevents bruteforcing via rate limits), and that will save you from phishing or credential reuse. Anyone worried about the security afforded there can of course modify the nginx security panel listener to allow access only from certain IPs.

**Comment by sneak** [comment]
Note that if you do go for 2FA instead of just a 20 char min password length, TOTP codes can be phished in the exact same manner as passwords, so their use is discouraged in favor of U2F for high security applications (such as the admin panel for a bunch of services).

**Comment by s-kris** [comment]
What if 2FA can be an optional feature for those who really need it? 

Simple scenario:
Caprover can ask for smtp details and 2FA codes can be sent via email. 

Complex scenario:
Caprover will have different modules for popular email/sms services. Users can give their api keys for sending 2FA codes.

**Comment by BamButz** [comment]
> Note that if you do go for 2FA instead of just a 20 char min password length or something that would achieve much the same end, TOTP codes can be phished in the exact same manner as passwords, so their benefit is significantly limited relative to their inconvenience, and their use is discouraged in favor of U2F for high security applications (such as the admin panel for a bunch of services).

But they are only valid for some minutes so the potential attacker would not have constant access. (Provided that he receives the data once and uses it directly)

**Comment by sneak** [comment]
@s-kris SMS 2FA is strongly discouraged. Email 2FA isn’t much better.

**Comment by s-kris** [comment]
Okay, no 100% safe. But could make caprover safer. We can have more probability in convincing team to use it in production.

**Comment by Misly16** [comment]
any updates on including this?

**Comment by githubsaturn** [comment]
**Please read the thread before adding a comment**. The current design of authentication for CapRover is secure enough that 2FA does NOT make the platform any more secure that what it is now. 2FA will be only a "sense of more security" not really more security.

**Comment by sneak** [comment]
This is a false statement. Someone able to steal the CapRover password (such as in the case where a password is reused and is compromised elsewhere) can use that to log in to CapRover.

In the case of 2FA, where the password is stolen but the 2FA device is not, the attacker in possession of the password would not gain access.

**Comment by githubsaturn** [comment]
> This is a false statement. Someone able to steal the CapRover password (such as in the case where a password is reused and is compromised elsewhere) can use that to log in to CapRover.

It's not if you don't reuse your password elsewhere. If you only use a unique password for your CapRover instance. The attack verctor for stealing password is same as stealing your secret hashkey.

**Comment by sneak** [comment]
It seems to me that you have a few fundamental misunderstandings of how to design auth systems @githubsaturn, based on statements in this thread. 

As a CR user and security/authentication expert, I offer you free consulting on this matter, if you’d like it.  There are straightforward ways of reworking the CR auth. system that will make it safer and easier (and more secure) for users.

**Comment by githubsaturn** [comment]
Happy to jump on a chat with you. Feel free to message me on caprover.slack.com

**Comment by githubsaturn** [comment]
Or fell free to email me if you have any suggestions. Until then, I'll lock this thread to avoid extra heat.

**Comment by githubsaturn** [comment]
Email alerts Available as of 1.11+ as part of the pro plan.
