### ISSUE TITLE
[Feature request] Specify the user and port when attaching new nodes to a cluster

### ISSUE THREAD

**Issue by piscis** [caprover/caprover#497]
**Is your feature request related to a problem? Please describe.**
I normally disable root login and change the SSH Port of my servers. I then use a dedicated user account that has admin rights via `sudo` to do administrative work. 

At the moment it seems that it's not possible to configure a port or user when attaching a new node to the cluster therefore I have to permit root login on all cluster nodes and change my ssh ports to 22

**Describe the solution you'd like**
I would like a way to specify a user and ssh port (both optional) for CapRover to connect to a new node. If the user is not `root` it prefixes all commands with `sudo` and execute it.

It would then be the Administrators responsibility that the specified user can execute the necessary commands for CapRover to bootstrap a new Node into the cluster.

**Describe alternatives you've considered**
- PermitRootLogin via SSH + SSH KEY Only
- Leave the SSH Port at 22

Well both alternatives are valid but I really would like a way to specify this settings to integrate CapRover and make it a bit harder for potential attackers to gain access to my servers.

**Additional context**
On some AWS ubuntu images users are not permitted to login by default instead they have to use the `ubuntu` account as a gatekeeper. So I'm not the only one doing this.

**Comment by githubsaturn** [comment]
You can always use plain docker commands for non-standard cases:


```
docker swarm join-token worker # run on main node
docker swarm join --token YOURTOKEN HOST:IP # on new node
```

**Comment by piscis** [comment]
Okay thank you, this will certainly work and is a good workaround although I did not test it. Anyway I was hoping that at some point caprover would support a custom port and none root User configuration via web Frontend. it’s good to know there is a way to accomplish it. Thanks a lot

**Comment by githubsaturn** [comment]
Hi Alex, that's intentional. One of the CapRover's major design philosophy was to address 95%+ of cases easily while allowing the more customization to be done manually if anyone needs to do so. This has helped us create a non cluttered UI with simple and easy to work with UI.

When you look at the bigger picture, not just this minor customization, adding every special case and customization to the UI makes the UI complex.

**Comment by j-wil** [comment]
@githubsaturn I'm running into this as well while trying to add azure VMs to my cluster. I love the kiss philosophy but not allowing the specification of an account name for ssh may fall outside of serving 95% of use cases. Disallowing root is a very common practice.  

Azure does not allow any linux VMs to allow root as the username 
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/faq

**Comment by githubsaturn** [comment]
What username they use to run root commands then? Do you have to use `sudo` to run root commands then?

**Comment by j-wil** [comment]
Configure the vm with the username 'xyz' and then create a user group called docker and assign user xyz to that group. 

Per dockers recommendation in their [docs](https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user)

I believe the premise is to provide some obscurity for automated remote exploit tools that target common user names.

**Comment by githubsaturn** [comment]
Fair enough. I wasn't aware that Azure completely blocks `root` as username. For now, you can use the approach described here: https://github.com/caprover/caprover/issues/497#issuecomment-532230512

With regards to non-root accounts and using `sudo`, I don't think we can support this on the GUI, because running `sudo command` may require an interactive session for the user to enter their password.

On the other hand, port, and remote username should be doable. I'll open an issue to support these two
