### ISSUE TITLE
Additional config files

### ISSUE THREAD

**Issue by lgraubner** [caprover/caprover#508]
**Is your feature request related to a problem? Please describe.**

I have a JSON configuration file (for a Google service) which needs to be present in the docker container to be able to connect. As far as I understand it's only possible to add env variables for this kind of stuff. Is it possible to add files I *don`t* want in version control to be added to the container?

**Describe the solution you'd like**

Specifying additional files in `captain-definition` would be nice.

**Comment by functino** [comment]
Hi @lgraubner, 
I had similar problems. I solved it by using the feature to directly deploy a .tar-file like described here: https://caprover.com/docs/recipe-deploy-create-react-app.html#create-the-tar-file

Instead of deploying whatever is checked in into version control you can decide yourself what you want to add to your .tar-archive.

**Comment by lgraubner** [comment]
Thats not ideal, but thanks for letting me know @functino!

**Comment by otaviobps** [comment]
I have the exact same problem. By now I created a persistent app and moved the files to the blinded directory. However, I want to clusterize my app and it's not possible when you have a persistent app. Could you solve this problem @lgraubner ?

**Comment by lgraubner** [comment]
@otaviobps Unfortunately not. But to be honest I decided to go for Dokku and didn't dig into this issue much further.

**Comment by githubsaturn** [comment]
For what it worth, the method [mentioned above](https://github.com/caprover/caprover/issues/508#issuecomment-534708907) is very solid way of doing this.

More detail:

By default, CapRover uses git to create the "tar" version of your repository before sending it to the server. In most cases this is what you want. However, if you want to include files that are not version controlled, you can use another "tar" method, i.e., just tar command.

So instead of 
```
caprover deploy 
```

you do:
```
tar -cvf ./deploy.tar --exclude='.git' ./*
caprover deploy -t ./deploy.tar
```


Of course, you don't want to type all this every time, just create a `deploy.sh` file and dump the two lines in that file.

**Comment by otaviobps** [comment]
Hi @githubsaturn I'd like to keep the automatic build using git. It's very practical to merge a branch to master and caprover build it automatically. It would be great if this task could be accomplished maintaining the automatic build

**Comment by githubsaturn** [comment]
Well, in that case, there is no other option. Including files that are not version controlled aren't doable if you want to stick with automatic git deployment. This is the case with Heroku, Gitlab CI/CD and other services.

There are a few alternative solutions that you can use:

Solution 1)
- Include the files in your version control system. However, have them encrypted and keep the encryption key as an environmental variable. For example:
- Have a `firebase.keys.production` and `firebase.keys.staging` and etc. 
- Then in your environmental variables have two fields: `key_file_name` and `encryption_key`
- During start-up of your app, you can decrypt the file and use it.


Solution 2) This is what I personally do for firebase keys:
If your file isn't too big (less than a few kb), just convert your file to base64 and save it as an environmental variable. During app start-up, just load the environmental variable and decode it to base 64.

For firebase keys, you can directly pass the content to firebase SDK. However, if you need to, you can save the content to a file.


-------------------


I am happy to hear if there is any alternative solutions that we can implement in CapRover.

**Comment by ProfessorLogout** [comment]
Hi everyone,

@otaviobps 
I have a similar setup with files just in production. Solved it by substituting git „automatic“ deploy with a bit of GitLab CICD.

@githubsaturn 
A system solving a similar issue I really enjoy using has been implemented by gitlab.
Maybe this is a idea for CapRover as well.
https://docs.gitlab.com/ee/ci/variables/#file-type

**Comment by lgraubner** [comment]
@githubsaturn Solution 2 sounds very nice. Will try that as it is also useful with dokku.
