### ISSUE TITLE
[Deployment Issue] How to copy a file from host to docker container?

### ISSUE THREAD

**Issue by otaviobps** [caprover/caprover#529]
I'm trying to deploy an app with NO persistent data. I have some `cert` files and some `macaroon` files that I don't want to send to Github, because they shouldn't be exposed. I created an app with persistent data and could bind a volume to the docker container, which worked fine, however this is not ideal, since I don't want to map a volume, just copy some files to the container.

I tried, then, to create an app with no persistent data, and changed my `captain-definition` file to this:

```
 {
  "schemaVersion": 2,
  "dockerfileLines": [
                        "FROM node:12.6.0-alpine",
                        "RUN mkdir -p /usr/src/app",
                        "ADD /root/LND /usr/src/app",
                        "WORKDIR /usr/src/app",
                        "COPY ./package.json /usr/src/app/",
                        "RUN npm install && npm cache clean --force",
                        "COPY ./ /usr/src/app",
                        "ENV NODE_ENV production",
                        "ENV PORT 80",
                        "EXPOSE 80",
                        "CMD [ \"npm\", \"start\" ]"
                    ]
 }
```

What I tried to do was to `ADD` the files in the `/root/LND` directory to `/usr/src/app`. This should work, however won't work, because as I can see, caprover creates an intermediary container and it can't see the host directory:

```
{"message":"ADD failed: stat /var/lib/docker/tmp/docker-builder208822321/root/LND: no such file or directory"}
ADD failed: stat /var/lib/docker/tmp/docker-builder208822321/root/LND: no such file or directory
Build has failed!
```

I want to create an app with no persistent data because I want to create a cluster.

What's the best approach to solve this problem?

**Comment by githubsaturn** [comment]
First) your build fails because `ADD /root/LND /usr/src/app` tries to copy the LND directory from the CapRover container, not the host. When the images are being built, the host builder is the CapRover container, not the host.

Second, as mentioned in the other [thread](https://github.com/caprover/caprover/issues/508#issuecomment-548993370), the best way to avoid using git to archive your files.

If you have custom files that need to be added to your container, you need to use custom tar command as mentioned in the other thread. To be exact:

`caprover deploy` is equivalent of 
```
git archive --format tar --output "./deploy.tar" master
caprover deploy -t ./deploy.tar
```


However, because of your requirements, the line `git archive --format tar --output "./deploy.tar" master` doesn't work for you. So instead, replace that line with a custom tar command that suits your need.
