### ISSUE TITLE
Custom SSL without editing the nginx file

### ISSUE THREAD

**Issue by ElectricReality** [caprover/caprover#567]
**Is your feature request related to a problem? Please describe.**
Applying custom certificates should be easier. And setup should also have custom certificates option instead of lets encrypt only.

**Describe the solution you'd like**
A easier custom certificate panel for the setup and the web application.

**Describe alternatives you've considered**
Edit the nginx manually and fail.

**Additional context**
I’d like to enforce cloudflare’s full(strict) ssl encryption. Doing this shows “nothing here” on the domain.

**Comment by githubsaturn** [comment]
This goes against CapRover design principles. CapRover is designed, and will remain, a generic tool to address standard deployment while keeping the options open for further customization if user needs to. This decision is made to ensure that the scope of the project remains in a manageable state. Otherwise the number of custom rules that are brought into the CapRover ecosystem gets out of control. There are hundreds, if not thousands of customized actions that can be applied to nginx and docker. We address the cases that are being used in 99% of the cases.
