### ISSUE TITLE
[Deployment Issue] [Warning] One or more build-args [MYSQL_ROOT_PASSWORD] were not consumed

### ISSUE THREAD

**Issue by locvfx** [caprover/caprover#608]
What is the problem?
I can't set Mysql Root Password at deployment

Steps to reproduce the problem:
- Set Variable : MYSQL_ROOT_PASSWORD
- Deploy using official Image from Docker hub
FROM mariadb:latest

Answers to the following questions if applicable:
- Your OS and version? Centos 7
- RAM? 1GB

Error log:
------------------------- Wed Mar 04 2020 15:56:42 GMT+0000 (Coordinated Universal Time)
Build started for test-mariadb
Step 1/1 : from mariadb:latest

---> 2f11cf2ec189
[Warning] One or more build-args [MYSQL_ROOT_PASSWORD] were not consumed
Successfully built 2f11cf2ec189
Successfully tagged img-captain-test-mariadb:latest
Build has finished successfully!

**Comment by locvfx** [comment]
I searched on internet and I found this:
Common Error Messages
One or more build-args [XXX] were not consumed

If you pass a build argument to an image at build time, but do not have a corresponding ARG instruction in the Dockerfile, Docker (versions < 1.13) will fail the image build.

As of 1.13, unused build args will not fail the build, but will generate a warning message.

https://documentation.codeship.com/pro/builds-and-configuration/build-arguments/

However, I don't know how to fix it in Caprover. Can someone help, please?

**Comment by githubsaturn** [comment]
`One or more build-args [XXX] were not consumed` is not important at all. CapRover by default passes all the env vars to build args. This means that you can optionally use them as build args, but if you don't, it's okay too, they will simply be ignored and that's why you see that message.


With regards to MariaDB - please note that you cannot change the password after the first deployment:
https://github.com/docker-library/mariadb/blob/17fbf28e55c357c52d5025c50d65f2ab2ab508e2/10.4/docker-entrypoint.sh#L94-L99

Even if you delete your container, but you use the same volume with pre-existing database, your root password gets ignored.



To deploy MariaDB - simply use the one click app! MariaDB is available as a one-click app.
