### ISSUE TITLE
Cannot install Redash

### ISSUE THREAD

**Issue by KonradHolubek** [caprover/caprover#630]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
I'm trying to install Redash directly using image name but it is not working

If applicable, content of `captain-definition` file:
{
  "schemaVersion": 2,
  "imageName": "redash/redash"
}

Steps to reproduce the problem:
Build logs
```
Build started for redash
An explicit image name was provided (redash/redash). Therefore, no build process is needed.
Pulling this image: redash/redash This process might take a few minutes.
Build has finished successfully!

```

App logs
```
2020-03-21T16:23:26.463971773Z /
2020-03-21T16:23:27.250307439Z /
2020-03-21T16:24:04.130622307Z [2020-03-21 16:24:04 +0000] [1] [INFO] Starting gunicorn 19.7.1
2020-03-21T16:24:04.133476516Z [2020-03-21 16:24:04 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
2020-03-21T16:24:04.133701471Z [2020-03-21 16:24:04 +0000] [1] [INFO] Using worker: sync
2020-03-21T16:24:04.146315425Z [2020-03-21 16:24:04 +0000] [9] [INFO] Booting worker with pid: 9
2020-03-21T16:24:04.231469606Z [2020-03-21 16:24:04 +0000] [11] [INFO] Booting worker with pid: 11
2020-03-21T16:24:04.256761609Z [2020-03-21 16:24:04 +0000] [12] [INFO] Booting worker with pid: 12
2020-03-21T16:24:04.272452510Z [2020-03-21 16:24:04 +0000] [13] [INFO] Booting worker with pid: 13

```

On my url, I get a 502 error. 

Is this due to the fact that redash is a docker so basically it is trying to run a docker container inside a docker container ? Indeed, when I tried to install from source file but then I got the error
"Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?"

I've been struggling with this all day and would be very grateful if someone could help :)

Thank you.

**Comment by githubsaturn** [comment]
1) From the logs you posted, seems like redash is running on port `5000`. Navigate to App, go to HTTP tab, and set the `Container HTTP Port` to `5000` and click on Save and Update.

2) From the their [official documentation](https://redash.io/help/open-source/setup#docker), it appears that redash is not a single container application. It's a complex application with multiple service: https://github.com/getredash/setup/blob/master/data/docker-compose.yml

3) In order to deploy this application, you have to understand Docker compose pretty well. Then either use docker-compose directly or convert docker-compose to a one-click apps. CapRover one click apps are essentially applications that require multiple services (similar to redash)

4) This question is Docker specific, or redash specific, I suggest you post your question on StackOverflow or Redash's github.
