### ISSUE TITLE
Container stops after each deploy

### ISSUE THREAD

**Issue by KonradHolubek** [caprover/caprover#632]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
After each deploy my app either works for couple of minutes and then the container stop or the container simply does not start at all. This, despite my app logs showing
```
2020-03-23T16:44:40.811896340Z [Mon Mar 23 16:44:40 2020] PHP 7.4.3 Development Server (http://[::]:80) started
```

I always have to force reload by hitting the "Save & Update" button.

If applicable, content of `captain-definition` file:
```
{
  "schemaVersion": 2,
  "dockerfileLines" :[
                         "FROM php:7.4.3",
                         "RUN apt-get update && apt-get install -y git curl",
                         "RUN mkdir -p /usr/local/bin/ && curl -s -o installer.php \"https://getcomposer.org/installer\" && php installer.php --install-dir=/usr/local/bin --filename=composer && rm -f installer.php",
                         "RUN mkdir -p /var/www/html/dist",
                         "COPY ./dist/ /var/www/html/dist",
                         "COPY ./composer.json /var/www/html",
                         "RUN composer install -d /var/www/html",
                         "COPY ./.env /var/www/html",
                         "CMD [ \"php\", \"-S\", \"[::]:80\", \"-t\", \"/var/www/html/dist\" ]",
                         "EXPOSE 80"
                     ]
 }
```
Please advise.

**Comment by githubsaturn** [comment]
I am not sure what you mean by this:
> After each deploy my app either works for couple of minutes and then the container stop or the container simply does not start at all

What do you mean by not starting at all?

When you deploy a new version of your app, this is what happens:
- CapRover builds a new image for your app based on the new source code.
- CapRover asks Docker to update the service that's running your app to use the new image.
- You can verify this by running `docker service ls`
You will see a row like this:
```
y32f3vecybfv        srv-captain--myapp                    replicated          1/1                 img-captain-myapp:14                     
```

where `img-captain-myapp:14` shows that the currently deployed version is version `14` for example. Does this number get updated for you?

**Comment by KonradHolubek** [comment]
What I meant is that I have a 502 error on my webpage and when I do `sudo docker ps --format "{{.Names}}"` I do not see the related container (that I do not see "srv-captain--myapp"). It's only when I hit the save and update button that I can load my webpage and I see the related container.

**Comment by githubsaturn** [comment]
` 1/1` in `docker service ls` indicates that your service is running 1 instances. Beyond this point, it's purely docker, it's not CapRover. 

To help you troubleshoot the issue, maybe try running `docker service ps srv-captain--prod`

Then copy the entire output, it should be something like this: 

```
:~# docker service ps srv-captain--prod 
ID                  NAME                                        IMAGE               NODE                DESIRED STATE       CURRENT STATE         ERROR                              PORTS
pcsi0imkb093        srv-captain--prod.1       wordpress:4.9       asdf          Running             Running 3 days ago                                       
8kypu5l8wkjo         \_ srv-captain--prod.1   wordpress:4.9       asdf          Shutdown            Failed 3 days ago     "No such container: srv-captai…"   
o3z907iu91q2         \_ srv-captain--prod.1   wordpress:4.9       asdf          Shutdown            Failed 3 days ago     "task: non-zero exit (255)"        
v1lgcdhywqul         \_ srv-captain--prod.1   wordpress:4.9       asdf          Shutdown            Failed 4 weeks ago    "No such container: srv-captai…"   
epbiy6b4kpff         \_ srv-captain--prod.1   wordpress:4.9       asdf          Shutdown            Failed 2 months ago   "No such container: srv-captai…"   
```

**Comment by Brandutchmen** [comment]
+1

**Comment by githubsaturn** [comment]
@Brandutchmen are you able to reproduce the issue. What's your output for `docker service ls` ?

**Comment by Brandutchmen** [comment]
@githubsaturn I am not able to reproduce the exact same issue, but I am getting 502 errors on each deploy for around 10 seconds with apps with persistent data while the seem to boot up. I am trying to figure out how to get it as close to a zero-downtime deployment, but I haven't been successful yet. So overall, I have a slightly different issue, but I am still interested to see how this one resolves.

**Comment by githubsaturn** [comment]
@Brandutchmen 
The issue you're experiencing is different from the original problem that was discussed in this issue. With regards to the downtime you're seeing, please see: https://github.com/caprover/caprover/issues/661#issuecomment-619548552

**Comment by fcosrno** [comment]
The behavior described by OP happened to me in production and I was able to resolve it by reconnecting the worker node. Documenting here for future reference.

In my case, I have a cluster with one manager and one worker. The issue was that if my app went to the worker node on deployment, then the app would not work. It would work when I clicked "Save & Update" because the app would go to the manager node. But if I clicked it again (or deployed) it would go back to not working because the app went back to the worker node. I guess Caprover toggles each deploy/save between nodes in the cluster.

I was able to see in what node my app was deploying by ssh'ing to the manager node and doing `docker service ls` then `docker service ps [ID]` .

My solution was to reconnect the worker node. Before you do that, make sure your ports are open on all nodes (both manager and worker) as per the [Docker Swarm documentation](https://docs.docker.com/engine/swarm/swarm-tutorial/#open-protocols-and-ports-between-the-hosts). 

In Ubuntu the command to open ports looks something like this (find the correct syntax for your Ubuntu version):

```
sudo ufw allow from any to any port 2377 proto tcp
sudo ufw allow from any to any port 7946 proto tcp
sudo ufw allow from any to any port 7946 proto udp
sudo ufw allow from any to any port 4789 proto tcp
```

To remove the worker node, ssh into the worker node and leave the swarm: `docker swarm leave`. Then ssh to the manager node, and remove the node with `docker node ls` followed by `docker node rm node-id`, where the node-id is the inactive worker. 

You should now see the node is not in the cluster in Caprover's Cluster page. 

To reconnect the worker node, grab a" join-token" by running this in the manager node `docker swarm join-token worker`. It will return a command. Copy and paste it into your worker node via ssh. It should look something like this:

```
docker swarm join --token I-am-a-super-long-token IP:PORT
```

By the way, this is just the command line way of connecting nodes, which would be similar to connecting nodes in the Caprover Cluster section. 

You should now see your worker node back in the Caprover Cluster page and hopefully your apps are deploying fine! 

Hope this helps.
