### ISSUE TITLE
Select instances/apps location

### ISSUE THREAD

**Issue by aromero86** [caprover/caprover#634]
Hi guys, I would like to know if it is possible to decide in which machine of my cluster each instance or caprover application goes. The idea arises from this:

- It would be nice to have instances of the same application on different machines (in case a machine falls)
- It would be nice to have Caprover (which manages everything) on ​​a totally separate machine

What do you think? Does my approach make sense? Is this possible with Caprover? Currently I add applications but I don't know what machine they are on or how they are distributed ...

Thanks in advance. Beautifull project 😃

**Comment by githubsaturn** [comment]
Hi @aromero86 

Thanks for your comment. With regards to the location of the apps, if your app has persistent data (mapped volume) it will be locked to a particular node and you can set the node ID in apps settings. Otherwise, you app will float to all nodes available. If you want to lock it to a particular node, you can do so by creating a app with persistent data. You don't have to map any volume to it, just by virtue of selecting Persistent Data when creating the app, you can lock it down to a particular node.

Having said that, if you need more complex placement strategy, you can definitely use the docker's underlying [placement API](https://docs.docker.com/engine/swarm/services/#placement-preferences). Since these are rarely used APIs, CapRover doesn't surface them in the UI. However, you can leverage the [predeploy script](https://caprover.com/docs/pre-deploy-script.html) to use these functionalities if you really need them. But keep in mind that these are complex features and should only be used if you really need them.
