### ISSUE TITLE
Make it easier to execute commands during deployment

### ISSUE THREAD

**Issue by derek-adair** [caprover/caprover#635]
**Is your feature request related to a problem? Please describe.**
I need to be able to _easily_ execute arbitrary shell commands before/after deployment.

**Describe the solution you'd like**
**First -** This would ideally be in version control along with my captain-definition and described in my captain definition... like so...

```
{
  "schemaVersion": 2,
  "pre-deploy": /path/to/script,
  "post-deploy": /path/to/script
}
```

**Second -** The script could be of the current pre-deploy format OR just a simple shell script.  I'd imagine this could be achieved by detecting if its a .js file or .sh and providing some kind of default pre-deploy script to shove it into (like this migration script).
```
if .sh:  #Shove it in a .js pre-deploy script that will execute it
else if .js:  #execute script like it is done now
```
**Describe alternatives you've considered**
- No post-deploy, personally i just need pre-deploy
- No captain-definition, just add shell scripts to the pre-deploy section in the app config.  

**Additional context**
Idea taken from here #423 - i'm aware I can achieve this w/ the current pre-deploy script it would just be very convenient to;
1) Execute shell scripts directly
2) Have these in version control
3) Have a safe and easy way to execute commands pre-deploy... because as the docs state...

> Note that this pre-deploy script, particularly Docker service update object, is complicated. Hence, it is strongly recommended to use this pre-deploy method if you are an expert user.

**Comment by githubsaturn** [comment]
Thanks for the suggestion here. There are a few points here that need to be accounted for:
1)
CapRover runs pre-deploy script for both deployments (image change) and settings changes. Both are technically just a service update. This is necessary as otherwise all settings would be overridden once someone clicks on Save and Update.
For this reason, we cannot/should not put the script in the image name.

2)
Shell scripts are definitely doable, but it's of very low value considering that docker API is only available via a unix socket in CapRover container. Docker CLI commands won't work at all. 


So, to sum up:
> Execute shell scripts directly

You can do so by simply clicking on Save and Update. this will execute the predeploy script.

> Have these in version control

This is not possible because of the flow as described above.

> Have a safe and easy way to execute commands pre-deploy... because as the docs state...

I don't think there will ever be a "safe" way of executing these commands, you can full access to the service and you can do whatever you want with the service object, that's the goal of this script.


In general, I think confusion is due to the nature of the flow as to "when" the predeploy function gets called. It's for any type of service update, whether it's an image update or simply env var update or etc.

**Comment by derek-adair** [comment]
>For this reason, we cannot/should not put the script in the image name.

Its possible there is a miscommunication here.  I'm not 100% sure what you mean by 'put the script in the image name'.  That captain-definition is not complete maybe thats why... A valid one may look like this...

```
{
  "schemaVersion": 2,
  "image": "python",
  // points to a plain shell script OR a pre-deploy.js
  "pre-deploy": /path/to/script
}
```

>Shell scripts are definitely doable, but it's of very low value considering that docker API is only available via a unix socket in CapRover container. Docker CLI commands won't work at all.

I dont need the docker api, i need to be able to run migrations and collect static files.

**Comment by githubsaturn** [comment]
> I'm not 100% sure what you mean by 'put the script in the image name'

Sorry, it was a typo... I meant **we cannot/should not put the script in the image**

> I dont need the docker api, i need to be able to run migrations and collect static files.

In that case, I assume you need to run the shell script inside your own container... But the predeploy scripts run inside the CapRover container. That's why you see `await run(["--migrate-database"]);` in https://github.com/caprover/caprover/issues/423#issuecomment-602449626

So to sum up, if you want to run a script "inside" your container, just check in the script in your code base, and use a similar solution, just make sure that Entrypoint is a shell:

```javascript
var preDeployFunction = async function (captainAppObj, dockerUpdateObject) {
    const DockerApi = require("./built/docker/DockerApi");
    const api = new DockerApi.default();

    const setServiceInstances = async (service, count) => {
        const inspection = await service.inspect();
        const updateObject = { ...inspection.Spec, Mode: { Replicated: { Replicas: count } }, version: inspection.Version.Index };
        await service.update(updateObject);
    };

    const run = async args => {
        const imageName = dockerUpdateObject.TaskTemplate.ContainerSpec.Image;
        const env = captainAppObj.envVars.map(kv => kv.key + "=" + kv.value);
        const config = { Env: env, Entrypoint: ["/bin/sh"],  HostConfig: { AutoRemove: true, NetworkMode: captainAppObj.networks[0] } };

        const {output} = await api.dockerode.run(imageName, args, process.stdout, config);

        if (output.StatusCode !== 0) {
            throw new Error(`Failed to run image ${imageName} with args ${args} (status code ${output.StatusCode}).`);
        }
    };

    const service = api.dockerode.getService(dockerUpdateObject.Name);
    await setServiceInstances(service, 0);
    await run(["/path/to/script/in/your/image"]);
    dockerUpdateObject.version = (await service.inspect()).Version.Index;

    return dockerUpdateObject;
};

```

**Comment by derek-adair** [comment]
>Sorry, it was a typo... I meant we cannot/should not put the script in the image

I guess I imagined a disposable container that was built, spun up and destroyed.

**Comment by githubsaturn** [comment]
Yes, you wanted to run the predeploy script inside your own container, similar to what I explained above. In that case, use the same predeploy script that I posted above and things should work!

**Comment by pgaultier** [comment]
Hi, 
I found no answer for this kind of question.
In my use case I have CLI commands in my app such as (yii, artisan, ..) which are used to migrate DB, provision stuff etc... 
how can I run such commands remotely ?
I would like to be able to 
 - Run a shell script once deployment is done automatically
 - Run shell scripts on demand in the container 
The « docker run it » seems to not be an option because the cluster cannot be accessed by developpers directly (they can only use the caprover CLI)
Thank you

**Comment by githubsaturn** [comment]
> Run a shell script once deployment is done automatically

This shell script inside the container? If so, why not add it to the Dockerfile?


> Run shell scripts on demand in the container

https://caprover.com/docs/troubleshooting.html#how-to-run-shell-inside-my-application-inside-container

**Comment by fidelix** [comment]
I appreciate the replies, but they do not address the issue of ease of use (which is the goal of the issue).

Regarding the suggestion made here:
https://github.com/caprover/caprover/issues/635#issuecomment-604994857

That's a lot of work for something that could be automated precisely with the OP's suggestion:

```
{
  "schemaVersion": 2,
  "pre-deploy": /path/to/sh/script,
  "post-deploy": /path/to/sh/script
}
```

Is there a reason caprover couldn't automate this by simply executing the given command inside the app container by default?

**Comment by githubsaturn** [comment]
I don't think it is a matter of nomenclature since it cannot be generalized. Take the psot-deploy for example. When do you want to run this? In Docker's ecosystem, a code change, env var change, and port change, they all require removing the old container and setting up a new one. You cannot distinguish a code change with a config change (env var, etc...).  Now, if you're okay with this, and you still want to run your code whenever any of these happen, you can simply leverage CMD in Dockerfile. Something like `CMD run_post_deploy.sh && run_application.sh`.

**Comment by fidelix** [comment]
So the idea with the post-deploy as I see it is that caprover would run the command after the new container is up, variables have changed, and in the case above, `run_application.sh` is already running.

But now that you mentioned `CMD run_post_deploy.sh && run_application.sh`, I do see less use in it, except in some really edge cases...

Thanks for all the replies, though.

**Comment by scwall** [comment]
Hello I just came across this post, 
indeed a field to execute a command or a script would be very useful
I have to run a migration command once the deployment of my container is finished, so I have to connect to the machine each time and run a "docker run ... migrate {database}". 

is there a way to run it after the container is launched? 

thank's
