### ISSUE TITLE
Per app deploy keys

### ISSUE THREAD

**Issue by deanrock** [caprover/caprover#655]
**Is your feature request related to a problem? Please describe.**
In my use case, I use CI (either Gitlab CI or GitHub Actions) to build Docker images and run tests, and would like to deploy image for current git commit that triggered CI build.

Currently, I can achieve this by using admin password, but don't like the fact that I need to share this password to all of my projects.

**Describe the solution you'd like**
I'd like to either do:
```bash
export CAPROVER_PASSWORD=SecretForMyApp
caprover deploy -a myApp -i $IMAGE:$CI_COMMIT_SHA
```
or just have a dedicated 'webhook' which would accept captainDefinition as POST argument.

**Describe alternatives you've considered**
Alternative is that I have `captain-definition` file in my git repo, but this is limited to hardcoded image name, e.g.:
```
{
  "schemaVersion": 2,
  "imageName": "registry.gitlab.com/user/app:latest"
 }
```
With this I could leverage the webhook to deploy it.

Downsides here are:
* I'd like to always deploy image for git commit/CI run where it was triggered.
* I'd like to limit access for a specific password/secret to a single app.

**Comment by githubsaturn** [comment]
@deanrock 

This has been discussed in the past. Because of the CapRover architecture, having per-app token only provides "false" sense of security and will do more harm than good. Since CapRover is fully customizable, an app can create a volume that binds to the host Docker unix socket. In that case, that app, can control Docker, therefore can control the entire system. For this reason, having per app security key only provides a false sense of security.

With regards to the webhook. You are on the right track! In fact this is exactly the recommended way. In order to avoid re-committing on the same branch, you can create a release-caprover branch and on that branch the only file you keep is `captain-definition`. On high level here is your gitlab process:

On `master` branch
1- On new commits build the docker image
2- Push the docker image to gitlab docker registry and save it as  `registry.gitlab.com/user/app:hashcodeOfCommit`
3- Change branch to `release-caprover` and echo the new content to `captain-definition`
4- With the new content, commit to `release-caprover` and force push

On `release-caprover` branch
- Setup webhook for caprover to pull the repo and update the image name.

**Comment by deanrock** [comment]
@githubsaturn I've read a few past issues regarding user management, and different levels of permissions. However, I'm not suggesting that.

What I'm suggesting is to have a way to deploy a new image (or maybe even a tarball, if that helps someone), which would in no way allow anyone to access anything that's not already allowed for the specific application.

Having a separate branch, to which you push updated reference, sounds like a workaround, not a proper solution.
