### ISSUE TITLE
Installation failed: error creating external connectivity network

### ISSUE THREAD

**Issue by tp0ck3r** [caprover/caprover#665]
**What is the problem?**
I have a brand new vps with only Docker and NPM installed. I tried to install Caprover multiple times but I always get the error message:
`error creating external connectivity network: cannot restrict inter-container communication: open /proc/sys/net/bridge/bridge-nf-call-iptables: permission denied`

**Steps to reproduce the problem:**
Run the command from the documentation:
`docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover`

**Answers to the following questions where applicable:**
- Your OS and version?
Ubuntu 18.04.4 LTS
- RAM?
48GB

Any help appriciated!
Thanks in advance!

![Screenshot from 2020-05-05 15-29-04](https://user-images.githubusercontent.com/1336365/81074278-150e3c00-8ee9-11ea-8fc8-69e07fc88338.png)

**Comment by githubsaturn** [comment]
Short answer:
Most probably your VPS provider has non standard OS.

More details:
This is not a CapRover problem. It's a Docker low level system issue ([here](https://bugs.launchpad.net/ubuntu/+source/docker.io/+bug/1618283) and [here](https://stackoverflow.com/questions/51930407/docker-compose-error-cannot-restrict-inter-container-communication) for example). It's most probably due to a customized kernel that your vps provider uses. CapRover is tested on standard Ubuntu. 

- Try using a standard version of Ubuntu (try DigitalOcean)
- Also try using a [standard installation of Docker](https://docs.docker.com/engine/install/ubuntu/), not the snap version.

Closing this issue as it's unrelated to CapRover. Let me know if you have further questions.
