### ISSUE TITLE
[Question] Verification Failed error when setting up server

### ISSUE THREAD

**Issue by bwbb** [caprover/caprover#679]
```
$ caprover serversetup
Setup CapRover machine on your server...

? have you already started CapRover container on your server? Yes
? IP address of your server: 10.0.0.16
? CapRover server root domain: bdev.mywire.org

Cannot verify that bdev.mywire.org points to your server IP.
Are you sure that you setup your DNS to point "*.bdev.mywire.org" to 10.0.0.16?
Double check your DNS, if everything looks correct note that DNS changes take up to 24 hours to work properly. Check with your Domain Provider.

Error Code: 1107  Message: Verification Failed.
```

✅Ports are open in firewall, and router

It's interesting that `curl localhost:3000` hangs, but `curl 127.0.0.1:3000` returns the caprover page right away.

It hasn't been 24 hours yet, but `<anything>.bdev.mywire.org` points to my IP already... I'm using the free DNS service from dynu.com.

Is there anything I'm missing?

**Comment by githubsaturn** [comment]
`10.0.0.16` is a local IP address. Are you trying to install CapRover on a local machine behind a NAT via port forwarding on your router? CapRover is really meant to work on servers with public IP address.

The problem you're facing is that CapRover is trying to connect to `randomtuuid.bdev.mywire.org` to verify this resolves to itself... Since your instance is behind a NAT, it cannot verify that.

Having said this, this verification is an optional process that is meant to catch unwanted errors. If you're sure that your DNS is working and everything else is fine, you can turn off domain verification by running this on your server. 
```
echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json
docker service update captain-captain --force
```

Feel free to update if you still have problems.
