### ISSUE TITLE
Staging environments

### ISSUE THREAD

**Issue by umaar** [caprover/caprover#684]
This is a great project! Thought this could be the start of a discussion around staging environments, but I understand from your `contributing.md` that you want to keep the scope of this project small, totally understand if this feature request is not suitable.

Right now, you can create multiple apps pretty easily, and have one app be a "staging" app, and another one be your "production" app - however semantically, architecturally, those two apps would not be connected in anyway. So would it be possible for caprover to allow any app to have its own staging environment through the UI? And maybe support common use cases such as having production be a clone of staging? This could support:

1. I make a change and `caprover deploy` to staging
2. I verify the changes are correct on `https://staging.example.com`
3. I instruct caprover, somehow, that it can "deploy" to production, based on cloning the staging environment

**Comment by osmanzeki** [comment]
I would also be interested in this discussion. I enjoyed how Elastic Beanstalk handled this on Amazon AWS.

Basically, each "application" is a namespace for an arbitrary number of "environments".

https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.html

Obviously, I think there would be no need to actually try and model anything at that level of complexity for CapRover. I also enjoy the simplicity of the project and its mission to remain simple too.

That said, perhaps some sort of concept of grouping and/or namespacing might be useful in the future indeed.

**Comment by maietta** [comment]
Perhaps the built in features of Swarm could be of use here? Labeling your nodes in the swarm means you can place deployment constraints against those labels and define your constrains by way of creating separate deployment files, say docker-compose.stage.yml and docker-compose.prod.yml.

I am prepping to use Caprover myself and thinking this will be something I will approach myself since I have a couple of development servers dedicated for testing before running in production.

**Comment by githubsaturn** [comment]
The concept of staging vs. production is very much dependent on the type of app. CapRover is not a closed system, like elasticbean or Heroku, that is limited to certain type of webapps. Due to the variety of the types of apps that you can deploy via CapRover, it is not easy and practical to introduce a staging vs production that won't cause confusion. Interestingly, all three comments on this thread are an example of this and they are referring to different solutions.

[First comment](https://github.com/caprover/caprover/issues/684#issue-623539233) refers to creating a staging and production app in the UI that are not connected to each other, i.e, they are in parallel universe. This is definitely not practical on a single host with some types of apps. Imagine an app that has a persistent directory that maps `/var/log` of the host to `/var/log` of the container. In this case, the staging app and the production app would share the same persistent directory and it would definitely cause data corruption.

[Second comment](https://github.com/caprover/caprover/issues/684#issuecomment-633156275) refers to a prioperitory environment. In this environment the apps are managed by a third party system that creates VMs on the fly and it manages the lifecycle of the VMs which are invisible to the users eyes.

[Third comment](https://github.com/caprover/caprover/issues/684#issuecomment-633158135) is probabaly the closest thing to CapRover can theoretically do, but it results in lots of complications as the managers and workers are shared across production and staging environment. This results in a architecturally flawed staging/production environment.


-----------------


### Alternative solution:
The solution that is architecturally correct is to use two separate clusters for production and staging. In this setup, ideally you don't use the CI/CD part of CapRover. You build your images on a separate CI/CD platform, for example gitlab. Then deploy to staging cluster, and if the tests pass, you deploy to your production environment. This is the only way that you have a proper staging and production environment knowing that your two environments cannot talk to each other.
