### ISSUE TITLE
extendables variables fields (advanced)

### ISSUE THREAD

**Issue by LiquidITGuy** [caprover/caprover#690]
**Is your feature request related to a problem? Please describe.**
When I'm using some one click app (even the one I push), I have a lot of "useless" fields who I dont need to show to use it.
for exemple 

n8n:
useful: cap_n8n_version, cap_timezone, cap_user, cap_pass
useless: cap_postgres_version, cap_db_pass, cap_db_user

mautic : 
useful: cap_mautic_version
useless: cap_db_user, cap_db_pass, cap_percona_version

display all this not so useful fields are annoying and can add some difficulties to add new services (even more true with complex app)

**Describe the solution you'd like**
Adding a advanced attributes into the one app layout then hide thoses fields by default and unhide them if the user click on display/hide advances fields

**Additional context**
all passwords is considered as useless because of the previous issue

**Comment by githubsaturn** [comment]
This is going to be very subjective. What is being considered as essential for one user may be non-essential to another user. 

For example in your n8n example, if the version of the database isn't something that the user should care about, it shouldn't be surfaced as a variable at all. It can be simply hardcoded in the instructions. Otherwise, if it's typically set to a default a value, but it can be changed, then you should use the default value as expected. 

Password is a special one since sometimes it's internal to the application, sometimes it's something that the user needs to know about. Regardless, the user has to customize their password. One interesting idea for password was this one: https://github.com/caprover/caprover/issues/637
