### ISSUE TITLE
Token for command line deployments

### ISSUE THREAD

**Issue by solomon23** [caprover/caprover#698]
Hello,

I have CapRover setup with codeship where codeship will pull git, run some things, and then deploy to CapRover using a built tar file.  This all works very nicely and is very cool.  The problem is the only way to deploy to CapRover is to use my one root password.  I want other developers to be able to have access to CodeShip but I don't want them to have access to my CapRover root password.  

I think it would make sense to be able to generate a hash/token per app that allows for deploying that app.  It's similar to what's being done for git where the hook generates a token.

Thoughts ?

Solomon

**Comment by githubsaturn** [comment]
This issue has been brought up in the past. The problem with creating app specific hash tokens is the false sense of security. This is due to the fact that, by design, CapRover has a very light set of limitations on what apps can do. There is no guarantee that app1 cannot access app2, or even cannot access the host. For example, if user1 has a token for app1, all they need to do to access other apps is to add a volume mapping that maps `/var/run/docker.sock`.

The webhooks on the other hand are different. First of all, they follow a pull based mechanism. Second, they are only used for the deployment process.

Happy to hear alternative solutions.

**Comment by solomon23** [comment]
What if you restrict the hash to just deployments.  In that case they wouldn't be able to add volume mapping, no ?

**Comment by githubsaturn** [comment]
That may work. I'll look into this.

**Comment by solomon23** [comment]
I've jumped into the code before, if you decide this is a reasonable solution let me know and I can help.

**Comment by iBobik** [comment]
How about using existing webhooks tokens, just add it also to other routes?
