### ISSUE TITLE
[Deployment Issue] Caprover refeshed, how to redeploy existing images?

### ISSUE THREAD

**Issue by Turab** [caprover/caprover#724]
Hi. I have been testing Caprover for several days and wanted to give it a go for production, deploying 2 apps. Everything was working fine until today. I deployed a new app (Bitwarden_rs) and setup a custom domain like pass.domain.com and it successfully added, as that domain was already resolving to Caprover server IP. (Because I had deployed the same application to the same domain name before, for testing.)

Although it successfully added the custom domain, it couldn't assign an SSL to it giving "1107 verification failed" error. After I received this error, Caprover itself broke and never worked again along with the 2 other applications.

Now there are three questions here;

**1-** Domain must be verified **_before_** it could be added as a custom. So how could it verify while adding the domain but can't verify while assigning a certificate?
**2-** Why would this error break down the whole thing?
**3-** Caprover docs claim that even if you decide to remove Caprover later, yours apps would continue to work fine. But why didn't they considered the apps were working and nothing changed about them although only Caprover broke?

I know the questions seem a bit vague but that is exactly what happened. The logs were complaining that captain.apps.domain.com couldn't be verified so it couldn't start, although DNS settings never changed for the domain.

After the break down, I saw that the captain-config.json is emptied. I then re-ran the setup command for Caprover and now I can login to UI again and it works, but as you could guess, installed applications are gone.

I see that there is a backup of captain-config.json (which I created per the suggestion of the docs about broken nginx) and I copied the "appDefinitions" block to the live config file hoping that existing volumes and images could work again. But it broke Caprover again. (No custom nginx conf by the way.)

For the third time I ran the Caprover setup to be able to login to UI and again I copied the "appDefinitions" block with only one application. Now each time I am trying this, Caprover is emptying the config file all over leaving only "namespace": "captain"

Now the last question;

How can I tie those volumes and images to Caprover again so they could work?

**Comment by githubsaturn** [comment]
> 1- Domain must be verified before it could be added as a custom. So how could it verify while adding the domain but can't verify while assigning a certificate?

Did you change anything in between? Perhaps changing anything on the host machine like a network config or etc? Like what you said, it shouldn't break by itself.


> 2- Why would this error break down the whole thing?

That error didn't probably break the whole thing. The root of that error was something that made your domain not to resolve to caprover's IP address. When this happens, CapRover's internal health monitoring system kicks in and it restarts itself in an effort to fix the issue. But in this case, restart didn't resolve the issue because your domain resolution was broken elsewhere.

>  3- Caprover docs claim that even if you decide to remove Caprover later, yours apps would continue to work fine. But why didn't they considered the apps were working and nothing changed about them although only Caprover broke?

Like I said in point 2, the issue wasn't the fact that CapRover broke. The issue was that your domain resolution didn't resolve to the CapRover's IP address (or other network issues). You can verify that statement in CapRover docs, by setting up a healthy CapRover installation (one server or a cluster) and simply take down CapRover service `docker service scale captain-captain=0` and you'll see that everything will keep working. 


> For the third time I ran the Caprover setup to be able to login to UI and again I copied the "appDefinitions" block with only one application. 

In the past 3 years, we didn't have a single report like this. The fact that it happens for you over and over points me to a special condition on your machine. Are you sure your host machine is healthy? A few points:
- Make sure you install docker from official Docker installation guide - do not use the snap version, it's buggy.
- Make sure that your host system is healthy and ideally you have a public IP interface without anything in between

> Now each time I am trying this, Caprover is emptying the config file all over leaving only "namespace": "captain"
Now the last question;
How can I tie those volumes and images to Caprover again so they could work?

Okay, it seems like the problem is that your configuration keeps vanishing. And it keeps happening for you. A few questions to help you diagnose the issue:
- Does it only happen when you install a particular one click app or any app?
- What VPS provider do you use?
- RAM and CPU?
- OS?
- Do you directly point a wildcard domain to your IP or you use a caching layer like CloudFlare or such?

**Comment by Turab** [comment]
@githubsaturn thank you for your concern.

> Did you change anything in between? Perhaps changing anything on the host machine like a network config or etc? 

No, I haven't changed anything but adding that custom domain to the newly deployed application. But I guess removing unused images and volumes could have broke the whole thing. After deciding to deploy some apps for production, I just made a disk cleaning by removing unused images, volumes and containers. After opening this issue, I saw that there is a known bug about it and it is possible that the issue is related. But don't know how it wouldn't break until I add this custom domain.

> The root of that error was something that made your domain not to resolve to caprover's IP address. 

Not possible, because as I said, when adding the domain, Caprover already makes a validation if it resolves to its IP and it successfully adds because the domain is already resolving to Caprover. Right after it adds the domain, I click on the SSL button, then it says verification error. I remove the domain and re-add; Caprover successfully adds the domain again, no verification issues. And when clicked, domain already shows the Caprover page.

> In the past 3 years, we didn't have a single report like this. The fact that it happens for you over and over points me to a special condition on your machine. Are you sure your host machine is healthy?

Yes, host machine is brand new bare Centos 7 with 4 cores and 8GB RAMs. Its a VM in our own dedicated server and docker is installed per the suggestions of Caprover, it has a public IP which was already working for the past week without any conditions.

> Okay, it seems like the problem is that your configuration keeps vanishing. And it keeps happening for you.

There might be a misunderstanding here. Config file is not vanishing on its own. It vanishes only if I edit it. I can deploy applications, the config file updates itself accordingly and it doesn't vanish. But if I change something in it manually, then it empties the file all over leaving only the namespace.

> Do you directly point a wildcard domain to your IP or you use a caching layer like CloudFlare or such?

I directly point a wildcard to public IP without a caching layer. During the testing faze, it was a domain on Cloudflare but it was disabled. After I took the server to production, I nevertheless changed the root domain to another one outside Cloudflare.

As I said, it might all be happening due to the known bug about disk cleaning. But don't know why the config file breaks if you manually change "anything" in it.

By the way, one of the prod. apps I deployed was Nexcloud. I re-deployed with the same name before and used the same passwords. Now the old image and volume is being used and working correctly.

**Comment by githubsaturn** [comment]
> After deciding to deploy some apps for production, I just made a disk cleaning by removing unused images, volumes and containers. After opening this issue, I saw that there is a known bug about it and it is possible that the issue is related. But don't know how it wouldn't break until I add this custom domain.

Manually deleting images can definitely break the who system, because of this [bug](https://github.com/moby/moby/issues/36295) The reason that nothing broke until you added a custom domain is that the system updates once a change is made. And that could be the trigger for it.

> Right after it adds the domain, I click on the SSL button, then it says verification error. I remove the domain and re-add; Caprover successfully adds the domain again, no verification issues. And when clicked, domain already shows the Caprover page.

This seems impossible. The domain verification is absolutely the same code path. Can your provide step-by-step reproducible scenario for this issue?

>There might be a misunderstanding here. Config file is not vanishing on its own. It vanishes only if I edit it. I can deploy applications, the config file updates itself accordingly and it doesn't vanish. But if I change something in it manually, then it empties the file all over leaving only the namespace.

Okay this clears things up. Before making a config change, you need to turn CapRover off and turn it back on when the change is saved to avoid disk<>memory conflict. The steps are usually:
```
docker service scale captain-captain=0
nano /captain/data/config-captain.json
docker service scale captain-captain=1
```
>As I said, it might all be happening due to the known bug about disk cleaning. But don't know why the config file breaks if you manually change "anything" in it.

See above.

> By the way, one of the prod. apps I deployed was Nexcloud. I re-deployed with the same name before and used the same passwords. Now the old image and volume is being used and working correctly with the old data. Is it do you think by design?

When you delete an application from the web GUI, the UI will give you the option to also delete the volumes associated with the app. If you decide not to delete the volumes, the next time you deploy the app with the same name, the same volumes will be used.

**Comment by Turab** [comment]
@githubsaturn , thank you again. Yes, I figured it out that the cause is the known bug and I didn't know that I would need to stop Caprover before making changes in the config file.

> This seems impossible. The domain verification is absolutely the same code path. Can your provide step-by-step reproducible scenario for this issue?

I know how it sounds as it drove me crazy at the time. But unfortunately I am unable to reproduce the steps because I already re-ran the setup command and now it works. For making sure how crazy it was; I removed the domain for several times and each time it could add the domain successfully after which it always failed to activate SSL because of verification error.

I guess this might caused by Caprover having been refreshed at the backend without having everything loaded at the frontend at that moment. This doesn't explain the successful addition of the custom domain as it still needed to run the validation check; but there might be a bug in Ajax block.

**Comment by githubsaturn** [comment]
Update calls are POST calls and are not cached on browsers. That couldn't be the reason behind the issue. The only potential root cause might be the issue where CapRover is able to verify the domain, but the certbot servers aren't able to verify. This is rare, but it could happen:

CapRover verifies the domain by sending a request to `http://thedomain.com` and makes sure that nginx receives it. This request doesn't go outside of your network. It bounces within the network. But Certbot servers are reaching out to your domain from an external source, so it's possible that the cannot reach the network. Reasons include, DNS propagation hasn't made it to Certbot servers region, your network is blocking the incoming requests from certbot servers and many other reasons.

**Comment by Turab** [comment]
A logical explanation, but misses out that other applications could verify for SSL. Additionally, there are other applications deployed by Caprover which all verified for SSL. So no blocking on the server side. Maybe it was a glitch at that exact time but I highly doubt it.

Guess this will stay unknown until it happens again.

**Comment by githubsaturn** [comment]
Next time it happens, make sure to capture the logs from your CapRover instance as it'll have more meaningful information in it. 
https://caprover.com/docs/troubleshooting.html#second
