### ISSUE TITLE
Mongodb connection issue

### ISSUE THREAD

**Issue by a6un** [caprover/caprover#728]
Hi All, when connecting nodejs app to mongo, it is throwing error message **MongooseServerSelectionError: getaddrinfo ENOTFOUND srv-captain--prod-db srv-captain--prod-db:27017**.

MONGO_INITDB_ROOT_USERNAME : root
MONGO_INITDB_ROOT_PASSWORD : 123456

Connection URL: **mongodb://root:123456@srv-captain--mongo/mydatabase?authSource=admin**

can anyone help me to fix this issue?

**Comment by githubsaturn** [comment]
Your connection string looks fine. 

- Is `prod-db` the exact name of your db?
- Are you running on a cluster or a single node?

**Comment by a6un** [comment]
Thanks, @githubsaturn  for your valuable time. Some commands are missed in nodejs. @JacobSamro helped me to fix this issue.

**Comment by moellrich** [comment]
@a6un Please describe, what commands are missing.
I have the same issue.
Thx in advance

**Comment by Alfagun74** [comment]
Same here. 
Whats the point of an open issue tracker if people go write "Some commands are missed in nodejs".
@moellrich @a6un @githubsaturn @JacobSamro

**Comment by githubsaturn** [comment]
Hi @Alfagun74 - this is really a MongoDB issue. See [this one](https://stackoverflow.com/questions/39108992/mongoerror-getaddrinfo-enotfound-undefined-undefined27017/39109112) and [this one](https://stackoverflow.com/questions/36048655/nodejs-mongoose-error-getaddrinfo-enotfound-undefined-undefined27017) for example.

The root cause is generally due to the connection string being wrong. The exact solution depends on your source code. I suggest post your question, alongside with your exact source code that you're using on StackOverflow to get an answer.

**Comment by Alfagun74** [comment]
Thank you for some actual help man @githubsaturn
