### ISSUE TITLE
Lets Encrypt challenge fail with poste.io

### ISSUE THREAD

**Issue by MrSquaare** [caprover/caprover#729]
What is the problem?

I try to generate Lets Encrypt certificates from the administration panel of poste.io to be able to support STARTTLS, but the challenge fails (because https://app-name.root.domain.com/.well-known/acme-challenge/ is not accessible)

Steps to reproduce the problem:

- Use poste.io one-click app
- Go to app-name.root.domain.com/admin/le/
- Click "Save changes"

Answers to the following questions where applicable:
- Your OS and version? Ubuntu 20.04
- RAM? 16GB

**Comment by githubsaturn** [comment]
This is expected behavior. CapRover uses `/.well-known/*`  to manage SSL certificates. You have two options:
- Let CapRover continue managing SSL certificate. Then just map the cerbot directory to any directory that poste.io uses.
- Block CapRover and let poste.io manage your certificate. If you do that, you should expect poste.io to manage and renew the certificate for you. If that's what you want then remove the following block from nginx block of your poste.io app by clicking on your app then click on EDIT NGINX CONFIG and remove this block:
```
        # Used by Lets Encrypt
        location /.well-known/ {
            root <%-s.staticWebRoot%>;
        }
```

**Comment by MrSquaare** [comment]
I see, I preferred to take the first option
However, I don't see how "mapping" the certbot directory to poste.io

I have for the moment used the web interface of poste.io which also offers to enter the certificates manually (with an intermediate certificate requested, I guess it can be found on this page: https://letsencrypt.org/2015/06/04/isrg-ca-certs.html ?).
Unfortunately this means that I would have to manually update the certificates at each renewal.

Also, I would like to have two domains for mailboxes, the problem is that the certificates generated by CapRover are dissociated for each domain, is there a way to "assemble" them?

Thanks a lot for the help :smile:

**Comment by githubsaturn** [comment]
If you enable HTTPS for any domains, it's available in LetsEncrypt directory `/captain/data/letencrypt/etc/live/`

If you map this directory to any directory in poste.io you can use these certificates.
