### ISSUE TITLE
How to upgrade caprover from 1.6 to 1.7

### ISSUE THREAD

**Issue by tim-hub** [caprover/caprover#767]
I tried searched on issues and google.

https://github.com/caprover/caprover/releases/tag/v1.7.1
![image](https://user-images.githubusercontent.com/2884320/87915758-14a22d80-ca62-11ea-87a7-acd7ccece29c.png)

it seems like there is no clear document about upgrade from 1.6 to 1.7?

can anyone create a guide for this?

**Comment by githubsaturn** [comment]
Are you by any change have blocked outgoing requests from your server? 

CapRover checks the update status automatically and it displays an update message, when the update is available.

You can manually update by running
```
docker service update captain-captain --image caprover/caprover:1.7.1
```
But unless you've blocked outgoing request, you should be able to update from the UI too. That's why there is no issues, or documentation on this, because it's all in the UI.

![image](https://user-images.githubusercontent.com/10582082/87935289-d0f9f480-ca5e-11ea-9e18-c11259405892.png)

**Comment by tim-hub** [comment]
Thanks, will check the firewall, but I assume it is not blocked

**Comment by tim-hub** [comment]
I found the problem.

It is not from firewall, 

It is like when they get request from `api.v2.caprover.com`, it returns 404.

`sudo docker service logs captain-captain `
```
 Error: getaddrinfo EAI_AGAIN api.v2.caprover.com
```

@githubsaturn do you have any ideas on this?

**Comment by githubsaturn** [comment]
I replied to your other comment. It's not 404
https://github.com/caprover/caprover/issues/812

The error you're getting is `EAI_AGAIN` which is DNS lookup failure which is a network connectivity issue.
