### ISSUE TITLE
[Question] A chat about Cloudflare and reverse proxy

### ISSUE THREAD

**Issue by MattiaFailla** [caprover/caprover#775]
Hello guys, I hope it is the right place to have a relaxing chat about the problems that prevent cloudflare from working with caprover. 
Since I am really very happy with CapRover I would like to understand what problems there are with Cloudflare and how we could solve them (I am ready (where my skills allow me) to participate in a possible PR).

Why do I insist on cloudflare? I find it a good service and I wish it was part of my technology stack. I am not affiliated with them in any way but I have always admired their work. 
Today it is increasingly important to protect your network, your server and your application with the best technologies in circulation, and I would personally like to point in the direction of CloudFlare.

For CapRover gurus: what prevents the cloudflare reverse proxy from working properly with caprover?

**Comment by githubsaturn** [comment]
What is the issue you're having with Cloudflare?

You can use it to attach custom domains (not root domain) to your apps.

**Comment by MattiaFailla** [comment]
> You can use it to attach custom domains (not root domain) to your apps. 

That's the problem, I would really like to attach my root domain with the reverse proxy of CloudFlare in order to protect my apps (and the caprover login page)

**Comment by githubsaturn** [comment]
You "can" use it as your root domain. But the SSL termination point will be CloudFlare. If you're okay with it, the only thing that you need to do prevent CapRover from "verifying domains".

**Comment by githubsaturn** [comment]
All you need to do is
```
echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json
docker service update captain-captain --force
```

**Comment by golyalpha** [comment]
Actually, what you can easily do, is disable the CloudFlare proxy on the domain while HTTPS is not setup on CapRover, and once it is, reenable it later, as from then on, CloudFlare won't have issues passing LE's requests through, as the certificate on CapRover's end will be valid.

**Comment by golyalpha** [comment]
But basically, your issues is that CloudFlare is trying to verify the certificate of the Origin (your CapRover server), and the Origin doesn't have a valid certificate, so CloudFlare ends up returning an error page rather than passing the request and response through.

**Comment by githubsaturn** [comment]
Thanks @golyalpha ! I didn't know it was possible to have HTTPS forwarded on CloudFlare... Thanks for this!

Closing this issue. Feel free to reopen if you still have questions.

**Comment by golyalpha** [comment]
@githubsaturn 
![image](https://user-images.githubusercontent.com/8203992/89390295-c9954500-d706-11ea-8a22-4545d1353d9e.png)

It would potentially be interesting to implement self signed certificates on CapRover (Origin) end, so that people can configure their CloudFlare with Full encryption and leave the proxy setting always on. I haven't really tested certificate issuance from Let's Encrypt through CloudFlare proxy (not talking about renewal, that works fine AFAIK), but that would also be technically unnecessary (for the origin to have a LE-signed certificate under non-Strict Full configuration on CloudFlare).

**Comment by golyalpha** [comment]
It might actually be worth it to figure out a way to get certificates from CloudFlare's Origin CA, if CloudFlare serves as a CDN for the application.

**Comment by githubsaturn** [comment]
It is technically possible to use your own self-signed certs, it's not a built-in mode, but there is enough customization hooks available that you can achieve this:
- First you need to copy your certs in `/captain/data/nginx-shared` [directory](https://caprover.com/docs/nginx-customization.html#custom-files-and-directories).
- Next, you need to edit your nginx config to load the certs from `/nginx-shared` directory.
- If you go down this route, you can remove `if (s.hasSsl) {....` lines and such in the nginx config as you'll be managing the SSL yourself, not CapRover.
- Finally, depending your setup, you may also need to [disable domain verification](https://github.com/caprover/caprover/issues/759#issuecomment-656081220) at CapRover level.

**Comment by golyalpha** [comment]
I think it might be better to let CapRover issue the self signed certs on it's own, if you want to take it that route. Then there's the part about CF's Origin CA, which is probably the better route to go by, but it means CapRover will need to ask for the user's CF API key, in order to interact with CloudFlare and attempt to retrieve the certificate.

Up to you, really, but I'd personally recommend users using CF to keep their TLS setting on Full (strict) and retrieving certs for the origin from CloudFlare, and to make it as easy as possible, to automate the retrieval and deployment process from CapRover.

**Comment by golyalpha** [comment]
I should add, for people not using CloudFlare, nothing should change.

**Comment by MattiaFailla** [comment]
What should I do if Clouflare has not been used so far? 
I mean that now I have activated forced https on some of my apps and therefore certbot will go on checking them.. 

I can't simply activate cloudflare, because this would break everything when certificates expires.. right?

**Comment by golyalpha** [comment]
Nope. As I said, if the certificate is valid during renewal, CloudFlare will pass it right through, without any issues. So, you should be fine, as Certbot usually renews certs before they expire.

**Comment by golyalpha** [comment]
In other words, if you already have valid certificates, you can just enable CloudFlare proxy in Full (strict) TLS mode, and everything will work fine. If you don't, you can either use Flexible TLS mode (doesn't use HTTPS between the Proxy and the Origin) to retrieve the certs, and switch it to Full (strict) afterwards, or you can disable to proxy for a while before getting the certificate form LE, and then enable it again. Either way, you should be using Full (strict) TLS mode.

**Comment by uncvrd** [comment]
@golyalpha hi - thanks for this thread. I've been trying to use CloudFlare as CDN for an image proxy (imgproxy.net) that's hosted through Caprover. I've been attempting your steps but I receive a `This site can’t provide a secure connection` webpage error. I was wondering if you could quickly see where my issue lies?

1. set up a wildcard dns `A` entry for `*.api` (no proxy)
2. set up a wildcard dns `A` entry for `images.api` and enabled proxy (should take precendence over wildcard right?)
3. created an app in caprover called `images` that is accessed at `images.api.mysite.com`
4. enabled HTTPS in caprover for `images` app
5. Added Full (strict) mode in CloudFlare

> if you already have valid certificates, you can just enable CloudFlare proxy in Full (strict) TLS mode, and everything will work fine

In that case I believe I've followed the instructions, but would be interested to know if I've missed a critical step that would fix the problem! Thanks for any guidance.

FULL PAGE ERROR:

```
This site can’t provide a secure connection
images.api.mysite.com uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```

**Comment by golyalpha** [comment]
> @golyalpha hi - thanks for this thread. I've been trying to use CloudFlare as CDN for an image proxy (imgproxy.net) that's hosted through Caprover. I've been attempting your steps but I receive a `This site can’t provide a secure connection` webpage error. I was wondering if you could quickly see where my issue lies?
> 
> 1. set up a wildcard dns `A` entry for `*.api` (no proxy)
> 2. set up a wildcard dns `A` entry for `images.api` and enabled proxy (should take precendence over wildcard right?)
> 3. created an app in caprover called `images` that is accessed at `images.api.mysite.com`
> 4. enabled HTTPS in caprover for `images` app
> 5. Added Full (strict) mode in CloudFlare
> 
> > if you already have valid certificates, you can just enable CloudFlare proxy in Full (strict) TLS mode, and everything will work fine
> 
> In that case I believe I've followed the instructions, but would be interested to know if I've missed a critical step that would fix the problem! Thanks for any guidance.
> 
> FULL PAGE ERROR:
> 
> ```
> This site can’t provide a secure connection
> images.api.mysite.com uses an unsupported protocol.
> ERR_SSL_VERSION_OR_CIPHER_MISMATCH
> ```


Did you wait for the Let's Encrypt HTTPS certificate to be issued first, and did you disable the Proxy function in the DNS settings for the relevant records?

**Comment by uncvrd** [comment]
@golyalpha thanks for the quick response! I guess I'm confused on "disabling the proxy function on DNS settings for relevant records" because that's what enables the cdn, correct?

1. I disabled the Cloudflare Proxy for the DNS A record of `images.api.mysite.com`
2. created the application `images` in caprover
3. enabled https in caprover for `images`

At this point I can hit https of my application and it works perfectly, however, it's not hitting the Cloudflare cache because the proxy is disabled for `images.api.mysite.com` (instead it's hitting the caprover nginx)

Is it at this point that I can re-enable the proxy or should this be turned off and im just missing something? Sorry for my confusion.

**Comment by golyalpha** [comment]
Yes, now that you have HTTPS working on Origin, you can safely re-enable the Proxy within CloudFlare.

**Comment by uncvrd** [comment]
@golyalpha thanks for clarifying - unfortunately, when I go to re-enable the proxy for the `A` record of `images.api.mysite.com` I get the page error mentioned above:

```
This site can’t provide a secure connection
images.api.mysite.com uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```

I definitely understand the explained method above - is there any other info I can help provide to help debug this problem?

**Comment by golyalpha** [comment]
Okay, this is gonna need a bit more debugging. Disable the proxy again, and run an SSL test suite on the server (Qualys SSL Labs, for example).
This looks like a configuration issue within CapRover's NGINX container using outdated TLS settings (browsers generally will work fine, but CloudFlare isn't as forgiving)

**Comment by uncvrd** [comment]
@golyalpha was JUST looking at Qualys SSL Labs haha - ok here's what the test returned when running on `images.api.encoreapp.co`:

![image](https://user-images.githubusercontent.com/25097099/109116377-44e73400-76f5-11eb-854e-d277988bbc50.png)

**Comment by golyalpha** [comment]
Well, this is weird. I guess you're going to have to have a back and forth with CloudFlare support, because I don't see any obvious reason as to why CloudFlare shouldn't work.

**Comment by uncvrd** [comment]
@golyalpha ok - i might be seeing the issue? After some digging I found this thread: https://community.cloudflare.com/t/community-tip-fixing-err-ssl-version-or-cipher-mismatch-in-google-chrome/42162

Where step 3 states that:

> Understand how the certificate works
Certificates will only cover a single level of subdomains (.example.com, but not *…example.com):
Will work - www.example.com
Will work - example.com
Will work - test.example.com
Will NOT work - www.test.example.com
Will NOT work - staging.www.example.com

So I suppose since I have `images.api.encoreapp.co`, there's an extra level that a cert cannot cover thus making it not compatible with Caprover?

Regardless, if this doesn't spur any other ideas, thanks for your time - really appreciate it

**Comment by uncvrd** [comment]
well that's exactly what the issue was, I created a new caprover instance from scratch and made my url `images.mysite.com` and it worked perfectly and it hits the cloudflare cache! ...too many levels of subdomain 🤯 I guess I'll see if I run in to any issues having this kind of setup but hopefully this will be an "ok" solution! I feel like I read somewhere in the docs this is not the best way to go though...

**Comment by golyalpha** [comment]
Oh, I guess we misunderstood each other then. I thought you were saying CloudFlare was showing that error. Not your browser itself.

**Comment by thomascenni** [comment]
> @golyalpha ok - i might be seeing the issue? After some digging I found this thread: https://community.cloudflare.com/t/community-tip-fixing-err-ssl-version-or-cipher-mismatch-in-google-chrome/42162
> 
> Where step 3 states that:
> 
> > Understand how the certificate works
> > Certificates will only cover a single level of subdomains (.example.com, but not *…example.com):
> > Will work - [www.example.com](http://www.example.com)
> > Will work - example.com
> > Will work - test.example.com
> > Will NOT work - [www.test.example.com](http://www.test.example.com)
> > Will NOT work - staging.www.example.com
> 
> So I suppose since I have `images.api.encoreapp.co`, there's an extra level that a cert cannot cover thus making it not compatible with Caprover?
> 
> Regardless, if this doesn't spur any other ideas, thanks for your time - really appreciate it

Hello, having the same issue. Why certificates will only cover a single level of subdomains? The R3/LetsEncrypt certificates emitted via Caprover dashboard work if Cloudfare proxy is disabled (grey cloud). Why when Cloudafare is enabled, they stop working ?

**Comment by golyalpha** [comment]
What exact error are you getting?

**Comment by thomascenni** [comment]
> What exact error are you getting?

Error code: SSL_ERROR_NO_CYPHER_OVERLAP

**Comment by golyalpha** [comment]
It looks like your browser does not support the ciphers the server is offering. That's not a certificate issue.

**Comment by thomascenni** [comment]
Hello, I think the answer is here:
https://developers.cloudflare.com/ssl/advanced-certificate-manager

> use Advanced Certificate Manager to cover more than one level of subdomain

The Free plan only covers one level of subdomain.

**Comment by golyalpha** [comment]
@thomascenni that shouldn't be a problem that's causing your particular error. What browser are you using to access the site (include the version)?

**Comment by ivalsaraj** [comment]
Same issue while trying to turn on Cloudflare proxy.
1. Setup caprover, added app
2. Connected new domain to the app, verified it (by turning off Cloudflare proxy)
3. Then turned on Cloudflare proxy and getting this error.

![image](https://user-images.githubusercontent.com/42429710/129469082-f44c40ba-814b-46bb-bc82-30ed22a8f883.png)

**Comment by golyalpha** [comment]
CloudFlare SSL mode set to Flexible is basically like not having SSL between your server and CloudFlare at all. Check if you're also not running some unsupported configuration in your CloudFlare account.

Specifically, check if your domain is a first level subdomain (`level1.example.com` for example), deeper levels (`level2.level1.example.com`) require an active CloudFlare subscription. (More here: https://developers.cloudflare.com/ssl/edge-certificates/universal-ssl/limitations)

If you're sure that is not the problem, run a Qualys SSL Labs check on your domain, and see what that comes up with (post the result here if you are unable to come up with a solution on your own)

**Comment by ivalsaraj** [comment]
Thanks for the quick response, I don't have deep level domain, first level domain it not working.

I've found an article about doing it in Dokku: https://okhlopkov.com/cloudflare-certificates-dokku/ Is there any similar articles available for the Cloudflare <> Caprover compatibility, I couldn't find one. An official documentation is worth, as I believe Cloudflare will become the normal for routing and caching in the years ahead.

**Comment by golyalpha** [comment]
Hey @ivalsaraj. 

I've spotted one major issue with that article - it uses CloudFlare Certificates. Those are NOT recognized by browsers as valid certificates.
This represents a certain level of vendor lock-in - if you, for whatever reason, ever decide to stop using CloudFlare, you'll find that it's not gonna be as simple as moving your name servers/disabling CloudFlare Proxy on the relevant DNS records. 
For that reason, it *is* an issue. In practicality, there is zero benefit in using CloudFlare certificates for anyone but CloudFlare themselves, at least until CloudFlare becomes a generally recognized CA.
On top of that, long-lived certificates are a ***BAD*** idea. More on that later.

Now, if you're still 100% determined to use CloudFlare Certificates, I have bad news for you - you'll have to dig into your Caprover deployment, and figure out a way to change the master template to include your CF Certificate, as well as exposing it to Caprover's NGINX instance. I do however recommend you continue reading.

On the other hand, if I have managed to dissuade you from going down the path of CF Certificates, I have more good news for you:
Let's Encrypt certificates being short lived is a *good* thing - it is a good security practice in general, to rotate keys automatically, and frequently by default - that way, if ever a horrible leak happens, even if unnoticed, the period during which the leak is a problem is relatively short. 
Remember when I said long-lived certificates are a bad idea? Let me introduce you to Heartbleed - an exploit that could leak sensitive data, like your server certificate and the associated private keys.
Now, imagine that back when Heartbleed happened, you had 5 years on your 15 year certificate - that's 5 years that *someone* really bad can impersonate your website. You might say: "But we have CRLs!" Yes, yes, we do have Certificate Revocation Lists! And they *do* work... Sometimes... Unfortunately, that sometimes is a problem: What generally happens when one of these is offline for some reason is that browsers just ignore it, and continue on serving the page over HTTPS as if the certificate was valid - at best showing a little yellow warning icon next to the padlock telling you your connection is secure - even though it had been already revoked specifically via a CRL.
I think we can both agree, that if an attacker is capable of getting you to visit their server when you ask for Google, and presenting you with an otherwise valid certificate for Google, they're capable of preventing you from reaching the relevant CRL.

Unfortunately, because you have provided us with zero information about your deployment besides "I use CloudFlare" and the error message you're getting from your browser, and you claim that the previously discussed issues with CloudFlare and Let's Encrypt don't apply to you, I can't help you.

**Comment by bader515** [comment]
**I'm trying to do the same thing using CloudFlare, but I want to include a load balancer (Kemp LoadMaster free version).**
**Is that possible?**

**Comment by golyalpha** [comment]
I don't see why not. Just point your load balancer in SSL Passthrough (might need to use SNI if you use the same LB for other destinations) mode at Caprover, and point your CF record at the load balancer.

**Comment by ak4zh** [comment]
> Actually, what you can easily do, is disable the CloudFlare proxy on the domain while HTTPS is not setup on CapRover, and once it is, reenable it later, as from then on, CloudFlare won't have issues passing LE's requests through, as the certificate on CapRover's end will be valid.

Following this comment I assumed it's ok to enable Cloudflare proxy on my captain root domain since it already had a SSL certificate generated by LE caprover. After enabling the proxy now I am unable to open the caprover admin page gives SSL error. Already tried disabling cloudflare proxy still same.
Any ideas?

**Comment by golyalpha** [comment]
Hey @ak4zh, the domain you use to access caprover wouldn't happen to be a 4th level domain, would it? (i.e. `admin.caprover.example.com`).

If that is the case, you will be unable to use CloudFlare Proxy and SSL with this domain on a free account. That's a limitation on CloudFlare's side.

**Comment by ak4zh** [comment]
@golyalpha Thanks that was the case.

**Comment by ak4zh** [comment]
@golyalpha For this to work on, does my caprover has to be on root domain `captain.example.com` or will it work if I have `captain.internal.example.com` ?
I am trying to not pollute my 1st level sub-domain with the automated domains caprover assigns for every app using the app name.

**Comment by golyalpha** [comment]
Well, what you can do is simply not proxy the autogenerated domains, but add custom first level domains that CNAME to the autogenerated one and have proxy enabled.

**Comment by 4abhinavjain** [comment]
Another possible workaround is through Cloudflare Tunnels (which I currently use on our production servers as well). Someone has used it with UptimeKuma on Caprover, and then mapping connecting it to Cloudflare DNS via Cloudflare tunnels: https://github.com/caprover/caprover/discussions/1626 . I will update if I managed to make it work.

**Comment by VictorioBerra** [comment]
@4abhinavjain I managed to make it work https://github.com/caprover/caprover/issues/1788#issuecomment-2652230031
