### ISSUE TITLE
[Deployment Issue] Convert "docker run ..." terminal to caprover

### ISSUE THREAD

**Issue by m4rcster** [caprover/caprover#778]
I'm new to caprover and docker. Most docker images are booted via docker run [some paramaters] or via a docker compose file. Is there a recipe to translate terminal instructions into a captain-definition file or dockerfile?

For example
```
docker run -d --name="home-assistant" -v /PATH_TO_YOUR_CONFIG:/config -v /etc/localtime:/etc/localtime:ro --net=host homeassistant/home-assistant:stable
```

https://www.home-assistant.io/docs/installation/docker/

**Comment by githubsaturn** [comment]
There is no converter, but it's quite simple:
- First, SSH to your server and run `mkdir /ha-config`
- Then go to the web GUI
- Create a new app and check the "Has Persistent Data" checkbox since you have `-v` flag (volume).
- Name your app "home-assistant"
- Go to your apps > "home-assistant" > "Deployent" tab and under "Method 6: Deploy via ImageName" just enter "homeassistant/home-assistant:stable'
- Go to your apps > "home-assistant" > "App Configs" and add two volumes:
- `/etc/localtime` to `/etc/localtime`
- `/config` in container to `/ha-config` in host

**Comment by githubsaturn** [comment]
Also note that if you want to use `--net=host`, you can't use CapRover because CapRover can't manage your container if it's using your host network directly.
