### ISSUE TITLE
Update Docker API default to 1.40

### ISSUE THREAD

**Issue by githubsaturn** [caprover/caprover#797]
CapRover is using Docker API v1.30 from a few years ago. We can upgrade this to use V1.40. By the looks of [the changelog](https://docs.docker.com/engine/api/version-history/), there is not any breaking changes that affect CapRover.

**Comment by githubsaturn** [comment]
Done here: https://github.com/caprover/caprover/commit/393d3a8e5a91162d9d9672fbca2372db5268bd66

**Comment by githubsaturn** [comment]
Make sure you have Docker v19.03 or above before upgrading to v1.8

```
apt update
apt full-upgrade
docker -v
```

**Comment by julianengel** [comment]
Hey! Just stumbled across the same issue after upgrading to 1.8.1, and took me some time to realize that the Admin UI wasn't working because of the wrong version of docker being installed. 

Just wanted to ask if this is written out anywhere, in the troubleshooting or release notes, or if you'd like it added via a PR?

> Make sure you have Docker v19.03 or above before upgrading to v1.8
> 
> ```
> apt update
> apt full-upgrade
> docker -v
> ```

**Comment by githubsaturn** [comment]
It's the first item in the [changelog here](https://github.com/caprover/caprover/blob/master/CHANGELOG.md#180---2020-08-16)

But feel free to add it to troubleshoothing
