### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by skiv71** [caprover/caprover#817]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:

Hi, sorry, this is docker and caprover related.... I've deployed a 1-click mongodb and its running, according to the default dockerfile for v4 (I assume). If I want to enable replicaSet, or add any other specific command line args to mongod, do I have to create a repo (like my node app) and a custom docker file with my args? I've checked the webUI for managing caprover, assumed I'd find a way to append or modify the cmd args?

Thanks

Neil

**Comment by skiv71** [comment]
Does Caprover use generic Dockerfiles from the official sources (i.e. mongodb 4.4) or does it have its own? I've looked and I cannot find it. I know when I need to add .npmrc functionality to my node app, someone posted a Dockerfile which I used, which I'm guessing was based on the 'default'?

**Comment by githubsaturn** [comment]
CapRover uses [official MongoDB image](https://github.com/caprover/one-click-apps/blob/24958039b47b4d68ec4c039b081bb82b4c4f548b/public/v4/apps/mongodb.yml#L3-L11). 

If you want to setup a replica set a MongoDB, you'd need to simply extend the official image. For example, you need to go to deployment tab, and **deploy a "Dockerfile", currently method 4,** with this content:

````
FROM mongo:4
CMD mongod --replSet ...... --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles
```

Since there is no "common" way to deploy a cluster, we can't add this as a one click app. There is a lot of customization that can be done with the sharding/clustering.

**Comment by skiv71** [comment]
Ah, I went looking for my issue, couldn't see it... thought it had been deleted. Wow, is that all that's needed to run my own set of CMD arguments?

I was about to copy and paste in the full Dockerfile from github.com/docker-library/mongo (sorry, still finding my feet with docker).

Caprover is ace though :o)
