### ISSUE TITLE
Is there a way to run with docker on different port

### ISSUE THREAD

**Issue by mck159** [caprover/caprover#823]
Hi,

I'm trying to run caprover on different port, so I can have multiple apps (caprover, gitlab) + separate nginx listening on port 80 that will act as reverse proxy to those apps based on host header. So e.g. gitlab.myhost.com could forward to myhost.com:81 and caprover.myhost.com could forward to myhost.com:82

I'm trying to change port maping in docker run command:
`docker run -e "MAIN_NODE_IP_ADDRESS=192.168.1.134" -p 81:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover`

But then trying to run container fails with following error:
```
Installation failed.
Error: Port seems to be closed: 80
    at Request._callback (/usr/src/app/built/utils/CaptainInstaller.js:149:24)
    at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:314:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

```

**Comment by githubsaturn** [comment]
CapRover doesn't work with custom ports. Let's Encrypt needs port 80 to function properly and more importantly CapRove purpose is to be the service that manages you application. Most likely, you don't need a separate nginx server. If you need to forward/redirect a subdomain to another domain you can do so from your DNS provider or from within CapRover.

**Comment by mck159** [comment]
Thanks for response

Thing is that I want to have multiple http apps (caprover, gitlab etc.) on one physical machine

I could do this e.g. by using nginx/apache/otherserver for virtual hosts

So lets say I have following configuration:

My NgInx/Apache or other reverse proxy server on port 80
Caprover on port 81
GitLab on port 82

When requests comes on subdomain caprover.myhost.com nginx/apache will proxy incoming traffic to port 81 (caprover)
When requests comes on subdomain gitlab.myhost.com nginx/apache will proxy incoming traffic to port 82 (gitlab)

Of course this way it would be transparent, so anyone who sends requests to caprover.myhost.com:80 will see it as caprover on port 80

This way request from Let's Encrypt would also come to CapRover as letsencrypt will see CapRover as listening on 80 (as reverse proxy provided by nginx/apache is transparent to client)

I think this is pretty usual use case for people who have single VPS for everything or some PC as server at home

**Comment by mck159** [comment]
btw. I see that other people asked for this as well, so probably it would help more people than just me if you would be able to do this (not sure how much work would it be for you)

https://github.com/caprover/caprover/issues/803
https://github.com/caprover/caprover/issues/720

I see that I second issue you've provided workaround on this, but I've tried and it no longer works

**Comment by githubsaturn** [comment]
> btw. I see that other people asked for this as well, so probably it would help more people than just me if you would be able to do this (not sure how much work would it be for you)

#720 is an unrelated issue. Changing the port is [literally a constant](https://github.com/caprover/caprover/blob/master/src/utils/CaptainConstants.ts#L146). The problem is the complications and issues that it arises. Basically maintenance cost vs benefit.

> This way request from Let's Encrypt would also come to CapRover as letsencrypt will see CapRover as listening on 80 (as reverse proxy provided by nginx/apache is transparent to client)

What about port 443? In that case the headers are encrypted and you can redirect on your apache server as CapRover's nginx has the cert keys.

I still don't understand why this is not possible by running CapRover at port 80 and have it forward requests to non 80 ports. Here is what I am suggesting:
- Install CapRover and run it as usual using port 80/443
- Create multiple apps on CapRover and have fun!
- Install gitlab and have it run on your localhost at port 81
- Create a one click app using "**Nginx Reverse Proxy**" on CapRover and call it `gitlab-router` for example. For `Upstream address` use `http://192.168.x.x:81` where `192.168.x.x` is your local IP address


![image](https://user-images.githubusercontent.com/10582082/92671017-435eb680-f2e3-11ea-9338-454a7a6bfad1.png)

**Comment by srsquare** [comment]
I agree with the above, it is dumb to not allow changing ports on docker. I can use a reverse proxy to handle the SSL, etc. So saying ports 80 and 443 are required for SSL is useless for me as I want to handle that via the reverse proxy. For the exact reason, I can't use this app, which appears to support way more apps than portainer or yacht templates do so that makes me sad!

**Comment by ahgsql** [comment]
> CapRover doesn't work with custom ports. Let's Encrypt needs port 80 to function properly and more importantly CapRove purpose is to be the service that manages you application. Most likely, you don't need a separate nginx server. If you need to forward/redirect a subdomain to another domain you can do so from your DNS provider or from within CapRover.

How to do this? I need to install supabase self-hosted inside my server which caprover installed too. I need supastudio for ui and for api i need another subdomain, and in need of nginx proxy manager
