### ISSUE TITLE
Self-signed SSL certificate is used only when using "www."

### ISSUE THREAD

**Issue by cooldoganytime** [caprover/caprover#824]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
When I access my website without prefixing "www." (e.g. https://[rootdomain].com) then it works fine and it is using a valid certificate issued by Let's Encrypt. When I attempt to access my website when prefixing "www." (e.g. https://www.[rootdomain].com) then I receive connection error ERR_CERT_AUTHORITY_INVALID because the website is using a self-signed certificate.

Some more background: This Caprover instance is hosted on a DigitalOcean droplet. I had previously deployed the same website with the same domain on a different droplet and did not experience this issue. However I destroyed that droplet and created a new one with the same codebase and domain (for an unrelated reason). The issue occurred after deploying Caprover to the new droplet. In my networking settings I only have A records that are associated with my droplet IPv4 address.

I already tried these troubleshooting methods, based on other issues I saw here:
-Restarted Caprover via 'docker service update captain-captain --force'
-Changed root domain in Caprover panel and re-enabled SSL (also re-enabled SSL for each app individually)
-Disabled SSL flag by accessing 'nano /captain/data/config-captain.json' and then re-enabled SSL in the Caprover panel
-I tried forcing certbot to renew certificates ('certbot renew --force-renewal') which ran successfully, but did not change anything

If applicable, content of `captain-definition` file:
N/A. I have no issues with deploying.

Steps to reproduce the problem:
I went through the normal setup process via the setup guide and enabled SSL. For reference, my website is live here:
peepthis.app (certificate works)
www.peepthis.app (certificate doesn't work)

Answers to the following questions where applicable:
N/A

Thank you!

**Comment by prikr** [comment]
Hi. I experienced this issue too, and i fixed it by changing the rootdomain. 

My first situation was that my rootdomain was: `exampledomain.nl`
In this situation I was able to visit the captain panel through `captain.exampledomain.nl`. And my production app couldn't point to `www.exampledomain.nl`, that caused an error. In this situation i only added one A record, which was a wildcard pointing to the IP of my droplet.

The problem is that your rootdomain should be an subdomain of your actual rootdomain. In my case i used a fancy word _elixer_
and now my captain dashboard is available at `captain.elixer.exampledomain.nl`. With that I had to set a new a record: elixer.exampledomain.nl   A   pointing to droplets IP, but also keep the wildcard record, because u can use that for picking new domains for your app.

In the new situation (with captain.elixer.exampledomain.nl) you can now point **one** app to www.exampledomain.nl AND exampledomain.nl

**Comment by cooldoganytime** [comment]
@prikr Yep, that solved it. I had to change my root domain to include a subdomain ('caprover.peepthis.app') and then I added 'www.peepthis.app' (in addition to 'peepthis.app') as a URL for my frontend app. Now SSL works for both URLs. Just to reiterate to anyone reading this: you can only include 'www.' in the URL for an app if you have a subdomain in your root domain! I had done this before, but I completely forgot when I re-deployed Caprover.

Thanks so much for taking the time to reply! I spent way too much time trying to figure this out.

Closing this issue. Hopefully this helps someone else in the future.
