### ISSUE TITLE
Unable to access through the app's exposed port with private ip

### ISSUE THREAD

**Issue by AngeloReppucci** [caprover/caprover#853]
Hi, many thanks for your work. Caprover it's amazing!

My question is about access to a container through its exposed port. I've a server (Ubuntu 18.04) with a public IP on eth0 and a private IP on ens10. Caprover is installed and all is working fine.

The problem is the following:

I installed the ssh one click app (but the problem is with every app). If i try to connect with the public ip of the host on the port exposed by the app all is working. I i try to connect with the private ip of the host on the exposed port, i receive a connection timeout.

To do some test i also disabled the firewall (UFW) but nothing has changed.

Looking at the caprover's server syslog i found the following message:

IPv4: martian source 172.18.0.2 from 10.0.0.2, on dev eth1

The strange thing is that eth1 is not an existing interface.

Can someone help me please?

Many thanks.

**Comment by githubsaturn** [comment]
CapRover uses [Docker overlay mesh network](https://docs.docker.com/network/overlay/)

Because Docker swarm was created on your public IP, all your port bindings that go through overlay mesh network only bind to your public IP. If you really need to bind to private IP, you can try using the "host" mode of Docker. To do so, you'll have to [override default Docker service configs](https://caprover.com/docs/service-update-override.html)

**Comment by AngeloReppucci** [comment]
Hi @githubsaturn,

i'm struggling with solving this problem. 
I was unable to find how to set mode="host" through the Service Update Override of caprover. I cannot find what is the yaml key to use to do this.

Please can you help me with a small example of the yaml configuration?

Many thanks in advance.
