### ISSUE TITLE
[Question] Can nginx logs be persistent for protection with fail2ban?

### ISSUE THREAD

**Issue by Turab** [caprover/caprover#880]
Hi.

I have installed fail2ban on the Caprover server to protect against simple attacks like brute force. Caprover itself already runs on nginx and I would like to protect it with fail2ban so that brute force attacks on Caprover login could be stopped. You know that nginx runs on its own container and as far as I know it doesn't have persistent data; so I can't have access to nginx error logs.

How can I get absolute path of the nginx error log on the host?

I am for example using fail2ban for Bitwarden_rs since I have defined its data directory as persistent and now I can point the log file in fail2ban conf like;

/var/lib/docker/volumes/captain--bitwarden/_data/bitwarden.log

Now it protects Bitwarden against password guessing attacks.

**Comment by githubsaturn** [comment]
There are a few directories in nginx image that are persistent. Specifically `/captain/data/nginx-shared` is mapped to `/nginx-shared` inside the container.

To use this location to store your logs, you can go to settings > edit nginx config.


PS: you probably don't need to do this as CapRover has built in bruteforce guard that limits the wrong password to 6 per 30sec. This makes bruteforcing practically impossible.

**Comment by bevinhex** [comment]
I think the idea here is not to protect caprover, but other http services that exposed by caprover nginx container, I do have fail2ban protecting host ssh port, but when ddos is happening , containers are spinning like crazy taking up lots of CPU power, looking for possible solutions

**Comment by valensto** [comment]
@bevinhex do you found something interesting ?

**Comment by bevinhex** [comment]
I found few options to the problem:
1. setup individual applications to use persistent storage or mapped folder, so that their log file can appear within host folders (/var/log*), then setup fail2ban to monitor those files
2. assuming each application's logs are redirected to docker stdout (most of the time it is ), thus use https://hub.docker.com/r/gliderlabs/logspout, which can then redirect docker logs into server log files ( or even remote log servers in case needed), now setup fail2ban to parse those log file(s) on the host machine
Haven't implemented myself yet due to other priorities, but think this is good approach.
