### ISSUE TITLE
[Question]Deploy application to root domain instead of subdomain. 

### ISSUE THREAD

**Issue by ajitgoel** [caprover/caprover#898]
Hopefully this is a newbie question. 
I have created a new app under "Apps" and I am trying to deploy my .Net Core application to it. 
![image](https://user-images.githubusercontent.com/6394444/98423171-6f808480-2053-11eb-9434-398aa67aa030.png)
When I try to run the `caprover deploy `command, I can select the new "app" that I have created. 
How can I change the application to point to `https://www.instatranscribe.com`(instead of `https://app.instatranscribe.com`) i.e deploy the application to the root domain instead of the subdomain?

**Comment by denis-roy** [comment]
Good day @ajitgoel,

You can use the "Connect New Domain" button to enter the subdomain.domain.tld you want to use for your app, so in your case this would be:

![image](https://user-images.githubusercontent.com/3801326/98428496-a1dfb100-2056-11eb-9e9c-5e139c800e28.png)

**Comment by ajitgoel** [comment]
Thank you @denis-roy for your input, when I did that, I got a `1104 : Domain name is not accepted. Custom domain cannot be subdomain of root domain.` error message.

**Comment by denis-roy** [comment]
I presume there might be a problem with your wildcard root.

I will share how I manage it, it might be easier for you to inspire you from my setup than for me to guess yours :)

My Caprover wildcard root is `cr.domain.tld`
Captain is reachable at `captain.cr.domain.tld`
My app lives at `app.cr.domain.tld`

I then set `www.domain.tld` using the "Connect New Domain" button from withtin my app dashboard and voilà

Hope this help :)

**Comment by githubsaturn** [comment]
@denis-roy is correct.

@ajitgoel , your wildcard setup is shallow. With your setup if you create an app called `www` it'll take over `www.domain.com` .


It's generally recommended to use a deeper wildcard for your root domain, like `*.something.domain.com`

**Comment by ajitgoel** [comment]
Thank you @githubsaturn, @denis-roy  for your inputs , I changed the app name from `app` to `www` to fix the issue.

**Comment by lars1134** [comment]
Some docker apps (like peertube) don't support running on other domains other than the domain they are deployed on.

Lets say, I wanted to (for some extra security) deploy caprover on: captain.doggy.milk.kitten.sweet.net

When I deploy Peertube, I can give it a name, like Peertube. It will deploy on: peertube.doggy.milk.kitten.sweet.net But I want it to be deployed on peertube.sweet.net. Or on peertube.bad.monster

Now, I can link peertube.sweet.net to peertube in caprover. But the peertube app is unable to 'run' on this domainname. It will forever run on peertube.doggy.milk.kitten.sweet.net.

Is there anything I can do to **deploy** apps on custom domains?

**Comment by githubsaturn** [comment]
@lars1134  - yes. It really depends on how one click apps are developed and templetized in CapRover. They are community maintained, so there is no unique way that works for all of them:

In case of PeerTube, I think you can just update this [env var](https://github.com/caprover/one-click-apps/blob/5041131cd5d83ef517af08934184380316608fe9/public/v4/apps/peertube.yml#L35) and it works.

So simply after deploying the app, go to your app config and change that environmental variable. Most probably it'll work. If not, it means that they do store the variable somewhere in the database when the application gets initialized for the first time. In that case:
* Simply copy the entire content of `peertube.yml` from the link above
* Create a one click app, instead of PeerTube, choose "Template" and paste the content
* Before clicking NEXT, update the env variable in the text box and change it to `peertube.bad.monster` 
* Go ahead and deploy your app
* Connect the new domain (`peertube.bad.monster`) to it

**Comment by lars1134** [comment]
@githubsaturn Thank you very much for your answer. I will try it out this weekend.

**Comment by kwiat1990** [comment]
> 
I have tried the very same thing but it doesn’t work. Do I need change DNS of the domain to point to the servers‘s IP as well?

Currently I set an A Record, following docs, for `*.foo.domain.tld` to point to the server‘s IP.

**Comment by githubsaturn** [comment]
Yes.
