### ISSUE TITLE
[Deployment Issue]

### ISSUE THREAD

**Issue by tonxxd** [caprover/caprover#915]
What is the problem?
I am not able to deploy any one click apps

Steps to reproduce the problem:
Create a one click mongodb app (I have other caprover machines and it's the first time I am getting this error)
Could be related to the remote registry? I don't think so but I cannot understand what that error means.
(I have also another nodejs app deployed with imageName method from gitlab registry)

Answers to the following questions if applicable:
- Your OS and version? Ubuntu x86_64 
- RAM? 2gb 2cores
<img width="852" alt="Schermata 2020-11-20 alle 10 24 13" src="https://user-images.githubusercontent.com/2827496/99783734-1a487680-2b1b-11eb-88c9-47c2996b71a8.png">

**Comment by githubsaturn** [comment]
> Could be related to the remote registry? I don't think so but I cannot understand what that error means.

Yes, it's related. You have set up a Docker registry on your CLUSTER page and you don't have write access to it. To fix, you need to disable the push:
![image](https://user-images.githubusercontent.com/10582082/99799476-bc0e9a00-2b00-11eb-9de3-a64f1da43e50.png)


NOTE: YOU CANNOT DO THIS if you have a cluster of nodes. In that case, you need to fix the root cause of your issue which is not having access to the registry in the first place

**Comment by tonxxd** [comment]
Perfect thank you very much for the clarification :)
