### ISSUE TITLE
Support for encrypted / edit-only environment variables

### ISSUE THREAD

**Issue by amatzen** [caprover/caprover#917]
**Is your feature request related to a problem? Please describe.**
Most apps use environment variables to store secrets, e.g. admin password, app-key for randomizing and encryption etc. I think we should protect those values better.

**Describe the solution you'd like**
Cloudflare Workers has support for encrypted environment variables, where first entered, you can only edit the value - not displayable in any way. I could see the same feature be implemented with a checkmark to each environment variable and a popup confirmation dialogue, which removes access to readability for the token.

**Additional context**
Visualization of my idea:

☃|**Before**|**After**
:-----:|:-----:|:-----:
Key Value Edit|![Before - KV-edit](https://screenshots.amatzen.dk/O50SzuDZjKNf0UriPR.png)|![After - KV-edit](https://screenshots.amatzen.dk/NNWIfqLoWRTJVnYN5T.png)
Bulk Edit|![Before - Bulk-edit](https://screenshots.amatzen.dk/0LPHKV00yh3oindrK8.png)|![After - Bulk-edit](https://screenshots.amatzen.dk/oHKhaAN1HxJkzrNfg5.png)

**Comment by githubsaturn** [comment]
This has previously been discussed. The data is sent back to the client. Hiding it on the UI doesn't provide much value as the data is visible underneath. In most cases this is fine since however has access to the dashboard essentially has access to all the content of all containers.

However, if your use case requires extra hardening. You can manually create a docker secret on the server and just docker update to add the secret to your app:
````
docker service update \
    --secret-add source=ssh-2,target=ssh-2 \
    myservice
```
