### ISSUE TITLE
[Question] How to access root folder from container?

### ISSUE THREAD

**Issue by marcusique** [caprover/caprover#945]
Hi,

I have several apps running in Caprover and to simplify event logging I want to collect logs in a folder that I created under /app-logs (root file system). The folder has 777 permission, but the logging won't happen. As far as I understand I need to somehow bind this directory to the container, but can't quite figure out how. Could you please give me a hint?
Thanks!

**Comment by maietta** [comment]
Caprover is a "layer" upon Docker and Docker Swarm. As such, you can use your standard methods of querying for information about the Services that Caprover deploys and manages.

For example, you can list your services to find the service ID's:
docker service ls

Then refer to the ID on first column to fetch all the current logs for that service like so:

docker service logs q9xx0sqh4e8r > capture.log

For further information about what you can do with Docker and Docker Swarm via the command line interface (CLI), please refer to the CLI section of the Docker Docs at https://docs.docker.com/engine/reference/commandline/service/.

Keep in mind that Docker Services will have a different command set than individual docker containers. You will want to work with running services rather than individual containers given that you are deploying apps as services via Caprover.

**Comment by maietta** [comment]
To follow up, if you need Docker Service logs to be funneled to a log processing utility or services, you literally have hundreds of services and thousands of tools you can use. You will need to figure out what your goals are exactly, then start looking for a solution that meets your needs (or build your own) but your baseline problem of collecting logs can be done directly from the Docker API or the command line environment. I would avoid trying to access the files from the host system directly and instead build your tooling to work directly with the API or CLI. This gives you a better and more consistent way of accessing your logs, even across different manager nodes you may be running.

Good luck!

**Comment by githubsaturn** [comment]
@maietta is correct - ideally you'd want to post your application's log to stdout. But if that's not possible you'd rather keep `/app-logs` directory, all you need to:
- First, when you create your app, make sure it's marked as "Has Persistent Data". You cannot change this once you created your app. If you missed this, create a new app with persistence.
- Next, create a directory on your host, like `mkdir /my-app-logs` 
- Navigate to Apps > Your App and map `app-logs` to `/my-app-logs` - see below:

![image](https://user-images.githubusercontent.com/10582082/102818803-5da73680-43a0-11eb-8d82-3a7cbc7156f2.png)

**Comment by marcusique** [comment]
@maietta, thank you for comprehensive details!
@githubsaturn, this is just what I needed. Thanks a whole lot.
