### ISSUE TITLE
[Tech Debt] Should we consider modernizing code to Async/Await?

### ISSUE THREAD

**Issue by amanvishnani** [caprover/caprover#951]
1. The project uses a Promise based approach which when chained together makes code hard to read and comprehend. 
2. Async/Await has now been around for a long time with first-class support in Node.js
3. We can consider modernizing the code by refactoring to Async/Await based approach. 
4. We can breakdown this task into multiple sub-tasks. Each sub-task will work on a specific set of files.

**Comment by githubsaturn** [comment]
TLDR: No.

Using promises is not a tech debt. Using async/await is just one opinionated style among many. It's similar to spread syntax, and etc. It's different from other modern concepts that avoid bugs and/or increase developer productivity, such as, typing, const/let and etc. Chasing what considered "modern" just because it's a new shiny thing only increases the maintainable cost, introduces potential bugs and reduces the development productivity due to the ever-changing landscape of the code base.

**Comment by zenflow** [comment]
I agree. Not using the latest language features is not tech debt. The latest language features just help sometimes to clean & simplify code. In the case where code is too complex, _that_ (the over complexity) is the tech debt, not the fact that you're not using the latest features itself.

If there was some area of code that could be greatly simplified by using async/await, that would make a good argument.

I think in many cases async/await doesn't help to simplify at all.
