### ISSUE TITLE
[Question] Deployment options and suggestions?

### ISSUE THREAD

**Issue by ylluminate** [caprover/caprover#992]
We primarily work with cPanel+CentOS based servers, but can be flexible. Do you have an optimal or suggested Docker server distro (such as Photon OS or another) that you've found to work best for CapRover?

**Comment by maietta** [comment]
Taken directly from the docs at https://caprover.com/docs/get-started.html

CPU Architecture: Although CapRover source code is compatible with any CPU architecture, the Docker build available on Docker Hub is built for x86 CPU. Therefore, If your CPU is ARM, you can download the source code and build it on your ARM architecture in order to run it.

Recommended Stack: CapRover is tested on Ubuntu 18.04 and Docker 19.03. If you're using CapRover on a different OS, you might want to look at Docker Docs.

**Comment by githubsaturn** [comment]
Exactly what @maietta said. 

CapRover is basically a layer on top of Docker. So technically it can run on any Docker compliant linux distribution. But different flavors has their own issues. Even for Ubuntu, we found that Ubuntu 20 has some issues with Docker that haven't been resolved yet. So Ubuntu 18 is the way to go for now.

**Comment by ylluminate** [comment]
Interesting, I'm really not an enormous fan of working with Docker on Ubuntu, but I'll have to explore this.  Has anyone had success with Photon OS or another specialized Docker distro?  I ask in that I haven't seen any such discussion so far, which surprised me.

**Comment by githubsaturn** [comment]
Feel free to try it out on other OS and share your experience in the docs. Like I said, technically, CapRover works on any Docker complaint linux distribution. But previously some distributions showed weird glitches (that might have been fixed by now). IIRC CentOS had some issues with mapped volumes. Ubuntu 20 has issues with overlay network. and etc...

Docs are open source and editable.
